// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Kind{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AccountsConferencesParticipantsParameters are the configurable fields of a AccountsConferencesParticipants.
//
// These are the parameters of the create operation (CreateParticipant), plus any the
// update accepts and the create does not. The fields are spelled the way
// Twilio TAKES them -- PascalCase -- because that is the name the request
// carries; status.atProvider spells the same values the way Twilio ANSWERS
// them, in snake_case. Nothing translates between the two, so nothing can
// drift out of a translation layer.
type AccountsConferencesParticipantsParameters struct {
	// ConferenceSid The SID of the participant's conference.
	// +kubebuilder:validation:Required
	ConferenceSid string `json:"ConferenceSid"`
	// From The phone number, Client identifier, or username portion of SIP address that made this call. Phone numbers are in [E.164](https://www.twilio.com/docs/glossary/what-e164) format (e.g., +16175551212). Client identifiers are formatted `client:name`. If using a phone number, it must be a Twilio number or a Verified [outgoing caller id](https://www.twilio.com/docs/voice/api/outgoing-caller-ids) for your account. If the `to` parameter is a phone number, `from` must also be a phone number. If `to` is sip address, this value of `from` should be a username portion to be used to populate the P-Asserted-Identity header that is passed to the SIP endpoint.
	// +kubebuilder:validation:Required
	From string `json:"From"`
	// To The phone number, SIP address, Client, TwiML App identifier that received this call. Phone numbers are in [E.164](https://www.twilio.com/docs/glossary/what-e164) format (e.g., +16175551212). SIP addresses are formatted as `sip:name@company.com`. Client identifiers are formatted `client:name`. TwiML App identifiers are formatted `app:<APP_SID>`. [Custom parameters](https://www.twilio.com/docs/voice/api/conference-participant-resource#custom-parameters) may also be specified.
	// +kubebuilder:validation:Required
	To string `json:"To"`
	// PathAccountSid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that will create the resource.
	// +optional
	PathAccountSid string `json:"PathAccountSid,omitempty"`
	// StatusCallback The URL we should call using the `status_callback_method` to send status information to your application.
	// +optional
	StatusCallback string `json:"StatusCallback,omitempty"`
	// StatusCallbackMethod The HTTP method we should use to call `status_callback`. Can be: `GET` and `POST` and defaults to `POST`.
	// +optional
	StatusCallbackMethod string `json:"StatusCallbackMethod,omitempty"`
	// StatusCallbackEvent The conference state changes that should generate a call to `status_callback`. Can be: `initiated`, `ringing`, `answered`, and `completed`. Separate multiple values with a space. The default value is `completed`.
	// +optional
	StatusCallbackEvent []string `json:"StatusCallbackEvent,omitempty"`
	// Label A label for this participant. If one is supplied, it may subsequently be used to fetch, update or delete the participant.
	// +optional
	Label string `json:"Label,omitempty"`
	// Timeout The number of seconds that we should allow the phone to ring before assuming there is no answer. Can be an integer between `5` and `600`, inclusive. The default value is `60`. We always add a 5-second timeout buffer to outgoing calls, so value of 10 would result in an actual timeout that was closer to 15 seconds.
	// +optional
	Timeout int `json:"Timeout,omitempty"`
	// Record Whether to record the participant and their conferences, including the time between conferences. Can be `true` or `false` and the default is `false`.
	// +optional
	Record bool `json:"Record,omitempty"`
	// Muted Whether the agent is muted in the conference. Can be `true` or `false` and the default is `false`.
	// +optional
	Muted bool `json:"Muted,omitempty"`
	// Beep Whether to play a notification beep to the conference when the participant joins. Can be: `true`, `false`, `onEnter`, or `onExit`. The default value is `true`.
	// +optional
	Beep string `json:"Beep,omitempty"`
	// StartConferenceOnEnter Whether to start the conference when the participant joins, if it has not already started. Can be: `true` or `false` and the default is `true`. If `false` and the conference has not started, the participant is muted and hears background music until another participant starts the conference.
	// +optional
	StartConferenceOnEnter bool `json:"StartConferenceOnEnter,omitempty"`
	// EndConferenceOnExit Whether to end the conference when the participant leaves. Can be: `true` or `false` and defaults to `false`.
	// +optional
	EndConferenceOnExit bool `json:"EndConferenceOnExit,omitempty"`
	// WaitUrl The URL that Twilio calls using the `wait_method` before the conference has started. The URL may return an MP3 file, a WAV file, or a TwiML document. The default value is the URL of our standard hold music. If you do not want anything to play while waiting for the conference to start, specify an empty string by setting `wait_url` to `''`. For more details on the allowable verbs within the `waitUrl`, see the `waitUrl` attribute in the [<Conference> TwiML instruction](https://www.twilio.com/docs/voice/twiml/conference#attributes-waiturl).
	// +optional
	WaitUrl string `json:"WaitUrl,omitempty"`
	// WaitMethod The HTTP method we should use to call `wait_url`. Can be `GET` or `POST` and the default is `POST`. When using a static audio file, this should be `GET` so that we can cache the file.
	// +optional
	WaitMethod string `json:"WaitMethod,omitempty"`
	// EarlyMedia Whether to allow an agent to hear the state of the outbound call, including ringing or disconnect messages. Can be: `true` or `false` and defaults to `true`.
	// +optional
	EarlyMedia bool `json:"EarlyMedia,omitempty"`
	// MaxParticipants The maximum number of participants in the conference. Can be a positive integer from `2` to `250`. The default value is `250`.
	// +optional
	MaxParticipants int `json:"MaxParticipants,omitempty"`
	// ConferenceRecord Whether to record the conference the participant is joining. Can be: `true`, `false`, `record-from-start`, and `do-not-record`. The default value is `false`.
	// +optional
	ConferenceRecord string `json:"ConferenceRecord,omitempty"`
	// ConferenceTrim Whether to trim leading and trailing silence from the conference recording. Can be: `trim-silence` or `do-not-trim` and defaults to `trim-silence`.
	// +optional
	ConferenceTrim string `json:"ConferenceTrim,omitempty"`
	// ConferenceStatusCallback The URL we should call using the `conference_status_callback_method` when the conference events in `conference_status_callback_event` occur. Only the value set by the first participant to join the conference is used. Subsequent `conference_status_callback` values are ignored.
	// +optional
	ConferenceStatusCallback string `json:"ConferenceStatusCallback,omitempty"`
	// ConferenceStatusCallbackMethod The HTTP method we should use to call `conference_status_callback`. Can be: `GET` or `POST` and defaults to `POST`.
	// +optional
	ConferenceStatusCallbackMethod string `json:"ConferenceStatusCallbackMethod,omitempty"`
	// ConferenceStatusCallbackEvent The conference state changes that should generate a call to `conference_status_callback`. Can be: `start`, `end`, `join`, `leave`, `mute`, `hold`, `modify`, `speaker`, and `announcement`. Separate multiple values with a space. Defaults to `start end`.
	// +optional
	ConferenceStatusCallbackEvent []string `json:"ConferenceStatusCallbackEvent,omitempty"`
	// RecordingChannels The recording channels for the final recording. Can be: `mono` or `dual` and the default is `mono`.
	// +optional
	RecordingChannels string `json:"RecordingChannels,omitempty"`
	// RecordingStatusCallback The URL that we should call using the `recording_status_callback_method` when the recording status changes.
	// +optional
	RecordingStatusCallback string `json:"RecordingStatusCallback,omitempty"`
	// RecordingStatusCallbackMethod The HTTP method we should use when we call `recording_status_callback`. Can be: `GET` or `POST` and defaults to `POST`.
	// +optional
	RecordingStatusCallbackMethod string `json:"RecordingStatusCallbackMethod,omitempty"`
	// SipAuthUsername The SIP username used for authentication.
	// +optional
	SipAuthUsername string `json:"SipAuthUsername,omitempty"`
	// SipAuthPassword The SIP password for authentication.
	// +optional
	SipAuthPassword string `json:"SipAuthPassword,omitempty"`
	// Region The [region](https://support.twilio.com/hc/en-us/articles/223132167-How-global-low-latency-routing-and-region-selection-work-for-conferences-and-Client-calls) where we should mix the recorded audio. Can be:`us1`, `us2`, `ie1`, `de1`, `sg1`, `br1`, `au1`, or `jp1`.
	// +optional
	Region string `json:"Region,omitempty"`
	// ConferenceRecordingStatusCallback The URL we should call using the `conference_recording_status_callback_method` when the conference recording is available.
	// +optional
	ConferenceRecordingStatusCallback string `json:"ConferenceRecordingStatusCallback,omitempty"`
	// ConferenceRecordingStatusCallbackMethod The HTTP method we should use to call `conference_recording_status_callback`. Can be: `GET` or `POST` and defaults to `POST`.
	// +optional
	ConferenceRecordingStatusCallbackMethod string `json:"ConferenceRecordingStatusCallbackMethod,omitempty"`
	// RecordingStatusCallbackEvent The recording state changes that should generate a call to `recording_status_callback`. Can be: `started`, `in-progress`, `paused`, `resumed`, `stopped`, `completed`, `failed`, and `absent`. Separate multiple values with a space, ex: `'in-progress completed failed'`.
	// +optional
	RecordingStatusCallbackEvent []string `json:"RecordingStatusCallbackEvent,omitempty"`
	// ConferenceRecordingStatusCallbackEvent The conference recording state changes that generate a call to `conference_recording_status_callback`. Can be: `in-progress`, `completed`, `failed`, and `absent`. Separate multiple values with a space, ex: `'in-progress completed failed'`
	// +optional
	ConferenceRecordingStatusCallbackEvent []string `json:"ConferenceRecordingStatusCallbackEvent,omitempty"`
	// Coaching Whether the participant is coaching another call. Can be: `true` or `false`. If not present, defaults to `false` unless `call_sid_to_coach` is defined. If `true`, `call_sid_to_coach` must be defined.
	// +optional
	Coaching bool `json:"Coaching,omitempty"`
	// CallSidToCoach The SID of the participant who is being `coached`. The participant being coached is the only participant who can hear the participant who is `coaching`.
	// +optional
	CallSidToCoach string `json:"CallSidToCoach,omitempty"`
	// JitterBufferSize Jitter buffer size for the connecting participant. Twilio will use this setting to apply Jitter Buffer before participant's audio is mixed into the conference. Can be: `off`, `small`, `medium`, and `large`. Default to `large`.
	// +optional
	JitterBufferSize string `json:"JitterBufferSize,omitempty"`
	// Byoc The SID of a BYOC (Bring Your Own Carrier) trunk to route this call with. Note that `byoc` is only meaningful when `to` is a phone number; it will otherwise be ignored. (Beta)
	// +optional
	Byoc string `json:"Byoc,omitempty"`
	// CallerId The phone number, Client identifier, or username portion of SIP address that made this call. Phone numbers are in [E.164](https://www.twilio.com/docs/glossary/what-e164) format (e.g., +16175551212). Client identifiers are formatted `client:name`. If using a phone number, it must be a Twilio number or a Verified [outgoing caller id](https://www.twilio.com/docs/voice/api/outgoing-caller-ids) for your account. If the `to` parameter is a phone number, `callerId` must also be a phone number. If `to` is sip address, this value of `callerId` should be a username portion to be used to populate the From header that is passed to the SIP endpoint.
	// +optional
	CallerId string `json:"CallerId,omitempty"`
	// CallReason The Reason for the outgoing call. Use it to specify the purpose of the call that is presented on the called party's phone. (Branded Calls Beta)
	// +optional
	CallReason string `json:"CallReason,omitempty"`
	// RecordingTrack The audio track to record for the call. Can be: `inbound`, `outbound` or `both`. The default is `both`. `inbound` records the audio that is received by Twilio. `outbound` records the audio that is sent from Twilio. `both` records the audio that is received and sent by Twilio.
	// +optional
	RecordingTrack string `json:"RecordingTrack,omitempty"`
	// RecordingConfigurationId The identifier of the configuration to be used when creating and processing the recording
	// +optional
	RecordingConfigurationId string `json:"RecordingConfigurationId,omitempty"`
	// TimeLimit The maximum duration of the call in seconds. Constraints depend on account and configuration.
	// +optional
	TimeLimit int `json:"TimeLimit,omitempty"`
	// MachineDetection Whether to detect if a human, answering machine, or fax has picked up the call. Can be: `Enable` or `DetectMessageEnd`. Use `Enable` if you would like us to return `AnsweredBy` as soon as the called party is identified. Use `DetectMessageEnd`, if you would like to leave a message on an answering machine. For more information, see [Answering Machine Detection](https://www.twilio.com/docs/voice/answering-machine-detection).
	// +optional
	MachineDetection string `json:"MachineDetection,omitempty"`
	// MachineDetectionTimeout The number of seconds that we should attempt to detect an answering machine before timing out and sending a voice request with `AnsweredBy` of `unknown`. The default timeout is 30 seconds.
	// +optional
	MachineDetectionTimeout int `json:"MachineDetectionTimeout,omitempty"`
	// MachineDetectionSpeechThreshold The number of milliseconds that is used as the measuring stick for the length of the speech activity, where durations lower than this value will be interpreted as a human and longer than this value as a machine. Possible Values: 1000-6000. Default: 2400.
	// +optional
	MachineDetectionSpeechThreshold int `json:"MachineDetectionSpeechThreshold,omitempty"`
	// MachineDetectionSpeechEndThreshold The number of milliseconds of silence after speech activity at which point the speech activity is considered complete. Possible Values: 500-5000. Default: 1200.
	// +optional
	MachineDetectionSpeechEndThreshold int `json:"MachineDetectionSpeechEndThreshold,omitempty"`
	// MachineDetectionSilenceTimeout The number of milliseconds of initial silence after which an `unknown` AnsweredBy result will be returned. Possible Values: 2000-10000. Default: 5000.
	// +optional
	MachineDetectionSilenceTimeout int `json:"MachineDetectionSilenceTimeout,omitempty"`
	// AmdStatusCallback The URL that we should call using the `amd_status_callback_method` to notify customer application whether the call was answered by human, machine or fax.
	// +optional
	AmdStatusCallback string `json:"AmdStatusCallback,omitempty"`
	// AmdStatusCallbackMethod The HTTP method we should use when calling the `amd_status_callback` URL. Can be: `GET` or `POST` and the default is `POST`.
	// +optional
	AmdStatusCallbackMethod string `json:"AmdStatusCallbackMethod,omitempty"`
	// Trim Whether to trim any leading and trailing silence from the participant recording. Can be: `trim-silence` or `do-not-trim` and the default is `trim-silence`.
	// +optional
	Trim string `json:"Trim,omitempty"`
	// CallToken A token string needed to invoke a forwarded call. A call_token is generated when an incoming call is received on a Twilio number. Pass an incoming call's call_token value to a forwarded call via the call_token parameter when creating a new call. A forwarded call should bear the same CallerID of the original incoming call.
	// +optional
	CallToken string `json:"CallToken,omitempty"`
	// Passports The STIR/SHAKEN passport for this call, provided as a base64 encoded string. Multiple passports (at max 5) are comma separated and provided as base64 encoded string
	// +optional
	Passports string `json:"Passports,omitempty"`
	// ClientNotificationUrl The URL that we should use to deliver `push call notification`.
	// +optional
	ClientNotificationUrl string `json:"ClientNotificationUrl,omitempty"`
	// CallerDisplayName The name that populates the display name in the From header. Must be between 2 and 255 characters. Only applicable for calls to sip address.
	// +optional
	CallerDisplayName string `json:"CallerDisplayName,omitempty"`
	// EmergencyCallerPosition The emergency caller's GPS coordinates in decimal degrees format. Format: \\\"latitude longitude\\\" (space-separated) - Latitude: decimal degrees, range -90.0 to +90.0 (negative for South, positive for North) - Longitude: decimal degrees, range -180.0 to +180.0 (negative for West, positive for East) - Precision: up to 6 decimal places recommended for meter-level accuracy Note: If the value exceeds 150 characters, only the first 150 characters will be used.
	// +optional
	EmergencyCallerPosition string `json:"EmergencyCallerPosition,omitempty"`
	// EmergencyCallerLocation The emergency caller's physical location description within a building or facility. Note: If the value exceeds 20 characters, only the first 20 characters will be used.
	// +optional
	EmergencyCallerLocation string `json:"EmergencyCallerLocation,omitempty"`
	// EmergencyName The emergency caller's organization or entity name. Note: If the value exceeds 20 characters, only the first 20 characters will be used.
	// +optional
	EmergencyName string `json:"EmergencyName,omitempty"`
	// EmergencyAddress The emergency caller's street address including street number and street name. Note: If the value exceeds 60 characters, only the first 60 characters will be used.
	// +optional
	EmergencyAddress string `json:"EmergencyAddress,omitempty"`
	// EmergencyZipCode The emergency caller's postal code or ZIP code. Note: If the value exceeds 20 characters, only the first 20 characters will be used.
	// +optional
	EmergencyZipCode string `json:"EmergencyZipCode,omitempty"`
	// EmergencyCity The emergency caller's city or municipality name. Should be the official city name as recognized by local authorities. Used in combination with state and country for emergency call routing. Note: If the value exceeds 20 characters, only the first 20 characters will be used.
	// +optional
	EmergencyCity string `json:"EmergencyCity,omitempty"`
	// EmergencyState The emergency caller's state or province. Note: If the value exceeds 20 characters, only the first 20 characters will be used.
	// +optional
	EmergencyState string `json:"EmergencyState,omitempty"`
	// EmergencyCountry The emergency caller's country. Currently supported US and CA only. Note: If the value exceeds 20 characters, only the first 20 characters will be used.
	// +optional
	EmergencyCountry string `json:"EmergencyCountry,omitempty"`
	// Hold Whether the participant should be on hold. Can be: `true` or `false`. `true` puts the participant on hold, and `false` lets them rejoin the conference.
	// +optional
	Hold bool `json:"Hold,omitempty"`
	// HoldUrl The URL we call using the `hold_method` for music that plays when the participant is on hold. The URL may return an MP3 file, a WAV file, or a TwiML document that contains `<Play>`, `<Say>`, `<Pause>`, or `<Redirect>` verbs.
	// +optional
	HoldUrl string `json:"HoldUrl,omitempty"`
	// HoldMethod The HTTP method we should use to call `hold_url`. Can be: `GET` or `POST` and the default is `GET`.
	// +optional
	HoldMethod string `json:"HoldMethod,omitempty"`
	// AnnounceUrl The URL we call using the `announce_method` for an announcement to the participant. The URL may return an MP3 file, a WAV file, or a TwiML document that contains `<Play>`, `<Say>`, `<Pause>`, or `<Redirect>` verbs.
	// +optional
	AnnounceUrl string `json:"AnnounceUrl,omitempty"`
	// AnnounceMethod The HTTP method we should use to call `announce_url`. Can be: `GET` or `POST` and defaults to `POST`.
	// +optional
	AnnounceMethod string `json:"AnnounceMethod,omitempty"`
	// BeepOnExit Whether to play a notification beep to the conference when the participant exits. Can be: `true` or `false`.
	// +optional
	BeepOnExit bool `json:"BeepOnExit,omitempty"`
}

// AccountsConferencesParticipantsObservation are the observable fields of a AccountsConferencesParticipants.
//
// These are the properties of what the read (FetchParticipant) answers -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AccountsConferencesParticipantsObservation struct {
	AccountSid             string `json:"account_sid,omitempty"`
	CallSid                string `json:"call_sid,omitempty"`
	Label                  string `json:"label,omitempty"`
	CallSidToCoach         string `json:"call_sid_to_coach,omitempty"`
	Coaching               bool   `json:"coaching,omitempty"`
	ConferenceSid          string `json:"conference_sid,omitempty"`
	DateCreated            string `json:"date_created,omitempty"`
	DateUpdated            string `json:"date_updated,omitempty"`
	EndConferenceOnExit    bool   `json:"end_conference_on_exit,omitempty"`
	Muted                  bool   `json:"muted,omitempty"`
	Hold                   bool   `json:"hold,omitempty"`
	StartConferenceOnEnter bool   `json:"start_conference_on_enter,omitempty"`
	Status                 string `json:"status,omitempty"`
	QueueTime              string `json:"queue_time,omitempty"`
	Uri                    string `json:"uri,omitempty"`
}

// A AccountsConferencesParticipantsSpec defines the desired state of a AccountsConferencesParticipants.
type AccountsConferencesParticipantsSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AccountsConferencesParticipantsParameters `json:"forProvider"`
}

// A AccountsConferencesParticipantsStatus represents the observed state of a AccountsConferencesParticipants.
type AccountsConferencesParticipantsStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AccountsConferencesParticipantsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AccountsConferencesParticipants is a managed Twilio resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twilio}
type AccountsConferencesParticipants struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AccountsConferencesParticipantsSpec   `json:"spec"`
	Status AccountsConferencesParticipantsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountsConferencesParticipantsList contains a list of AccountsConferencesParticipants
type AccountsConferencesParticipantsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountsConferencesParticipants `json:"items"`
}

// AccountsConferencesParticipants type metadata.
var (
	AccountsConferencesParticipantsKind             = reflect.TypeOf(AccountsConferencesParticipants{}).Name()
	AccountsConferencesParticipantsGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountsConferencesParticipantsKind}.String()
	AccountsConferencesParticipantsKindAPIVersion   = AccountsConferencesParticipantsKind + "." + SchemeGroupVersion.String()
	AccountsConferencesParticipantsGroupVersionKind = SchemeGroupVersion.WithKind(AccountsConferencesParticipantsKind)
)

func init() {
	SchemeBuilder.Register(&AccountsConferencesParticipants{}, &AccountsConferencesParticipantsList{})
}
