//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsConferencesParticipants) DeepCopyInto(out *AccountsConferencesParticipants) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsConferencesParticipants.
func (in *AccountsConferencesParticipants) DeepCopy() *AccountsConferencesParticipants {
	if in == nil {
		return nil
	}
	out := new(AccountsConferencesParticipants)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsConferencesParticipants) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsConferencesParticipantsList) DeepCopyInto(out *AccountsConferencesParticipantsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccountsConferencesParticipants, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsConferencesParticipantsList.
func (in *AccountsConferencesParticipantsList) DeepCopy() *AccountsConferencesParticipantsList {
	if in == nil {
		return nil
	}
	out := new(AccountsConferencesParticipantsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsConferencesParticipantsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsConferencesParticipantsObservation) DeepCopyInto(out *AccountsConferencesParticipantsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsConferencesParticipantsObservation.
func (in *AccountsConferencesParticipantsObservation) DeepCopy() *AccountsConferencesParticipantsObservation {
	if in == nil {
		return nil
	}
	out := new(AccountsConferencesParticipantsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsConferencesParticipantsParameters) DeepCopyInto(out *AccountsConferencesParticipantsParameters) {
	*out = *in
	if in.StatusCallbackEvent != nil {
		in, out := &in.StatusCallbackEvent, &out.StatusCallbackEvent
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConferenceStatusCallbackEvent != nil {
		in, out := &in.ConferenceStatusCallbackEvent, &out.ConferenceStatusCallbackEvent
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RecordingStatusCallbackEvent != nil {
		in, out := &in.RecordingStatusCallbackEvent, &out.RecordingStatusCallbackEvent
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConferenceRecordingStatusCallbackEvent != nil {
		in, out := &in.ConferenceRecordingStatusCallbackEvent, &out.ConferenceRecordingStatusCallbackEvent
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsConferencesParticipantsParameters.
func (in *AccountsConferencesParticipantsParameters) DeepCopy() *AccountsConferencesParticipantsParameters {
	if in == nil {
		return nil
	}
	out := new(AccountsConferencesParticipantsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsConferencesParticipantsSpec) DeepCopyInto(out *AccountsConferencesParticipantsSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsConferencesParticipantsSpec.
func (in *AccountsConferencesParticipantsSpec) DeepCopy() *AccountsConferencesParticipantsSpec {
	if in == nil {
		return nil
	}
	out := new(AccountsConferencesParticipantsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsConferencesParticipantsStatus) DeepCopyInto(out *AccountsConferencesParticipantsStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsConferencesParticipantsStatus.
func (in *AccountsConferencesParticipantsStatus) DeepCopy() *AccountsConferencesParticipantsStatus {
	if in == nil {
		return nil
	}
	out := new(AccountsConferencesParticipantsStatus)
	in.DeepCopyInto(out)
	return out
}
