// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Kind{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AccountsMessagesParameters are the configurable fields of a AccountsMessages.
//
// These are the parameters of the create operation (CreateMessage), plus any the
// update accepts and the create does not. The fields are spelled the way
// Twilio TAKES them -- PascalCase -- because that is the name the request
// carries; status.atProvider spells the same values the way Twilio ANSWERS
// them, in snake_case. Nothing translates between the two, so nothing can
// drift out of a translation layer.
type AccountsMessagesParameters struct {
	// To The recipient's phone number in [E.164](https://www.twilio.com/docs/glossary/what-e164) format (for SMS/MMS) or [channel address](https://www.twilio.com/docs/messaging/channels), e.g. `whatsapp:+15552229999`.
	// +kubebuilder:validation:Required
	To string `json:"To"`
	// PathAccountSid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) creating the Message resource.
	// +optional
	PathAccountSid string `json:"PathAccountSid,omitempty"`
	// StatusCallback The URL of the endpoint to which Twilio sends [Message status callback requests](https://www.twilio.com/docs/sms/api/message-resource#twilios-request-to-the-statuscallback-url). URL must contain a valid hostname and underscores are not allowed. If you include this parameter with the `messaging_service_sid`, Twilio uses this URL instead of the Status Callback URL of the [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource).
	// +optional
	StatusCallback string `json:"StatusCallback,omitempty"`
	// ApplicationSid The SID of the associated [TwiML Application](https://www.twilio.com/docs/usage/api/applications). [Message status callback requests](https://www.twilio.com/docs/sms/api/message-resource#twilios-request-to-the-statuscallback-url) are sent to the TwiML App's `message_status_callback` URL. Note that the `status_callback` parameter of a request takes priority over the `application_sid` parameter; if both are included `application_sid` is ignored.
	// +optional
	ApplicationSid string `json:"ApplicationSid,omitempty"`
	// MaxPrice [OBSOLETE] This parameter will no longer have any effect as of 2024-06-03.
	// +optional
	MaxPrice float32 `json:"MaxPrice,omitempty"`
	// ProvideFeedback Boolean indicating whether or not you intend to provide delivery confirmation feedback to Twilio (used in conjunction with the [Message Feedback subresource](https://www.twilio.com/docs/sms/api/message-feedback-resource)). Default value is `false`.
	// +optional
	ProvideFeedback bool `json:"ProvideFeedback,omitempty"`
	// Attempt Total number of attempts made (including this request) to send the message regardless of the provider used
	// +optional
	Attempt int `json:"Attempt,omitempty"`
	// ValidityPeriod The maximum length in seconds that the Message can remain in Twilio's outgoing message queue. If a queued Message exceeds the `validity_period`, the Message is not sent. Accepted values are integers from `1` to `36000`. Default value is `36000`. A `validity_period` greater than `5` is recommended. [Learn more about the validity period](https://www.twilio.com/blog/take-more-control-of-outbound-messages-using-validity-period-html)
	// +optional
	ValidityPeriod int `json:"ValidityPeriod,omitempty"`
	// ForceDelivery Reserved
	// +optional
	ForceDelivery bool `json:"ForceDelivery,omitempty"`
	// ContentRetention
	// +optional
	ContentRetention string `json:"ContentRetention,omitempty"`
	// AddressRetention
	// +optional
	AddressRetention string `json:"AddressRetention,omitempty"`
	// SmartEncoded Whether to detect Unicode characters that have a similar GSM-7 character and replace them. Can be: `true` or `false`.
	// +optional
	SmartEncoded bool `json:"SmartEncoded,omitempty"`
	// PersistentAction Rich actions for non-SMS/MMS channels. Used for [sending location in WhatsApp messages](https://www.twilio.com/docs/whatsapp/message-features#location-messages-with-whatsapp).
	// +optional
	PersistentAction []string `json:"PersistentAction,omitempty"`
	// TrafficType
	// +optional
	TrafficType string `json:"TrafficType,omitempty"`
	// ShortenUrls For Messaging Services with [Link Shortening configured](https://www.twilio.com/docs/messaging/features/link-shortening) only: A Boolean indicating whether or not Twilio should shorten links in the `body` of the Message. Default value is `false`. If `true`, the `messaging_service_sid` parameter must also be provided.
	// +optional
	ShortenUrls bool `json:"ShortenUrls,omitempty"`
	// ScheduleType
	// +optional
	ScheduleType string `json:"ScheduleType,omitempty"`
	// SendAt The time that Twilio will send the message. Must be in ISO 8601 format.
	// +optional
	SendAt string `json:"SendAt,omitempty"`
	// SendAsMms If set to `true`, Twilio delivers the message as a single MMS message, regardless of the presence of media.
	// +optional
	SendAsMms bool `json:"SendAsMms,omitempty"`
	// ContentVariables For [Content Editor/API](https://www.twilio.com/docs/content) only: Key-value pairs of [Template variables](https://www.twilio.com/docs/content/using-variables-with-content-api) and their substitution values. `content_sid` parameter must also be provided. If values are not defined in the `content_variables` parameter, the [Template's default placeholder values](https://www.twilio.com/docs/content/content-api-resources#create-templates) are used.
	// +optional
	ContentVariables string `json:"ContentVariables,omitempty"`
	// MessageIntent Specifies the purpose or use case of the outbound communication. This parameter is used by Twilio's [Traffic Shaping](https://www.twilio.com/docs/messaging/features/traffic-shaping) and [Compliance Toolkit](https://www.twilio.com/docs/messaging/features/compliance-toolkit) products. Possible values include: `otp`, `notifications`, `marketing`, `fraud`, `security`, `customercare`, `delivery`, `education`, `polling`, `announcements`, and `events`.
	// +optional
	MessageIntent string `json:"MessageIntent,omitempty"`
	// RiskCheck
	// +optional
	RiskCheck string `json:"RiskCheck,omitempty"`
	// From The sender's Twilio phone number (in [E.164](https://en.wikipedia.org/wiki/E.164) format), [alphanumeric sender ID](https://www.twilio.com/docs/sms/quickstart), [Wireless SIM](https://www.twilio.com/docs/iot/wireless/programmable-wireless-send-machine-machine-sms-commands), [short code](https://www.twilio.com/en-us/messaging/channels/sms/short-codes), or [channel address](https://www.twilio.com/docs/messaging/channels) (e.g., `whatsapp:+15554449999`). The value of the `from` parameter must be a sender that is hosted within Twilio and belongs to the Account creating the Message. If you are using `messaging_service_sid`, this parameter can be empty (Twilio assigns a `from` value from the Messaging Service's Sender Pool) or you can provide a specific sender from your Sender Pool.
	// +optional
	From string `json:"From,omitempty"`
	// FallbackFrom A fallback SMS sender to use when the recipient cannot be reached over RCS. This parameter may only be used when also providing a [Messaging Service](https://twilio.com/docs/messaging/services) containing an RCS sender. The fallback SMS sender must be either a Twilio phone number (in [E.164](https://en.wikipedia.org/wiki/E.164) format), [alphanumeric sender ID](https://www.twilio.com/docs/sms/quickstart), or [short code](https://www.twilio.com/en-us/messaging/channels/sms/short-codes), hosted within Twilio and belong to the Account creating the Message.
	// +optional
	FallbackFrom string `json:"FallbackFrom,omitempty"`
	// MessagingServiceSid The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/services) you want to associate with the Message. When this parameter is provided and the `from` parameter is omitted, Twilio selects the optimal sender from the Messaging Service's Sender Pool. You may also provide a `from` parameter if you want to use a specific Sender from the Sender Pool.
	// +optional
	MessagingServiceSid string `json:"MessagingServiceSid,omitempty"`
	// Body The text content of the outgoing message. Can be up to 1,600 characters in length. SMS only: If the `body` contains more than 160 [GSM-7](https://www.twilio.com/docs/glossary/what-is-gsm-7-character-encoding) characters (or 70 [UCS-2](https://www.twilio.com/docs/glossary/what-is-ucs-2-character-encoding) characters), the message is segmented and charged accordingly. For long `body` text, consider using the [send_as_mms parameter](https://www.twilio.com/blog/mms-for-long-text-messages).
	// +optional
	Body string `json:"Body,omitempty"`
	// MediaUrl The URL of media to include in the Message content. `jpeg`, `jpg`, `gif`, and `png` file types are fully supported by Twilio and content is formatted for delivery on destination devices. The media size limit is 5 MB for supported file types (`jpeg`, `jpg`, `png`, `gif`) and 500 KB for [other types](https://www.twilio.com/docs/messaging/guides/accepted-mime-types) of accepted media. To send more than one image in the message, provide multiple `media_url` parameters in the POST request. You can include up to ten `media_url` parameters per message. [International](https://support.twilio.com/hc/en-us/articles/223179808-Sending-and-receiving-MMS-messages) and [carrier](https://support.twilio.com/hc/en-us/articles/223133707-Is-MMS-supported-for-all-carriers-in-US-and-Canada-) limits apply.
	// +optional
	MediaUrl []string `json:"MediaUrl,omitempty"`
	// ContentSid For [Content Editor/API](https://www.twilio.com/docs/content) only: The SID of the Content Template to be used with the Message, e.g., `HXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`. If this parameter is not provided, a Content Template is not used. Find the SID in the Console on the Content Editor page. For Content API users, the SID is found in Twilio's response when [creating the Template](https://www.twilio.com/docs/content/content-api-resources#create-templates) or by [fetching your Templates](https://www.twilio.com/docs/content/content-api-resources#fetch-all-content-resources).
	// +optional
	ContentSid string `json:"ContentSid,omitempty"`
	// Status
	// +optional
	Status string `json:"Status,omitempty"`
}

// AccountsMessagesObservation are the observable fields of a AccountsMessages.
//
// These are the properties of what the read (FetchMessage) answers -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AccountsMessagesObservation struct {
	Body                string `json:"body,omitempty"`
	NumSegments         string `json:"num_segments,omitempty"`
	Direction           string `json:"direction,omitempty"`
	From                string `json:"from,omitempty"`
	To                  string `json:"to,omitempty"`
	DateUpdated         string `json:"date_updated,omitempty"`
	Price               string `json:"price,omitempty"`
	ErrorMessage        string `json:"error_message,omitempty"`
	Uri                 string `json:"uri,omitempty"`
	AccountSid          string `json:"account_sid,omitempty"`
	NumMedia            string `json:"num_media,omitempty"`
	Status              string `json:"status,omitempty"`
	MessagingServiceSid string `json:"messaging_service_sid,omitempty"`
	Sid                 string `json:"sid,omitempty"`
	DateSent            string `json:"date_sent,omitempty"`
	DateCreated         string `json:"date_created,omitempty"`
	ErrorCode           int64  `json:"error_code,omitempty"`
	PriceUnit           string `json:"price_unit,omitempty"`
	ApiVersion          string `json:"api_version,omitempty"`
	SubresourceUris     string `json:"subresource_uris,omitempty"`
}

// A AccountsMessagesSpec defines the desired state of a AccountsMessages.
type AccountsMessagesSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AccountsMessagesParameters `json:"forProvider"`
}

// A AccountsMessagesStatus represents the observed state of a AccountsMessages.
type AccountsMessagesStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AccountsMessagesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AccountsMessages is a managed Twilio resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twilio}
type AccountsMessages struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AccountsMessagesSpec   `json:"spec"`
	Status AccountsMessagesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountsMessagesList contains a list of AccountsMessages
type AccountsMessagesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountsMessages `json:"items"`
}

// AccountsMessages type metadata.
var (
	AccountsMessagesKind             = reflect.TypeOf(AccountsMessages{}).Name()
	AccountsMessagesGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountsMessagesKind}.String()
	AccountsMessagesKindAPIVersion   = AccountsMessagesKind + "." + SchemeGroupVersion.String()
	AccountsMessagesGroupVersionKind = SchemeGroupVersion.WithKind(AccountsMessagesKind)
)

func init() {
	SchemeBuilder.Register(&AccountsMessages{}, &AccountsMessagesList{})
}
