//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsMessages) DeepCopyInto(out *AccountsMessages) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsMessages.
func (in *AccountsMessages) DeepCopy() *AccountsMessages {
	if in == nil {
		return nil
	}
	out := new(AccountsMessages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsMessages) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsMessagesList) DeepCopyInto(out *AccountsMessagesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccountsMessages, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsMessagesList.
func (in *AccountsMessagesList) DeepCopy() *AccountsMessagesList {
	if in == nil {
		return nil
	}
	out := new(AccountsMessagesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsMessagesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsMessagesObservation) DeepCopyInto(out *AccountsMessagesObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsMessagesObservation.
func (in *AccountsMessagesObservation) DeepCopy() *AccountsMessagesObservation {
	if in == nil {
		return nil
	}
	out := new(AccountsMessagesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsMessagesParameters) DeepCopyInto(out *AccountsMessagesParameters) {
	*out = *in
	if in.PersistentAction != nil {
		in, out := &in.PersistentAction, &out.PersistentAction
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MediaUrl != nil {
		in, out := &in.MediaUrl, &out.MediaUrl
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsMessagesParameters.
func (in *AccountsMessagesParameters) DeepCopy() *AccountsMessagesParameters {
	if in == nil {
		return nil
	}
	out := new(AccountsMessagesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsMessagesSpec) DeepCopyInto(out *AccountsMessagesSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsMessagesSpec.
func (in *AccountsMessagesSpec) DeepCopy() *AccountsMessagesSpec {
	if in == nil {
		return nil
	}
	out := new(AccountsMessagesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsMessagesStatus) DeepCopyInto(out *AccountsMessagesStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsMessagesStatus.
func (in *AccountsMessagesStatus) DeepCopy() *AccountsMessagesStatus {
	if in == nil {
		return nil
	}
	out := new(AccountsMessagesStatus)
	in.DeepCopyInto(out)
	return out
}
