// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Kind{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AccountsSIPDomainsAuthCallsCredentialListMappingsParameters are the configurable fields of a AccountsSIPDomainsAuthCallsCredentialListMappings.
//
// These are the parameters of the create operation (CreateSipAuthCallsCredentialListMapping), plus any the
// update accepts and the create does not. The fields are spelled the way
// Twilio TAKES them -- PascalCase -- because that is the name the request
// carries; status.atProvider spells the same values the way Twilio ANSWERS
// them, in snake_case. Nothing translates between the two, so nothing can
// drift out of a translation layer.
type AccountsSIPDomainsAuthCallsCredentialListMappingsParameters struct {
	// DomainSid The SID of the SIP domain that will contain the new resource.
	// +kubebuilder:validation:Required
	DomainSid string `json:"DomainSid"`
	// CredentialListSid The SID of the CredentialList resource to map to the SIP domain.
	// +kubebuilder:validation:Required
	CredentialListSid string `json:"CredentialListSid"`
	// PathAccountSid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that will create the resource.
	// +optional
	PathAccountSid string `json:"PathAccountSid,omitempty"`
}

// AccountsSIPDomainsAuthCallsCredentialListMappingsObservation are the observable fields of a AccountsSIPDomainsAuthCallsCredentialListMappings.
//
// These are the properties of what the read (FetchSipAuthCallsCredentialListMapping) answers -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AccountsSIPDomainsAuthCallsCredentialListMappingsObservation struct {
	AccountSid   string `json:"account_sid,omitempty"`
	DateCreated  string `json:"date_created,omitempty"`
	DateUpdated  string `json:"date_updated,omitempty"`
	FriendlyName string `json:"friendly_name,omitempty"`
	Sid          string `json:"sid,omitempty"`
}

// A AccountsSIPDomainsAuthCallsCredentialListMappingsSpec defines the desired state of a AccountsSIPDomainsAuthCallsCredentialListMappings.
type AccountsSIPDomainsAuthCallsCredentialListMappingsSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AccountsSIPDomainsAuthCallsCredentialListMappingsParameters `json:"forProvider"`
}

// A AccountsSIPDomainsAuthCallsCredentialListMappingsStatus represents the observed state of a AccountsSIPDomainsAuthCallsCredentialListMappings.
type AccountsSIPDomainsAuthCallsCredentialListMappingsStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AccountsSIPDomainsAuthCallsCredentialListMappingsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AccountsSIPDomainsAuthCallsCredentialListMappings is a managed Twilio resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twilio}
type AccountsSIPDomainsAuthCallsCredentialListMappings struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AccountsSIPDomainsAuthCallsCredentialListMappingsSpec   `json:"spec"`
	Status AccountsSIPDomainsAuthCallsCredentialListMappingsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountsSIPDomainsAuthCallsCredentialListMappingsList contains a list of AccountsSIPDomainsAuthCallsCredentialListMappings
type AccountsSIPDomainsAuthCallsCredentialListMappingsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountsSIPDomainsAuthCallsCredentialListMappings `json:"items"`
}

// AccountsSIPDomainsAuthCallsCredentialListMappings type metadata.
var (
	AccountsSIPDomainsAuthCallsCredentialListMappingsKind             = reflect.TypeOf(AccountsSIPDomainsAuthCallsCredentialListMappings{}).Name()
	AccountsSIPDomainsAuthCallsCredentialListMappingsGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountsSIPDomainsAuthCallsCredentialListMappingsKind}.String()
	AccountsSIPDomainsAuthCallsCredentialListMappingsKindAPIVersion   = AccountsSIPDomainsAuthCallsCredentialListMappingsKind + "." + SchemeGroupVersion.String()
	AccountsSIPDomainsAuthCallsCredentialListMappingsGroupVersionKind = SchemeGroupVersion.WithKind(AccountsSIPDomainsAuthCallsCredentialListMappingsKind)
)

func init() {
	SchemeBuilder.Register(&AccountsSIPDomainsAuthCallsCredentialListMappings{}, &AccountsSIPDomainsAuthCallsCredentialListMappingsList{})
}
