//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsAuthCallsCredentialListMappings) DeepCopyInto(out *AccountsSIPDomainsAuthCallsCredentialListMappings) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsAuthCallsCredentialListMappings.
func (in *AccountsSIPDomainsAuthCallsCredentialListMappings) DeepCopy() *AccountsSIPDomainsAuthCallsCredentialListMappings {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsAuthCallsCredentialListMappings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsSIPDomainsAuthCallsCredentialListMappings) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsAuthCallsCredentialListMappingsList) DeepCopyInto(out *AccountsSIPDomainsAuthCallsCredentialListMappingsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccountsSIPDomainsAuthCallsCredentialListMappings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsAuthCallsCredentialListMappingsList.
func (in *AccountsSIPDomainsAuthCallsCredentialListMappingsList) DeepCopy() *AccountsSIPDomainsAuthCallsCredentialListMappingsList {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsAuthCallsCredentialListMappingsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsSIPDomainsAuthCallsCredentialListMappingsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsAuthCallsCredentialListMappingsObservation) DeepCopyInto(out *AccountsSIPDomainsAuthCallsCredentialListMappingsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsAuthCallsCredentialListMappingsObservation.
func (in *AccountsSIPDomainsAuthCallsCredentialListMappingsObservation) DeepCopy() *AccountsSIPDomainsAuthCallsCredentialListMappingsObservation {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsAuthCallsCredentialListMappingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsAuthCallsCredentialListMappingsParameters) DeepCopyInto(out *AccountsSIPDomainsAuthCallsCredentialListMappingsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsAuthCallsCredentialListMappingsParameters.
func (in *AccountsSIPDomainsAuthCallsCredentialListMappingsParameters) DeepCopy() *AccountsSIPDomainsAuthCallsCredentialListMappingsParameters {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsAuthCallsCredentialListMappingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsAuthCallsCredentialListMappingsSpec) DeepCopyInto(out *AccountsSIPDomainsAuthCallsCredentialListMappingsSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsAuthCallsCredentialListMappingsSpec.
func (in *AccountsSIPDomainsAuthCallsCredentialListMappingsSpec) DeepCopy() *AccountsSIPDomainsAuthCallsCredentialListMappingsSpec {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsAuthCallsCredentialListMappingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsAuthCallsCredentialListMappingsStatus) DeepCopyInto(out *AccountsSIPDomainsAuthCallsCredentialListMappingsStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsAuthCallsCredentialListMappingsStatus.
func (in *AccountsSIPDomainsAuthCallsCredentialListMappingsStatus) DeepCopy() *AccountsSIPDomainsAuthCallsCredentialListMappingsStatus {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsAuthCallsCredentialListMappingsStatus)
	in.DeepCopyInto(out)
	return out
}
