//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPCredentialLists) DeepCopyInto(out *AccountsSIPCredentialLists) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPCredentialLists.
func (in *AccountsSIPCredentialLists) DeepCopy() *AccountsSIPCredentialLists {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPCredentialLists)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsSIPCredentialLists) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPCredentialListsList) DeepCopyInto(out *AccountsSIPCredentialListsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccountsSIPCredentialLists, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPCredentialListsList.
func (in *AccountsSIPCredentialListsList) DeepCopy() *AccountsSIPCredentialListsList {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPCredentialListsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsSIPCredentialListsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPCredentialListsObservation) DeepCopyInto(out *AccountsSIPCredentialListsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPCredentialListsObservation.
func (in *AccountsSIPCredentialListsObservation) DeepCopy() *AccountsSIPCredentialListsObservation {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPCredentialListsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPCredentialListsParameters) DeepCopyInto(out *AccountsSIPCredentialListsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPCredentialListsParameters.
func (in *AccountsSIPCredentialListsParameters) DeepCopy() *AccountsSIPCredentialListsParameters {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPCredentialListsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPCredentialListsSpec) DeepCopyInto(out *AccountsSIPCredentialListsSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPCredentialListsSpec.
func (in *AccountsSIPCredentialListsSpec) DeepCopy() *AccountsSIPCredentialListsSpec {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPCredentialListsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPCredentialListsStatus) DeepCopyInto(out *AccountsSIPCredentialListsStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPCredentialListsStatus.
func (in *AccountsSIPCredentialListsStatus) DeepCopy() *AccountsSIPCredentialListsStatus {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPCredentialListsStatus)
	in.DeepCopyInto(out)
	return out
}
