// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Kind{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AccountsSIPIpAccessControlListsParameters are the configurable fields of a AccountsSIPIpAccessControlLists.
//
// These are the parameters of the create operation (CreateSipIpAccessControlList), plus any the
// update accepts and the create does not. The fields are spelled the way
// Twilio TAKES them -- PascalCase -- because that is the name the request
// carries; status.atProvider spells the same values the way Twilio ANSWERS
// them, in snake_case. Nothing translates between the two, so nothing can
// drift out of a translation layer.
type AccountsSIPIpAccessControlListsParameters struct {
	// FriendlyName A human readable descriptive text that describes the IpAccessControlList, up to 255 characters long.
	// +kubebuilder:validation:Required
	FriendlyName string `json:"FriendlyName"`
	// PathAccountSid The unique id of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this resource.
	// +optional
	PathAccountSid string `json:"PathAccountSid,omitempty"`
}

// AccountsSIPIpAccessControlListsObservation are the observable fields of a AccountsSIPIpAccessControlLists.
//
// These are the properties of what the read (FetchSipIpAccessControlList) answers -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AccountsSIPIpAccessControlListsObservation struct {
	Sid             string `json:"sid,omitempty"`
	AccountSid      string `json:"account_sid,omitempty"`
	FriendlyName    string `json:"friendly_name,omitempty"`
	DateCreated     string `json:"date_created,omitempty"`
	DateUpdated     string `json:"date_updated,omitempty"`
	SubresourceUris string `json:"subresource_uris,omitempty"`
	Uri             string `json:"uri,omitempty"`
}

// A AccountsSIPIpAccessControlListsSpec defines the desired state of a AccountsSIPIpAccessControlLists.
type AccountsSIPIpAccessControlListsSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AccountsSIPIpAccessControlListsParameters `json:"forProvider"`
}

// A AccountsSIPIpAccessControlListsStatus represents the observed state of a AccountsSIPIpAccessControlLists.
type AccountsSIPIpAccessControlListsStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AccountsSIPIpAccessControlListsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AccountsSIPIpAccessControlLists is a managed Twilio resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twilio}
type AccountsSIPIpAccessControlLists struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AccountsSIPIpAccessControlListsSpec   `json:"spec"`
	Status AccountsSIPIpAccessControlListsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountsSIPIpAccessControlListsList contains a list of AccountsSIPIpAccessControlLists
type AccountsSIPIpAccessControlListsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountsSIPIpAccessControlLists `json:"items"`
}

// AccountsSIPIpAccessControlLists type metadata.
var (
	AccountsSIPIpAccessControlListsKind             = reflect.TypeOf(AccountsSIPIpAccessControlLists{}).Name()
	AccountsSIPIpAccessControlListsGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountsSIPIpAccessControlListsKind}.String()
	AccountsSIPIpAccessControlListsKindAPIVersion   = AccountsSIPIpAccessControlListsKind + "." + SchemeGroupVersion.String()
	AccountsSIPIpAccessControlListsGroupVersionKind = SchemeGroupVersion.WithKind(AccountsSIPIpAccessControlListsKind)
)

func init() {
	SchemeBuilder.Register(&AccountsSIPIpAccessControlLists{}, &AccountsSIPIpAccessControlListsList{})
}
