//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPIpAccessControlLists) DeepCopyInto(out *AccountsSIPIpAccessControlLists) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPIpAccessControlLists.
func (in *AccountsSIPIpAccessControlLists) DeepCopy() *AccountsSIPIpAccessControlLists {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPIpAccessControlLists)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsSIPIpAccessControlLists) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPIpAccessControlListsList) DeepCopyInto(out *AccountsSIPIpAccessControlListsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccountsSIPIpAccessControlLists, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPIpAccessControlListsList.
func (in *AccountsSIPIpAccessControlListsList) DeepCopy() *AccountsSIPIpAccessControlListsList {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPIpAccessControlListsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsSIPIpAccessControlListsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPIpAccessControlListsObservation) DeepCopyInto(out *AccountsSIPIpAccessControlListsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPIpAccessControlListsObservation.
func (in *AccountsSIPIpAccessControlListsObservation) DeepCopy() *AccountsSIPIpAccessControlListsObservation {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPIpAccessControlListsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPIpAccessControlListsParameters) DeepCopyInto(out *AccountsSIPIpAccessControlListsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPIpAccessControlListsParameters.
func (in *AccountsSIPIpAccessControlListsParameters) DeepCopy() *AccountsSIPIpAccessControlListsParameters {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPIpAccessControlListsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPIpAccessControlListsSpec) DeepCopyInto(out *AccountsSIPIpAccessControlListsSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPIpAccessControlListsSpec.
func (in *AccountsSIPIpAccessControlListsSpec) DeepCopy() *AccountsSIPIpAccessControlListsSpec {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPIpAccessControlListsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPIpAccessControlListsStatus) DeepCopyInto(out *AccountsSIPIpAccessControlListsStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPIpAccessControlListsStatus.
func (in *AccountsSIPIpAccessControlListsStatus) DeepCopy() *AccountsSIPIpAccessControlListsStatus {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPIpAccessControlListsStatus)
	in.DeepCopyInto(out)
	return out
}
