// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package controller

import (
	"github.com/crossplane/crossplane-runtime/v2/pkg/controller"
	ctrl "sigs.k8s.io/controller-runtime"

	"github.com/n-at-han-k/crossplane-provider-twilio/internal/controller/config"

	"github.com/n-at-han-k/crossplane-provider-twilio/internal/controller/accounts_addresses"

	"github.com/n-at-han-k/crossplane-provider-twilio/internal/controller/accounts_applications"

	"github.com/n-at-han-k/crossplane-provider-twilio/internal/controller/accounts_calls"

	"github.com/n-at-han-k/crossplane-provider-twilio/internal/controller/accounts_calls_recordings"

	"github.com/n-at-han-k/crossplane-provider-twilio/internal/controller/accounts_conferences_participants"

	"github.com/n-at-han-k/crossplane-provider-twilio/internal/controller/accounts_incoming_phone_numbers"

	"github.com/n-at-han-k/crossplane-provider-twilio/internal/controller/accounts_incoming_phone_numbers_assigned_add_ons"

	"github.com/n-at-han-k/crossplane-provider-twilio/internal/controller/accounts_keys"

	"github.com/n-at-han-k/crossplane-provider-twilio/internal/controller/accounts_messages"

	"github.com/n-at-han-k/crossplane-provider-twilio/internal/controller/accounts_queues"

	"github.com/n-at-han-k/crossplane-provider-twilio/internal/controller/accounts_sip_credential_lists"

	"github.com/n-at-han-k/crossplane-provider-twilio/internal/controller/accounts_sip_credential_lists_credentials"

	"github.com/n-at-han-k/crossplane-provider-twilio/internal/controller/accounts_sip_domains"

	"github.com/n-at-han-k/crossplane-provider-twilio/internal/controller/accounts_sip_domains_auth_calls_credential_list_mappings"

	"github.com/n-at-han-k/crossplane-provider-twilio/internal/controller/accounts_sip_domains_auth_calls_ip_access_control_list_mappings"

	"github.com/n-at-han-k/crossplane-provider-twilio/internal/controller/accounts_sip_domains_auth_registrations_credential_list_mappings"

	"github.com/n-at-han-k/crossplane-provider-twilio/internal/controller/accounts_sip_domains_credential_list_mappings"

	"github.com/n-at-han-k/crossplane-provider-twilio/internal/controller/accounts_sip_domains_ip_access_control_list_mappings"

	"github.com/n-at-han-k/crossplane-provider-twilio/internal/controller/accounts_sip_ip_access_control_lists"

	"github.com/n-at-han-k/crossplane-provider-twilio/internal/controller/accounts_sip_ip_access_control_lists_ip_addresses"

	"github.com/n-at-han-k/crossplane-provider-twilio/internal/controller/accounts_signing_keys"

	"github.com/n-at-han-k/crossplane-provider-twilio/internal/controller/accounts_usage_triggers"
)

// SetupGated creates all Twilio controllers with safe-start support and adds
// them to the supplied manager.
func SetupGated(mgr ctrl.Manager, o controller.Options) error {
	for _, setup := range []func(ctrl.Manager, controller.Options) error{
		config.Setup,

		accounts_addresses.SetupGated,

		accounts_applications.SetupGated,

		accounts_calls.SetupGated,

		accounts_calls_recordings.SetupGated,

		accounts_conferences_participants.SetupGated,

		accounts_incoming_phone_numbers.SetupGated,

		accounts_incoming_phone_numbers_assigned_add_ons.SetupGated,

		accounts_keys.SetupGated,

		accounts_messages.SetupGated,

		accounts_queues.SetupGated,

		accounts_sip_credential_lists.SetupGated,

		accounts_sip_credential_lists_credentials.SetupGated,

		accounts_sip_domains.SetupGated,

		accounts_sip_domains_auth_calls_credential_list_mappings.SetupGated,

		accounts_sip_domains_auth_calls_ip_access_control_list_mappings.SetupGated,

		accounts_sip_domains_auth_registrations_credential_list_mappings.SetupGated,

		accounts_sip_domains_credential_list_mappings.SetupGated,

		accounts_sip_domains_ip_access_control_list_mappings.SetupGated,

		accounts_sip_ip_access_control_lists.SetupGated,

		accounts_sip_ip_access_control_lists_ip_addresses.SetupGated,

		accounts_signing_keys.SetupGated,

		accounts_usage_triggers.SetupGated,
	} {
		if err := setup(mgr, o); err != nil {
			return err
		}
	}
	return nil
}
