// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Kind{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AccountsAddressesParameters are the configurable fields of a AccountsAddresses.
//
// These are the parameters of the create operation (CreateAddress), plus any the
// update accepts and the create does not. The fields are spelled the way
// Twilio TAKES them -- PascalCase -- because that is the name the request
// carries; status.atProvider spells the same values the way Twilio ANSWERS
// them, in snake_case. Nothing translates between the two, so nothing can
// drift out of a translation layer.
type AccountsAddressesParameters struct {
	// CustomerName The name to associate with the new address.
	// +kubebuilder:validation:Required
	CustomerName string `json:"CustomerName"`
	// Street The number and street address of the new address.
	// +kubebuilder:validation:Required
	Street string `json:"Street"`
	// City The city of the new address.
	// +kubebuilder:validation:Required
	City string `json:"City"`
	// Region The state or region of the new address.
	// +kubebuilder:validation:Required
	Region string `json:"Region"`
	// PostalCode The postal code of the new address.
	// +kubebuilder:validation:Required
	PostalCode string `json:"PostalCode"`
	// IsoCountry The ISO country code of the new address.
	// +kubebuilder:validation:Required
	IsoCountry string `json:"IsoCountry"`
	// PathAccountSid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that will be responsible for the new Address resource.
	// +optional
	PathAccountSid string `json:"PathAccountSid,omitempty"`
	// FriendlyName A descriptive string that you create to describe the new address. It can be up to 64 characters long for Regulatory Compliance addresses and 32 characters long for Emergency addresses.
	// +optional
	FriendlyName string `json:"FriendlyName,omitempty"`
	// EmergencyEnabled Whether to enable emergency calling on the new address. Can be: `true` or `false`.
	// +optional
	EmergencyEnabled bool `json:"EmergencyEnabled,omitempty"`
	// AutoCorrectAddress Whether we should automatically correct the address. Can be: `true` or `false` and the default is `true`. If empty or `true`, we will correct the address you provide if necessary. If `false`, we won't alter the address you provide.
	// +optional
	AutoCorrectAddress bool `json:"AutoCorrectAddress,omitempty"`
	// StreetSecondary The additional number and street address of the address.
	// +optional
	StreetSecondary string `json:"StreetSecondary,omitempty"`
}

// AccountsAddressesObservation are the observable fields of a AccountsAddresses.
//
// These are the properties of what the read (FetchAddress) answers -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AccountsAddressesObservation struct {
	AccountSid       string `json:"account_sid,omitempty"`
	City             string `json:"city,omitempty"`
	CustomerName     string `json:"customer_name,omitempty"`
	DateCreated      string `json:"date_created,omitempty"`
	DateUpdated      string `json:"date_updated,omitempty"`
	FriendlyName     string `json:"friendly_name,omitempty"`
	IsoCountry       string `json:"iso_country,omitempty"`
	PostalCode       string `json:"postal_code,omitempty"`
	Region           string `json:"region,omitempty"`
	Sid              string `json:"sid,omitempty"`
	Street           string `json:"street,omitempty"`
	Uri              string `json:"uri,omitempty"`
	EmergencyEnabled bool   `json:"emergency_enabled,omitempty"`
	Validated        bool   `json:"validated,omitempty"`
	Verified         bool   `json:"verified,omitempty"`
	StreetSecondary  string `json:"street_secondary,omitempty"`
}

// A AccountsAddressesSpec defines the desired state of a AccountsAddresses.
type AccountsAddressesSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AccountsAddressesParameters `json:"forProvider"`
}

// A AccountsAddressesStatus represents the observed state of a AccountsAddresses.
type AccountsAddressesStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AccountsAddressesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AccountsAddresses is a managed Twilio resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twilio}
type AccountsAddresses struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AccountsAddressesSpec   `json:"spec"`
	Status AccountsAddressesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountsAddressesList contains a list of AccountsAddresses
type AccountsAddressesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountsAddresses `json:"items"`
}

// AccountsAddresses type metadata.
var (
	AccountsAddressesKind             = reflect.TypeOf(AccountsAddresses{}).Name()
	AccountsAddressesGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountsAddressesKind}.String()
	AccountsAddressesKindAPIVersion   = AccountsAddressesKind + "." + SchemeGroupVersion.String()
	AccountsAddressesGroupVersionKind = SchemeGroupVersion.WithKind(AccountsAddressesKind)
)

func init() {
	SchemeBuilder.Register(&AccountsAddresses{}, &AccountsAddressesList{})
}
