// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Kind{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AccountsSIPDomainsAuthCallsIpAccessControlListMappingsParameters are the configurable fields of a AccountsSIPDomainsAuthCallsIpAccessControlListMappings.
//
// These are the parameters of the create operation (CreateSipAuthCallsIpAccessControlListMapping), plus any the
// update accepts and the create does not. The fields are spelled the way
// Twilio TAKES them -- PascalCase -- because that is the name the request
// carries; status.atProvider spells the same values the way Twilio ANSWERS
// them, in snake_case. Nothing translates between the two, so nothing can
// drift out of a translation layer.
type AccountsSIPDomainsAuthCallsIpAccessControlListMappingsParameters struct {
	// DomainSid The SID of the SIP domain that will contain the new resource.
	// +kubebuilder:validation:Required
	DomainSid string `json:"DomainSid"`
	// IpAccessControlListSid The SID of the IpAccessControlList resource to map to the SIP domain.
	// +kubebuilder:validation:Required
	IpAccessControlListSid string `json:"IpAccessControlListSid"`
	// PathAccountSid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that will create the resource.
	// +optional
	PathAccountSid string `json:"PathAccountSid,omitempty"`
}

// AccountsSIPDomainsAuthCallsIpAccessControlListMappingsObservation are the observable fields of a AccountsSIPDomainsAuthCallsIpAccessControlListMappings.
//
// These are the properties of what the read (FetchSipAuthCallsIpAccessControlListMapping) answers -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AccountsSIPDomainsAuthCallsIpAccessControlListMappingsObservation struct {
	AccountSid   string `json:"account_sid,omitempty"`
	DateCreated  string `json:"date_created,omitempty"`
	DateUpdated  string `json:"date_updated,omitempty"`
	FriendlyName string `json:"friendly_name,omitempty"`
	Sid          string `json:"sid,omitempty"`
}

// A AccountsSIPDomainsAuthCallsIpAccessControlListMappingsSpec defines the desired state of a AccountsSIPDomainsAuthCallsIpAccessControlListMappings.
type AccountsSIPDomainsAuthCallsIpAccessControlListMappingsSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AccountsSIPDomainsAuthCallsIpAccessControlListMappingsParameters `json:"forProvider"`
}

// A AccountsSIPDomainsAuthCallsIpAccessControlListMappingsStatus represents the observed state of a AccountsSIPDomainsAuthCallsIpAccessControlListMappings.
type AccountsSIPDomainsAuthCallsIpAccessControlListMappingsStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AccountsSIPDomainsAuthCallsIpAccessControlListMappingsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AccountsSIPDomainsAuthCallsIpAccessControlListMappings is a managed Twilio resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twilio}
type AccountsSIPDomainsAuthCallsIpAccessControlListMappings struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AccountsSIPDomainsAuthCallsIpAccessControlListMappingsSpec   `json:"spec"`
	Status AccountsSIPDomainsAuthCallsIpAccessControlListMappingsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountsSIPDomainsAuthCallsIpAccessControlListMappingsList contains a list of AccountsSIPDomainsAuthCallsIpAccessControlListMappings
type AccountsSIPDomainsAuthCallsIpAccessControlListMappingsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountsSIPDomainsAuthCallsIpAccessControlListMappings `json:"items"`
}

// AccountsSIPDomainsAuthCallsIpAccessControlListMappings type metadata.
var (
	AccountsSIPDomainsAuthCallsIpAccessControlListMappingsKind             = reflect.TypeOf(AccountsSIPDomainsAuthCallsIpAccessControlListMappings{}).Name()
	AccountsSIPDomainsAuthCallsIpAccessControlListMappingsGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountsSIPDomainsAuthCallsIpAccessControlListMappingsKind}.String()
	AccountsSIPDomainsAuthCallsIpAccessControlListMappingsKindAPIVersion   = AccountsSIPDomainsAuthCallsIpAccessControlListMappingsKind + "." + SchemeGroupVersion.String()
	AccountsSIPDomainsAuthCallsIpAccessControlListMappingsGroupVersionKind = SchemeGroupVersion.WithKind(AccountsSIPDomainsAuthCallsIpAccessControlListMappingsKind)
)

func init() {
	SchemeBuilder.Register(&AccountsSIPDomainsAuthCallsIpAccessControlListMappings{}, &AccountsSIPDomainsAuthCallsIpAccessControlListMappingsList{})
}
