//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsAuthCallsIpAccessControlListMappings) DeepCopyInto(out *AccountsSIPDomainsAuthCallsIpAccessControlListMappings) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsAuthCallsIpAccessControlListMappings.
func (in *AccountsSIPDomainsAuthCallsIpAccessControlListMappings) DeepCopy() *AccountsSIPDomainsAuthCallsIpAccessControlListMappings {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsAuthCallsIpAccessControlListMappings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsSIPDomainsAuthCallsIpAccessControlListMappings) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsAuthCallsIpAccessControlListMappingsList) DeepCopyInto(out *AccountsSIPDomainsAuthCallsIpAccessControlListMappingsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccountsSIPDomainsAuthCallsIpAccessControlListMappings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsAuthCallsIpAccessControlListMappingsList.
func (in *AccountsSIPDomainsAuthCallsIpAccessControlListMappingsList) DeepCopy() *AccountsSIPDomainsAuthCallsIpAccessControlListMappingsList {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsAuthCallsIpAccessControlListMappingsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsSIPDomainsAuthCallsIpAccessControlListMappingsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsAuthCallsIpAccessControlListMappingsObservation) DeepCopyInto(out *AccountsSIPDomainsAuthCallsIpAccessControlListMappingsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsAuthCallsIpAccessControlListMappingsObservation.
func (in *AccountsSIPDomainsAuthCallsIpAccessControlListMappingsObservation) DeepCopy() *AccountsSIPDomainsAuthCallsIpAccessControlListMappingsObservation {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsAuthCallsIpAccessControlListMappingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsAuthCallsIpAccessControlListMappingsParameters) DeepCopyInto(out *AccountsSIPDomainsAuthCallsIpAccessControlListMappingsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsAuthCallsIpAccessControlListMappingsParameters.
func (in *AccountsSIPDomainsAuthCallsIpAccessControlListMappingsParameters) DeepCopy() *AccountsSIPDomainsAuthCallsIpAccessControlListMappingsParameters {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsAuthCallsIpAccessControlListMappingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsAuthCallsIpAccessControlListMappingsSpec) DeepCopyInto(out *AccountsSIPDomainsAuthCallsIpAccessControlListMappingsSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsAuthCallsIpAccessControlListMappingsSpec.
func (in *AccountsSIPDomainsAuthCallsIpAccessControlListMappingsSpec) DeepCopy() *AccountsSIPDomainsAuthCallsIpAccessControlListMappingsSpec {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsAuthCallsIpAccessControlListMappingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsAuthCallsIpAccessControlListMappingsStatus) DeepCopyInto(out *AccountsSIPDomainsAuthCallsIpAccessControlListMappingsStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsAuthCallsIpAccessControlListMappingsStatus.
func (in *AccountsSIPDomainsAuthCallsIpAccessControlListMappingsStatus) DeepCopy() *AccountsSIPDomainsAuthCallsIpAccessControlListMappingsStatus {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsAuthCallsIpAccessControlListMappingsStatus)
	in.DeepCopyInto(out)
	return out
}
