// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Kind{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AccountsSIPIpAccessControlListsIpAddressesParameters are the configurable fields of a AccountsSIPIpAccessControlListsIpAddresses.
//
// These are the parameters of the create operation (CreateSipIpAddress), plus any the
// update accepts and the create does not. The fields are spelled the way
// Twilio TAKES them -- PascalCase -- because that is the name the request
// carries; status.atProvider spells the same values the way Twilio ANSWERS
// them, in snake_case. Nothing translates between the two, so nothing can
// drift out of a translation layer.
type AccountsSIPIpAccessControlListsIpAddressesParameters struct {
	// IpAccessControlListSid The IpAccessControlList Sid with which to associate the created IpAddress resource.
	// +kubebuilder:validation:Required
	IpAccessControlListSid string `json:"IpAccessControlListSid"`
	// FriendlyName A human readable descriptive text for this resource, up to 255 characters long.
	// +kubebuilder:validation:Required
	FriendlyName string `json:"FriendlyName"`
	// IpAddress An IP address in dotted decimal notation from which you want to accept traffic. Any SIP requests from this IP address will be allowed by Twilio. IPv4 only supported today.
	// +kubebuilder:validation:Required
	IpAddress string `json:"IpAddress"`
	// PathAccountSid The unique id of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this resource.
	// +optional
	PathAccountSid string `json:"PathAccountSid,omitempty"`
	// CidrPrefixLength An integer representing the length of the CIDR prefix to use with this IP address when accepting traffic. By default the entire IP address is used.
	// +optional
	CidrPrefixLength int `json:"CidrPrefixLength,omitempty"`
}

// AccountsSIPIpAccessControlListsIpAddressesObservation are the observable fields of a AccountsSIPIpAccessControlListsIpAddresses.
//
// These are the properties of what the read (FetchSipIpAddress) answers -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AccountsSIPIpAccessControlListsIpAddressesObservation struct {
	Sid                    string `json:"sid,omitempty"`
	AccountSid             string `json:"account_sid,omitempty"`
	FriendlyName           string `json:"friendly_name,omitempty"`
	IpAddress              string `json:"ip_address,omitempty"`
	CidrPrefixLength       int64  `json:"cidr_prefix_length,omitempty"`
	IpAccessControlListSid string `json:"ip_access_control_list_sid,omitempty"`
	DateCreated            string `json:"date_created,omitempty"`
	DateUpdated            string `json:"date_updated,omitempty"`
	Uri                    string `json:"uri,omitempty"`
}

// A AccountsSIPIpAccessControlListsIpAddressesSpec defines the desired state of a AccountsSIPIpAccessControlListsIpAddresses.
type AccountsSIPIpAccessControlListsIpAddressesSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AccountsSIPIpAccessControlListsIpAddressesParameters `json:"forProvider"`
}

// A AccountsSIPIpAccessControlListsIpAddressesStatus represents the observed state of a AccountsSIPIpAccessControlListsIpAddresses.
type AccountsSIPIpAccessControlListsIpAddressesStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AccountsSIPIpAccessControlListsIpAddressesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AccountsSIPIpAccessControlListsIpAddresses is a managed Twilio resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twilio}
type AccountsSIPIpAccessControlListsIpAddresses struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AccountsSIPIpAccessControlListsIpAddressesSpec   `json:"spec"`
	Status AccountsSIPIpAccessControlListsIpAddressesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountsSIPIpAccessControlListsIpAddressesList contains a list of AccountsSIPIpAccessControlListsIpAddresses
type AccountsSIPIpAccessControlListsIpAddressesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountsSIPIpAccessControlListsIpAddresses `json:"items"`
}

// AccountsSIPIpAccessControlListsIpAddresses type metadata.
var (
	AccountsSIPIpAccessControlListsIpAddressesKind             = reflect.TypeOf(AccountsSIPIpAccessControlListsIpAddresses{}).Name()
	AccountsSIPIpAccessControlListsIpAddressesGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountsSIPIpAccessControlListsIpAddressesKind}.String()
	AccountsSIPIpAccessControlListsIpAddressesKindAPIVersion   = AccountsSIPIpAccessControlListsIpAddressesKind + "." + SchemeGroupVersion.String()
	AccountsSIPIpAccessControlListsIpAddressesGroupVersionKind = SchemeGroupVersion.WithKind(AccountsSIPIpAccessControlListsIpAddressesKind)
)

func init() {
	SchemeBuilder.Register(&AccountsSIPIpAccessControlListsIpAddresses{}, &AccountsSIPIpAccessControlListsIpAddressesList{})
}
