//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPIpAccessControlListsIpAddresses) DeepCopyInto(out *AccountsSIPIpAccessControlListsIpAddresses) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPIpAccessControlListsIpAddresses.
func (in *AccountsSIPIpAccessControlListsIpAddresses) DeepCopy() *AccountsSIPIpAccessControlListsIpAddresses {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPIpAccessControlListsIpAddresses)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsSIPIpAccessControlListsIpAddresses) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPIpAccessControlListsIpAddressesList) DeepCopyInto(out *AccountsSIPIpAccessControlListsIpAddressesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccountsSIPIpAccessControlListsIpAddresses, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPIpAccessControlListsIpAddressesList.
func (in *AccountsSIPIpAccessControlListsIpAddressesList) DeepCopy() *AccountsSIPIpAccessControlListsIpAddressesList {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPIpAccessControlListsIpAddressesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsSIPIpAccessControlListsIpAddressesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPIpAccessControlListsIpAddressesObservation) DeepCopyInto(out *AccountsSIPIpAccessControlListsIpAddressesObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPIpAccessControlListsIpAddressesObservation.
func (in *AccountsSIPIpAccessControlListsIpAddressesObservation) DeepCopy() *AccountsSIPIpAccessControlListsIpAddressesObservation {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPIpAccessControlListsIpAddressesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPIpAccessControlListsIpAddressesParameters) DeepCopyInto(out *AccountsSIPIpAccessControlListsIpAddressesParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPIpAccessControlListsIpAddressesParameters.
func (in *AccountsSIPIpAccessControlListsIpAddressesParameters) DeepCopy() *AccountsSIPIpAccessControlListsIpAddressesParameters {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPIpAccessControlListsIpAddressesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPIpAccessControlListsIpAddressesSpec) DeepCopyInto(out *AccountsSIPIpAccessControlListsIpAddressesSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPIpAccessControlListsIpAddressesSpec.
func (in *AccountsSIPIpAccessControlListsIpAddressesSpec) DeepCopy() *AccountsSIPIpAccessControlListsIpAddressesSpec {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPIpAccessControlListsIpAddressesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPIpAccessControlListsIpAddressesStatus) DeepCopyInto(out *AccountsSIPIpAccessControlListsIpAddressesStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPIpAccessControlListsIpAddressesStatus.
func (in *AccountsSIPIpAccessControlListsIpAddressesStatus) DeepCopy() *AccountsSIPIpAccessControlListsIpAddressesStatus {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPIpAccessControlListsIpAddressesStatus)
	in.DeepCopyInto(out)
	return out
}
