//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsAuthRegistrationsCredentialListMappings) DeepCopyInto(out *AccountsSIPDomainsAuthRegistrationsCredentialListMappings) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsAuthRegistrationsCredentialListMappings.
func (in *AccountsSIPDomainsAuthRegistrationsCredentialListMappings) DeepCopy() *AccountsSIPDomainsAuthRegistrationsCredentialListMappings {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsAuthRegistrationsCredentialListMappings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsSIPDomainsAuthRegistrationsCredentialListMappings) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsAuthRegistrationsCredentialListMappingsList) DeepCopyInto(out *AccountsSIPDomainsAuthRegistrationsCredentialListMappingsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccountsSIPDomainsAuthRegistrationsCredentialListMappings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsAuthRegistrationsCredentialListMappingsList.
func (in *AccountsSIPDomainsAuthRegistrationsCredentialListMappingsList) DeepCopy() *AccountsSIPDomainsAuthRegistrationsCredentialListMappingsList {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsAuthRegistrationsCredentialListMappingsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsSIPDomainsAuthRegistrationsCredentialListMappingsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsAuthRegistrationsCredentialListMappingsObservation) DeepCopyInto(out *AccountsSIPDomainsAuthRegistrationsCredentialListMappingsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsAuthRegistrationsCredentialListMappingsObservation.
func (in *AccountsSIPDomainsAuthRegistrationsCredentialListMappingsObservation) DeepCopy() *AccountsSIPDomainsAuthRegistrationsCredentialListMappingsObservation {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsAuthRegistrationsCredentialListMappingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsAuthRegistrationsCredentialListMappingsParameters) DeepCopyInto(out *AccountsSIPDomainsAuthRegistrationsCredentialListMappingsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsAuthRegistrationsCredentialListMappingsParameters.
func (in *AccountsSIPDomainsAuthRegistrationsCredentialListMappingsParameters) DeepCopy() *AccountsSIPDomainsAuthRegistrationsCredentialListMappingsParameters {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsAuthRegistrationsCredentialListMappingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsAuthRegistrationsCredentialListMappingsSpec) DeepCopyInto(out *AccountsSIPDomainsAuthRegistrationsCredentialListMappingsSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsAuthRegistrationsCredentialListMappingsSpec.
func (in *AccountsSIPDomainsAuthRegistrationsCredentialListMappingsSpec) DeepCopy() *AccountsSIPDomainsAuthRegistrationsCredentialListMappingsSpec {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsAuthRegistrationsCredentialListMappingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsAuthRegistrationsCredentialListMappingsStatus) DeepCopyInto(out *AccountsSIPDomainsAuthRegistrationsCredentialListMappingsStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsAuthRegistrationsCredentialListMappingsStatus.
func (in *AccountsSIPDomainsAuthRegistrationsCredentialListMappingsStatus) DeepCopy() *AccountsSIPDomainsAuthRegistrationsCredentialListMappingsStatus {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsAuthRegistrationsCredentialListMappingsStatus)
	in.DeepCopyInto(out)
	return out
}
