// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

// Package twilio is the API client the controllers share.
//
// It is deliberately thin. twilio-go is a generated, maintained SDK for the
// whole of Twilio's API, and terraform-provider-twilio is built on it, so
// there is nothing here that builds a URL, encodes a form, signs a request or
// decodes an answer -- it would be a second, worse copy of all of that. What
// is left is the two things twilio-go does not know about: how a Crossplane
// ProviderConfig spells its credentials, and how a Crossplane controller
// projects an SDK struct onto status.atProvider.
package twilio

import (
	"encoding/json"
	"reflect"
	"strconv"
	"time"

	"github.com/crossplane/crossplane-runtime/v2/pkg/errors"
	twilio "github.com/twilio/twilio-go"
	twilioclient "github.com/twilio/twilio-go/client"
)

// Client is what a controller is handed.
type Client struct {
	Rest *twilio.RestClient
}

// Credentials is the JSON document in a ProviderConfig's secret.
//
// Twilio authenticates with HTTP basic, and there are two things to put in it:
// an Account SID with its Auth Token, or an API Key SID with its secret. The
// second is the one to prefer -- a key can be revoked without rotating the
// account -- and both are the same two fields on the wire, so either spelling
// is accepted.
//
//	{
//	  "accountSid": "AC...",
//	  "authToken":  "..."
//	}
//
//	{
//	  "accountSid": "AC...",
//	  "apiKey":     "SK...",
//	  "apiSecret":  "..."
//	}
type Credentials struct {
	AccountSid string `json:"accountSid,omitempty"`
	AuthToken  string `json:"authToken,omitempty"`
	APIKey     string `json:"apiKey,omitempty"`
	APISecret  string `json:"apiSecret,omitempty"`

	// Username and Password are accepted as aliases for whichever pair is in
	// use, because that is what basic auth calls them and what an existing
	// secret is likely to hold already.
	Username string `json:"username,omitempty"`
	Password string `json:"password,omitempty"`

	// Edge and Region reach Twilio somewhere other than the default.
	// twilio-go composes the host from them, which is why nothing here holds
	// an endpoint: the base URL of every operation comes from the SDK, and the
	// API description gives a different one per product
	// (api.twilio.com, messaging.twilio.com, taskrouter.twilio.com...).
	Edge   string `json:"edge,omitempty"`
	Region string `json:"region,omitempty"`
}

const (
	errCreds      = "cannot unmarshal Twilio credentials as JSON"
	errNoAccount  = "Twilio credentials need an accountSid"
	errNoPassword = "Twilio credentials need an authToken, or an apiKey and apiSecret"
)

// NewClientFromCredentials builds a client from a ProviderConfig's secret.
func NewClientFromCredentials(data []byte) (*Client, error) {
	creds := Credentials{}
	if err := json.Unmarshal(data, &creds); err != nil {
		return nil, errors.Wrap(err, errCreds)
	}

	// An API key authenticates as itself, with the account it belongs to named
	// separately; an auth token authenticates as the account.
	username, password := creds.APIKey, creds.APISecret
	if username == "" {
		username, password = creds.AccountSid, creds.AuthToken
	}
	if username == "" {
		username, password = creds.Username, creds.Password
	}
	if password == "" {
		password = creds.Password
	}

	if creds.AccountSid == "" && username == "" {
		return nil, errors.New(errNoAccount)
	}
	if password == "" {
		return nil, errors.New(errNoPassword)
	}

	params := twilio.ClientParams{
		Username: username,
		Password: password,
	}

	// Set only when it differs from the username, which is the API-key case:
	// twilio-go otherwise infers the account from the username, and an
	// AccountSid equal to it is what it would have chosen anyway.
	if creds.AccountSid != "" && creds.AccountSid != username {
		params.AccountSid = creds.AccountSid
	}

	rest := twilio.NewRestClientWithParams(params)

	// Edge and Region are setters on the client rather than fields on
	// ClientParams, and the SDK composes the host from them.
	if creds.Edge != "" {
		rest.SetEdge(creds.Edge)
	}
	if creds.Region != "" {
		rest.SetRegion(creds.Region)
	}

	return &Client{Rest: rest}, nil
}

// IsNotFound reports whether an error is Twilio answering 404.
//
// Only a 404 may be read as "it does not exist". A 500, a timeout or a 429
// must be surfaced: treating one as absence would provision a second resource
// and orphan the first.
func IsNotFound(err error) bool {
	if err == nil {
		return false
	}

	var apiErr *twilioclient.TwilioRestError
	if errors.As(err, &apiErr) {
		return apiErr.Status == 404
	}

	return false
}

// Set reports whether a spec field holds anything.
//
// An optional field a person left alone must not be sent, because Twilio reads
// an empty string as an instruction to CLEAR the field rather than as "no
// opinion" -- so "unset" and "set to empty" are different requests and a
// zero value has to mean the first.
//
// ponytail: reflection rather than a generic, because the fields are strings,
// bools, int64s, float64s and []strings, and a type parameter constrained to
// comparable would not accept the slice.
func Set(value any) bool {
	if value == nil {
		return false
	}

	return !reflect.ValueOf(value).IsZero()
}

// IntToString is what a resource whose identifier is a number needs, since an
// external name is a string. Named to match the generator's
// x-resource-id-conversion-func.
func IntToString(value int) string {
	return strconv.Itoa(value)
}

// Time parses an RFC 3339 timestamp for an SDK setter that takes a time.Time.
//
// A CRD field cannot be a time.Time, so a date-time parameter is carried as a
// string and converted here. An unparseable value yields the zero time rather
// than an error: the field is validated by Twilio, which gives a better
// message than this could, and failing the whole request over one malformed
// timestamp would hide the rest of it.
//
// ponytail: zero time on a parse failure; validate in the CRD with a
// kubebuilder pattern if a clearer local error is wanted.
func Time(value string) time.Time {
	parsed, err := time.Parse(time.RFC3339, value)
	if err != nil {
		return time.Time{}
	}

	return parsed
}

// Project copies a twilio-go response struct onto a status.atProvider struct.
//
// One function instead of a generated assignment per field, of which there
// would be some thousands. It works because both sides carry the SAME json
// tags -- the API's snake_case names -- so the response is marshalled and then
// read field by field into the observation.
//
// It is not a plain json.Unmarshal, and that is the whole reason it exists: an
// observation field is a string wherever the API answers something a CRD
// cannot describe (subresource_uris, links, any uri-map), and unmarshalling a
// JSON object into a Go string fails. Such a field is given the raw JSON text
// instead, which is what both existing providers store and what makes
// status.atProvider comparable by value rather than by shape.
func Project(from any, into any) error {
	raw, err := json.Marshal(from)
	if err != nil {
		return errors.Wrap(err, "cannot marshal the API response")
	}

	fields := map[string]json.RawMessage{}
	if err := json.Unmarshal(raw, &fields); err != nil {
		return errors.Wrap(err, "cannot read the API response as an object")
	}

	target := reflect.ValueOf(into)
	if target.Kind() != reflect.Ptr || target.IsNil() {
		return errors.New("Project needs a pointer to a struct")
	}
	target = target.Elem()
	if target.Kind() != reflect.Struct {
		return errors.New("Project needs a pointer to a struct")
	}

	for i := 0; i < target.NumField(); i++ {
		name := jsonName(target.Type().Field(i))
		value, ok := fields[name]
		if !ok || string(value) == "null" {
			continue
		}

		field := target.Field(i)

		// The straightforward case: the shapes agree.
		if err := json.Unmarshal(value, field.Addr().Interface()); err == nil {
			continue
		}

		// They do not, which for a string field means the API answered an
		// object or an array. Store the document itself.
		if field.Kind() == reflect.String {
			field.SetString(string(value))
			continue
		}

		return errors.Errorf("cannot project %q onto %s", name, field.Type())
	}

	return nil
}

// jsonName is the wire name of a struct field, which is the API's own spelling.
func jsonName(field reflect.StructField) string {
	tag := field.Tag.Get("json")
	for i := 0; i < len(tag); i++ {
		if tag[i] == ',' {
			tag = tag[:i]
			break
		}
	}

	if tag == "" || tag == "-" {
		return field.Name
	}

	return tag
}
