// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Kind{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AccountsSIPCredentialListsCredentialsParameters are the configurable fields of a AccountsSIPCredentialListsCredentials.
//
// These are the parameters of the create operation (CreateSipCredential), plus any the
// update accepts and the create does not. The fields are spelled the way
// Twilio TAKES them -- PascalCase -- because that is the name the request
// carries; status.atProvider spells the same values the way Twilio ANSWERS
// them, in snake_case. Nothing translates between the two, so nothing can
// drift out of a translation layer.
type AccountsSIPCredentialListsCredentialsParameters struct {
	// CredentialListSid The unique id that identifies the credential list to include the created credential.
	// +kubebuilder:validation:Required
	CredentialListSid string `json:"CredentialListSid"`
	// Username The username that will be passed when authenticating SIP requests. The username should be sent in response to Twilio's challenge of the initial INVITE. It can be up to 32 characters long.
	// +kubebuilder:validation:Required
	Username string `json:"Username"`
	// Password The password that the username will use when authenticating SIP requests. The password must be a minimum of 12 characters, contain at least 1 digit, and have mixed case. (eg `IWasAtSignal2018`)
	// +kubebuilder:validation:Required
	Password string `json:"Password"`
	// PathAccountSid The unique id of the Account that is responsible for this resource.
	// +optional
	PathAccountSid string `json:"PathAccountSid,omitempty"`
}

// AccountsSIPCredentialListsCredentialsObservation are the observable fields of a AccountsSIPCredentialListsCredentials.
//
// These are the properties of what the read (FetchSipCredential) answers -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AccountsSIPCredentialListsCredentialsObservation struct {
	Sid               string `json:"sid,omitempty"`
	AccountSid        string `json:"account_sid,omitempty"`
	CredentialListSid string `json:"credential_list_sid,omitempty"`
	Username          string `json:"username,omitempty"`
	DateCreated       string `json:"date_created,omitempty"`
	DateUpdated       string `json:"date_updated,omitempty"`
	Uri               string `json:"uri,omitempty"`
}

// A AccountsSIPCredentialListsCredentialsSpec defines the desired state of a AccountsSIPCredentialListsCredentials.
type AccountsSIPCredentialListsCredentialsSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AccountsSIPCredentialListsCredentialsParameters `json:"forProvider"`
}

// A AccountsSIPCredentialListsCredentialsStatus represents the observed state of a AccountsSIPCredentialListsCredentials.
type AccountsSIPCredentialListsCredentialsStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AccountsSIPCredentialListsCredentialsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AccountsSIPCredentialListsCredentials is a managed Twilio resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twilio}
type AccountsSIPCredentialListsCredentials struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AccountsSIPCredentialListsCredentialsSpec   `json:"spec"`
	Status AccountsSIPCredentialListsCredentialsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountsSIPCredentialListsCredentialsList contains a list of AccountsSIPCredentialListsCredentials
type AccountsSIPCredentialListsCredentialsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountsSIPCredentialListsCredentials `json:"items"`
}

// AccountsSIPCredentialListsCredentials type metadata.
var (
	AccountsSIPCredentialListsCredentialsKind             = reflect.TypeOf(AccountsSIPCredentialListsCredentials{}).Name()
	AccountsSIPCredentialListsCredentialsGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountsSIPCredentialListsCredentialsKind}.String()
	AccountsSIPCredentialListsCredentialsKindAPIVersion   = AccountsSIPCredentialListsCredentialsKind + "." + SchemeGroupVersion.String()
	AccountsSIPCredentialListsCredentialsGroupVersionKind = SchemeGroupVersion.WithKind(AccountsSIPCredentialListsCredentialsKind)
)

func init() {
	SchemeBuilder.Register(&AccountsSIPCredentialListsCredentials{}, &AccountsSIPCredentialListsCredentialsList{})
}
