//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPCredentialListsCredentials) DeepCopyInto(out *AccountsSIPCredentialListsCredentials) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPCredentialListsCredentials.
func (in *AccountsSIPCredentialListsCredentials) DeepCopy() *AccountsSIPCredentialListsCredentials {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPCredentialListsCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsSIPCredentialListsCredentials) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPCredentialListsCredentialsList) DeepCopyInto(out *AccountsSIPCredentialListsCredentialsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccountsSIPCredentialListsCredentials, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPCredentialListsCredentialsList.
func (in *AccountsSIPCredentialListsCredentialsList) DeepCopy() *AccountsSIPCredentialListsCredentialsList {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPCredentialListsCredentialsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsSIPCredentialListsCredentialsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPCredentialListsCredentialsObservation) DeepCopyInto(out *AccountsSIPCredentialListsCredentialsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPCredentialListsCredentialsObservation.
func (in *AccountsSIPCredentialListsCredentialsObservation) DeepCopy() *AccountsSIPCredentialListsCredentialsObservation {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPCredentialListsCredentialsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPCredentialListsCredentialsParameters) DeepCopyInto(out *AccountsSIPCredentialListsCredentialsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPCredentialListsCredentialsParameters.
func (in *AccountsSIPCredentialListsCredentialsParameters) DeepCopy() *AccountsSIPCredentialListsCredentialsParameters {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPCredentialListsCredentialsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPCredentialListsCredentialsSpec) DeepCopyInto(out *AccountsSIPCredentialListsCredentialsSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPCredentialListsCredentialsSpec.
func (in *AccountsSIPCredentialListsCredentialsSpec) DeepCopy() *AccountsSIPCredentialListsCredentialsSpec {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPCredentialListsCredentialsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPCredentialListsCredentialsStatus) DeepCopyInto(out *AccountsSIPCredentialListsCredentialsStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPCredentialListsCredentialsStatus.
func (in *AccountsSIPCredentialListsCredentialsStatus) DeepCopy() *AccountsSIPCredentialListsCredentialsStatus {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPCredentialListsCredentialsStatus)
	in.DeepCopyInto(out)
	return out
}
