// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Kind{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AccountsCallsRecordingsParameters are the configurable fields of a AccountsCallsRecordings.
//
// These are the parameters of the create operation (CreateCallRecording), plus any the
// update accepts and the create does not. The fields are spelled the way
// Twilio TAKES them -- PascalCase -- because that is the name the request
// carries; status.atProvider spells the same values the way Twilio ANSWERS
// them, in snake_case. Nothing translates between the two, so nothing can
// drift out of a translation layer.
type AccountsCallsRecordingsParameters struct {
	// CallSid The SID of the [Call](https://www.twilio.com/docs/voice/api/call-resource) to associate the resource with.
	// +kubebuilder:validation:Required
	CallSid string `json:"CallSid"`
	// PathAccountSid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that will create the resource.
	// +optional
	PathAccountSid string `json:"PathAccountSid,omitempty"`
	// RecordingStatusCallbackEvent The recording status events on which we should call the `recording_status_callback` URL. Can be: `in-progress`, `completed` and `absent` and the default is `completed`. Separate multiple event values with a space.
	// +optional
	RecordingStatusCallbackEvent []string `json:"RecordingStatusCallbackEvent,omitempty"`
	// RecordingStatusCallback The URL we should call using the `recording_status_callback_method` on each recording event specified in `recording_status_callback_event`. For more information, see [RecordingStatusCallback parameters](https://www.twilio.com/docs/voice/api/recording#recordingstatuscallback).
	// +optional
	RecordingStatusCallback string `json:"RecordingStatusCallback,omitempty"`
	// RecordingStatusCallbackMethod The HTTP method we should use to call `recording_status_callback`. Can be: `GET` or `POST` and the default is `POST`.
	// +optional
	RecordingStatusCallbackMethod string `json:"RecordingStatusCallbackMethod,omitempty"`
	// Trim Whether to trim any leading and trailing silence in the recording. Can be: `trim-silence` or `do-not-trim` and the default is `do-not-trim`. `trim-silence` trims the silence from the beginning and end of the recording and `do-not-trim` does not.
	// +optional
	Trim string `json:"Trim,omitempty"`
	// RecordingChannels The number of channels used in the recording. Can be: `mono` or `dual` and the default is `mono`. `mono` records all parties of the call into one channel. `dual` records each party of a 2-party call into separate channels.
	// +optional
	RecordingChannels string `json:"RecordingChannels,omitempty"`
	// RecordingTrack The audio track to record for the call. Can be: `inbound`, `outbound` or `both`. The default is `both`. `inbound` records the audio that is received by Twilio. `outbound` records the audio that is generated from Twilio. `both` records the audio that is received and generated by Twilio.
	// +optional
	RecordingTrack string `json:"RecordingTrack,omitempty"`
	// RecordingConfigurationId The identifier of the configuration to be used when creating and processing the recording
	// +optional
	RecordingConfigurationId string `json:"RecordingConfigurationId,omitempty"`
	// Status
	// +kubebuilder:validation:Required
	Status string `json:"Status"`
	// PauseBehavior Whether to record during a pause. Can be: `skip` or `silence` and the default is `silence`. `skip` does not record during the pause period, while `silence` will replace the actual audio of the call with silence during the pause period. This parameter only applies when setting `status` is set to `paused`.
	// +optional
	PauseBehavior string `json:"PauseBehavior,omitempty"`
}

// AccountsCallsRecordingsObservation are the observable fields of a AccountsCallsRecordings.
//
// These are the properties of what the read (FetchCallRecording) answers -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AccountsCallsRecordingsObservation struct {
	AccountSid        string  `json:"account_sid,omitempty"`
	ApiVersion        string  `json:"api_version,omitempty"`
	CallSid           string  `json:"call_sid,omitempty"`
	ConferenceSid     string  `json:"conference_sid,omitempty"`
	DateCreated       string  `json:"date_created,omitempty"`
	DateUpdated       string  `json:"date_updated,omitempty"`
	StartTime         string  `json:"start_time,omitempty"`
	Duration          string  `json:"duration,omitempty"`
	Sid               string  `json:"sid,omitempty"`
	Price             float64 `json:"price,omitempty"`
	Uri               string  `json:"uri,omitempty"`
	EncryptionDetails string  `json:"encryption_details,omitempty"`
	PriceUnit         string  `json:"price_unit,omitempty"`
	Status            string  `json:"status,omitempty"`
	Channels          int64   `json:"channels,omitempty"`
	Source            string  `json:"source,omitempty"`
	ErrorCode         int64   `json:"error_code,omitempty"`
	Track             string  `json:"track,omitempty"`
}

// A AccountsCallsRecordingsSpec defines the desired state of a AccountsCallsRecordings.
type AccountsCallsRecordingsSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AccountsCallsRecordingsParameters `json:"forProvider"`
}

// A AccountsCallsRecordingsStatus represents the observed state of a AccountsCallsRecordings.
type AccountsCallsRecordingsStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AccountsCallsRecordingsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AccountsCallsRecordings is a managed Twilio resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twilio}
type AccountsCallsRecordings struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AccountsCallsRecordingsSpec   `json:"spec"`
	Status AccountsCallsRecordingsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountsCallsRecordingsList contains a list of AccountsCallsRecordings
type AccountsCallsRecordingsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountsCallsRecordings `json:"items"`
}

// AccountsCallsRecordings type metadata.
var (
	AccountsCallsRecordingsKind             = reflect.TypeOf(AccountsCallsRecordings{}).Name()
	AccountsCallsRecordingsGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountsCallsRecordingsKind}.String()
	AccountsCallsRecordingsKindAPIVersion   = AccountsCallsRecordingsKind + "." + SchemeGroupVersion.String()
	AccountsCallsRecordingsGroupVersionKind = SchemeGroupVersion.WithKind(AccountsCallsRecordingsKind)
)

func init() {
	SchemeBuilder.Register(&AccountsCallsRecordings{}, &AccountsCallsRecordingsList{})
}
