//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsCallsRecordings) DeepCopyInto(out *AccountsCallsRecordings) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsCallsRecordings.
func (in *AccountsCallsRecordings) DeepCopy() *AccountsCallsRecordings {
	if in == nil {
		return nil
	}
	out := new(AccountsCallsRecordings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsCallsRecordings) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsCallsRecordingsList) DeepCopyInto(out *AccountsCallsRecordingsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccountsCallsRecordings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsCallsRecordingsList.
func (in *AccountsCallsRecordingsList) DeepCopy() *AccountsCallsRecordingsList {
	if in == nil {
		return nil
	}
	out := new(AccountsCallsRecordingsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsCallsRecordingsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsCallsRecordingsObservation) DeepCopyInto(out *AccountsCallsRecordingsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsCallsRecordingsObservation.
func (in *AccountsCallsRecordingsObservation) DeepCopy() *AccountsCallsRecordingsObservation {
	if in == nil {
		return nil
	}
	out := new(AccountsCallsRecordingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsCallsRecordingsParameters) DeepCopyInto(out *AccountsCallsRecordingsParameters) {
	*out = *in
	if in.RecordingStatusCallbackEvent != nil {
		in, out := &in.RecordingStatusCallbackEvent, &out.RecordingStatusCallbackEvent
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsCallsRecordingsParameters.
func (in *AccountsCallsRecordingsParameters) DeepCopy() *AccountsCallsRecordingsParameters {
	if in == nil {
		return nil
	}
	out := new(AccountsCallsRecordingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsCallsRecordingsSpec) DeepCopyInto(out *AccountsCallsRecordingsSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsCallsRecordingsSpec.
func (in *AccountsCallsRecordingsSpec) DeepCopy() *AccountsCallsRecordingsSpec {
	if in == nil {
		return nil
	}
	out := new(AccountsCallsRecordingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsCallsRecordingsStatus) DeepCopyInto(out *AccountsCallsRecordingsStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsCallsRecordingsStatus.
func (in *AccountsCallsRecordingsStatus) DeepCopy() *AccountsCallsRecordingsStatus {
	if in == nil {
		return nil
	}
	out := new(AccountsCallsRecordingsStatus)
	in.DeepCopyInto(out)
	return out
}
