// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Kind{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AccountsSIPDomainsCredentialListMappingsParameters are the configurable fields of a AccountsSIPDomainsCredentialListMappings.
//
// These are the parameters of the create operation (CreateSipCredentialListMapping), plus any the
// update accepts and the create does not. The fields are spelled the way
// Twilio TAKES them -- PascalCase -- because that is the name the request
// carries; status.atProvider spells the same values the way Twilio ANSWERS
// them, in snake_case. Nothing translates between the two, so nothing can
// drift out of a translation layer.
type AccountsSIPDomainsCredentialListMappingsParameters struct {
	// DomainSid A 34 character string that uniquely identifies the SIP Domain for which the CredentialList resource will be mapped.
	// +kubebuilder:validation:Required
	DomainSid string `json:"DomainSid"`
	// CredentialListSid A 34 character string that uniquely identifies the CredentialList resource to map to the SIP domain.
	// +kubebuilder:validation:Required
	CredentialListSid string `json:"CredentialListSid"`
	// PathAccountSid The unique id of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this resource.
	// +optional
	PathAccountSid string `json:"PathAccountSid,omitempty"`
}

// AccountsSIPDomainsCredentialListMappingsObservation are the observable fields of a AccountsSIPDomainsCredentialListMappings.
//
// These are the properties of what the read (FetchSipCredentialListMapping) answers -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AccountsSIPDomainsCredentialListMappingsObservation struct {
	AccountSid   string `json:"account_sid,omitempty"`
	DateCreated  string `json:"date_created,omitempty"`
	DateUpdated  string `json:"date_updated,omitempty"`
	DomainSid    string `json:"domain_sid,omitempty"`
	FriendlyName string `json:"friendly_name,omitempty"`
	Sid          string `json:"sid,omitempty"`
	Uri          string `json:"uri,omitempty"`
}

// A AccountsSIPDomainsCredentialListMappingsSpec defines the desired state of a AccountsSIPDomainsCredentialListMappings.
type AccountsSIPDomainsCredentialListMappingsSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AccountsSIPDomainsCredentialListMappingsParameters `json:"forProvider"`
}

// A AccountsSIPDomainsCredentialListMappingsStatus represents the observed state of a AccountsSIPDomainsCredentialListMappings.
type AccountsSIPDomainsCredentialListMappingsStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AccountsSIPDomainsCredentialListMappingsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AccountsSIPDomainsCredentialListMappings is a managed Twilio resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twilio}
type AccountsSIPDomainsCredentialListMappings struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AccountsSIPDomainsCredentialListMappingsSpec   `json:"spec"`
	Status AccountsSIPDomainsCredentialListMappingsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountsSIPDomainsCredentialListMappingsList contains a list of AccountsSIPDomainsCredentialListMappings
type AccountsSIPDomainsCredentialListMappingsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountsSIPDomainsCredentialListMappings `json:"items"`
}

// AccountsSIPDomainsCredentialListMappings type metadata.
var (
	AccountsSIPDomainsCredentialListMappingsKind             = reflect.TypeOf(AccountsSIPDomainsCredentialListMappings{}).Name()
	AccountsSIPDomainsCredentialListMappingsGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountsSIPDomainsCredentialListMappingsKind}.String()
	AccountsSIPDomainsCredentialListMappingsKindAPIVersion   = AccountsSIPDomainsCredentialListMappingsKind + "." + SchemeGroupVersion.String()
	AccountsSIPDomainsCredentialListMappingsGroupVersionKind = SchemeGroupVersion.WithKind(AccountsSIPDomainsCredentialListMappingsKind)
)

func init() {
	SchemeBuilder.Register(&AccountsSIPDomainsCredentialListMappings{}, &AccountsSIPDomainsCredentialListMappingsList{})
}
