//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsCredentialListMappings) DeepCopyInto(out *AccountsSIPDomainsCredentialListMappings) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsCredentialListMappings.
func (in *AccountsSIPDomainsCredentialListMappings) DeepCopy() *AccountsSIPDomainsCredentialListMappings {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsCredentialListMappings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsSIPDomainsCredentialListMappings) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsCredentialListMappingsList) DeepCopyInto(out *AccountsSIPDomainsCredentialListMappingsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccountsSIPDomainsCredentialListMappings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsCredentialListMappingsList.
func (in *AccountsSIPDomainsCredentialListMappingsList) DeepCopy() *AccountsSIPDomainsCredentialListMappingsList {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsCredentialListMappingsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsSIPDomainsCredentialListMappingsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsCredentialListMappingsObservation) DeepCopyInto(out *AccountsSIPDomainsCredentialListMappingsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsCredentialListMappingsObservation.
func (in *AccountsSIPDomainsCredentialListMappingsObservation) DeepCopy() *AccountsSIPDomainsCredentialListMappingsObservation {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsCredentialListMappingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsCredentialListMappingsParameters) DeepCopyInto(out *AccountsSIPDomainsCredentialListMappingsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsCredentialListMappingsParameters.
func (in *AccountsSIPDomainsCredentialListMappingsParameters) DeepCopy() *AccountsSIPDomainsCredentialListMappingsParameters {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsCredentialListMappingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsCredentialListMappingsSpec) DeepCopyInto(out *AccountsSIPDomainsCredentialListMappingsSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsCredentialListMappingsSpec.
func (in *AccountsSIPDomainsCredentialListMappingsSpec) DeepCopy() *AccountsSIPDomainsCredentialListMappingsSpec {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsCredentialListMappingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsCredentialListMappingsStatus) DeepCopyInto(out *AccountsSIPDomainsCredentialListMappingsStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsCredentialListMappingsStatus.
func (in *AccountsSIPDomainsCredentialListMappingsStatus) DeepCopy() *AccountsSIPDomainsCredentialListMappingsStatus {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsCredentialListMappingsStatus)
	in.DeepCopyInto(out)
	return out
}
