// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Kind{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AccountsSIPDomainsIpAccessControlListMappingsParameters are the configurable fields of a AccountsSIPDomainsIpAccessControlListMappings.
//
// These are the parameters of the create operation (CreateSipIpAccessControlListMapping), plus any the
// update accepts and the create does not. The fields are spelled the way
// Twilio TAKES them -- PascalCase -- because that is the name the request
// carries; status.atProvider spells the same values the way Twilio ANSWERS
// them, in snake_case. Nothing translates between the two, so nothing can
// drift out of a translation layer.
type AccountsSIPDomainsIpAccessControlListMappingsParameters struct {
	// DomainSid A 34 character string that uniquely identifies the SIP domain.
	// +kubebuilder:validation:Required
	DomainSid string `json:"DomainSid"`
	// IpAccessControlListSid The unique id of the IP access control list to map to the SIP domain.
	// +kubebuilder:validation:Required
	IpAccessControlListSid string `json:"IpAccessControlListSid"`
	// PathAccountSid The unique id of the Account that is responsible for this resource.
	// +optional
	PathAccountSid string `json:"PathAccountSid,omitempty"`
}

// AccountsSIPDomainsIpAccessControlListMappingsObservation are the observable fields of a AccountsSIPDomainsIpAccessControlListMappings.
//
// These are the properties of what the read (FetchSipIpAccessControlListMapping) answers -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AccountsSIPDomainsIpAccessControlListMappingsObservation struct {
	AccountSid   string `json:"account_sid,omitempty"`
	DateCreated  string `json:"date_created,omitempty"`
	DateUpdated  string `json:"date_updated,omitempty"`
	DomainSid    string `json:"domain_sid,omitempty"`
	FriendlyName string `json:"friendly_name,omitempty"`
	Sid          string `json:"sid,omitempty"`
	Uri          string `json:"uri,omitempty"`
}

// A AccountsSIPDomainsIpAccessControlListMappingsSpec defines the desired state of a AccountsSIPDomainsIpAccessControlListMappings.
type AccountsSIPDomainsIpAccessControlListMappingsSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AccountsSIPDomainsIpAccessControlListMappingsParameters `json:"forProvider"`
}

// A AccountsSIPDomainsIpAccessControlListMappingsStatus represents the observed state of a AccountsSIPDomainsIpAccessControlListMappings.
type AccountsSIPDomainsIpAccessControlListMappingsStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AccountsSIPDomainsIpAccessControlListMappingsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AccountsSIPDomainsIpAccessControlListMappings is a managed Twilio resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twilio}
type AccountsSIPDomainsIpAccessControlListMappings struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AccountsSIPDomainsIpAccessControlListMappingsSpec   `json:"spec"`
	Status AccountsSIPDomainsIpAccessControlListMappingsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountsSIPDomainsIpAccessControlListMappingsList contains a list of AccountsSIPDomainsIpAccessControlListMappings
type AccountsSIPDomainsIpAccessControlListMappingsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountsSIPDomainsIpAccessControlListMappings `json:"items"`
}

// AccountsSIPDomainsIpAccessControlListMappings type metadata.
var (
	AccountsSIPDomainsIpAccessControlListMappingsKind             = reflect.TypeOf(AccountsSIPDomainsIpAccessControlListMappings{}).Name()
	AccountsSIPDomainsIpAccessControlListMappingsGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountsSIPDomainsIpAccessControlListMappingsKind}.String()
	AccountsSIPDomainsIpAccessControlListMappingsKindAPIVersion   = AccountsSIPDomainsIpAccessControlListMappingsKind + "." + SchemeGroupVersion.String()
	AccountsSIPDomainsIpAccessControlListMappingsGroupVersionKind = SchemeGroupVersion.WithKind(AccountsSIPDomainsIpAccessControlListMappingsKind)
)

func init() {
	SchemeBuilder.Register(&AccountsSIPDomainsIpAccessControlListMappings{}, &AccountsSIPDomainsIpAccessControlListMappingsList{})
}
