//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsIpAccessControlListMappings) DeepCopyInto(out *AccountsSIPDomainsIpAccessControlListMappings) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsIpAccessControlListMappings.
func (in *AccountsSIPDomainsIpAccessControlListMappings) DeepCopy() *AccountsSIPDomainsIpAccessControlListMappings {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsIpAccessControlListMappings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsSIPDomainsIpAccessControlListMappings) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsIpAccessControlListMappingsList) DeepCopyInto(out *AccountsSIPDomainsIpAccessControlListMappingsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccountsSIPDomainsIpAccessControlListMappings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsIpAccessControlListMappingsList.
func (in *AccountsSIPDomainsIpAccessControlListMappingsList) DeepCopy() *AccountsSIPDomainsIpAccessControlListMappingsList {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsIpAccessControlListMappingsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsSIPDomainsIpAccessControlListMappingsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsIpAccessControlListMappingsObservation) DeepCopyInto(out *AccountsSIPDomainsIpAccessControlListMappingsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsIpAccessControlListMappingsObservation.
func (in *AccountsSIPDomainsIpAccessControlListMappingsObservation) DeepCopy() *AccountsSIPDomainsIpAccessControlListMappingsObservation {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsIpAccessControlListMappingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsIpAccessControlListMappingsParameters) DeepCopyInto(out *AccountsSIPDomainsIpAccessControlListMappingsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsIpAccessControlListMappingsParameters.
func (in *AccountsSIPDomainsIpAccessControlListMappingsParameters) DeepCopy() *AccountsSIPDomainsIpAccessControlListMappingsParameters {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsIpAccessControlListMappingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsIpAccessControlListMappingsSpec) DeepCopyInto(out *AccountsSIPDomainsIpAccessControlListMappingsSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsIpAccessControlListMappingsSpec.
func (in *AccountsSIPDomainsIpAccessControlListMappingsSpec) DeepCopy() *AccountsSIPDomainsIpAccessControlListMappingsSpec {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsIpAccessControlListMappingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSIPDomainsIpAccessControlListMappingsStatus) DeepCopyInto(out *AccountsSIPDomainsIpAccessControlListMappingsStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSIPDomainsIpAccessControlListMappingsStatus.
func (in *AccountsSIPDomainsIpAccessControlListMappingsStatus) DeepCopy() *AccountsSIPDomainsIpAccessControlListMappingsStatus {
	if in == nil {
		return nil
	}
	out := new(AccountsSIPDomainsIpAccessControlListMappingsStatus)
	in.DeepCopyInto(out)
	return out
}
