// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Kind{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AccountsQueuesParameters are the configurable fields of a AccountsQueues.
//
// These are the parameters of the create operation (CreateQueue), plus any the
// update accepts and the create does not. The fields are spelled the way
// Twilio TAKES them -- PascalCase -- because that is the name the request
// carries; status.atProvider spells the same values the way Twilio ANSWERS
// them, in snake_case. Nothing translates between the two, so nothing can
// drift out of a translation layer.
type AccountsQueuesParameters struct {
	// FriendlyName A descriptive string that you created to describe this resource. It can be up to 64 characters long.
	// +kubebuilder:validation:Required
	FriendlyName string `json:"FriendlyName"`
	// PathAccountSid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that will create the resource.
	// +optional
	PathAccountSid string `json:"PathAccountSid,omitempty"`
	// MaxSize The maximum number of calls allowed to be in the queue. The default is 1000. The maximum is 5000.
	// +optional
	MaxSize int `json:"MaxSize,omitempty"`
}

// AccountsQueuesObservation are the observable fields of a AccountsQueues.
//
// These are the properties of what the read (FetchQueue) answers -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AccountsQueuesObservation struct {
	DateUpdated     string `json:"date_updated,omitempty"`
	CurrentSize     int64  `json:"current_size,omitempty"`
	FriendlyName    string `json:"friendly_name,omitempty"`
	Uri             string `json:"uri,omitempty"`
	AccountSid      string `json:"account_sid,omitempty"`
	AverageWaitTime int64  `json:"average_wait_time,omitempty"`
	Sid             string `json:"sid,omitempty"`
	DateCreated     string `json:"date_created,omitempty"`
	MaxSize         int64  `json:"max_size,omitempty"`
}

// A AccountsQueuesSpec defines the desired state of a AccountsQueues.
type AccountsQueuesSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AccountsQueuesParameters `json:"forProvider"`
}

// A AccountsQueuesStatus represents the observed state of a AccountsQueues.
type AccountsQueuesStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AccountsQueuesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AccountsQueues is a managed Twilio resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twilio}
type AccountsQueues struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AccountsQueuesSpec   `json:"spec"`
	Status AccountsQueuesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountsQueuesList contains a list of AccountsQueues
type AccountsQueuesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountsQueues `json:"items"`
}

// AccountsQueues type metadata.
var (
	AccountsQueuesKind             = reflect.TypeOf(AccountsQueues{}).Name()
	AccountsQueuesGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountsQueuesKind}.String()
	AccountsQueuesKindAPIVersion   = AccountsQueuesKind + "." + SchemeGroupVersion.String()
	AccountsQueuesGroupVersionKind = SchemeGroupVersion.WithKind(AccountsQueuesKind)
)

func init() {
	SchemeBuilder.Register(&AccountsQueues{}, &AccountsQueuesList{})
}
