// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Kind{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AccountsKeysParameters are the configurable fields of a AccountsKeys.
//
// These are the parameters of the create operation (CreateNewKey), plus any the
// update accepts and the create does not. The fields are spelled the way
// Twilio TAKES them -- PascalCase -- because that is the name the request
// carries; status.atProvider spells the same values the way Twilio ANSWERS
// them, in snake_case. Nothing translates between the two, so nothing can
// drift out of a translation layer.
type AccountsKeysParameters struct {
	// PathAccountSid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that will be responsible for the new Key resource.
	// +optional
	PathAccountSid string `json:"PathAccountSid,omitempty"`
	// FriendlyName A descriptive string that you create to describe the resource. It can be up to 64 characters long.
	// +optional
	FriendlyName string `json:"FriendlyName,omitempty"`
}

// AccountsKeysObservation are the observable fields of a AccountsKeys.
//
// These are the properties of what the read (FetchKey) answers -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AccountsKeysObservation struct {
	Sid          string `json:"sid,omitempty"`
	FriendlyName string `json:"friendly_name,omitempty"`
	DateCreated  string `json:"date_created,omitempty"`
	DateUpdated  string `json:"date_updated,omitempty"`
}

// A AccountsKeysSpec defines the desired state of a AccountsKeys.
type AccountsKeysSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AccountsKeysParameters `json:"forProvider"`
}

// A AccountsKeysStatus represents the observed state of a AccountsKeys.
type AccountsKeysStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AccountsKeysObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AccountsKeys is a managed Twilio resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twilio}
type AccountsKeys struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AccountsKeysSpec   `json:"spec"`
	Status AccountsKeysStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountsKeysList contains a list of AccountsKeys
type AccountsKeysList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountsKeys `json:"items"`
}

// AccountsKeys type metadata.
var (
	AccountsKeysKind             = reflect.TypeOf(AccountsKeys{}).Name()
	AccountsKeysGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountsKeysKind}.String()
	AccountsKeysKindAPIVersion   = AccountsKeysKind + "." + SchemeGroupVersion.String()
	AccountsKeysGroupVersionKind = SchemeGroupVersion.WithKind(AccountsKeysKind)
)

func init() {
	SchemeBuilder.Register(&AccountsKeys{}, &AccountsKeysList{})
}
