// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accounts_signing_keys

import (
	"context"

	"github.com/crossplane/crossplane-runtime/v2/pkg/controller"
	"github.com/crossplane/crossplane-runtime/v2/pkg/errors"
	"github.com/crossplane/crossplane-runtime/v2/pkg/event"
	"github.com/crossplane/crossplane-runtime/v2/pkg/feature"
	"github.com/crossplane/crossplane-runtime/v2/pkg/meta"
	"github.com/crossplane/crossplane-runtime/v2/pkg/ratelimiter"
	"github.com/crossplane/crossplane-runtime/v2/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	"github.com/crossplane/crossplane-runtime/v2/pkg/statemetrics"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"

	twiliogo "github.com/twilio/twilio-go/rest/api/v2010"

	"github.com/n-at-han-k/crossplane-provider-twilio/apis/accounts_signing_keys/v1alpha1"
	apisv1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/v1alpha1"
	"github.com/n-at-han-k/crossplane-provider-twilio/internal/clients/twilio"
)

const (
	errTrackPCUsage = "cannot track ProviderConfig usage"
	errGetPC        = "cannot get ProviderConfig"
	errGetCPC       = "cannot get ClusterProviderConfig"
	errGetCreds     = "cannot get credentials"
	errNewClient    = "cannot create new Service"

	errGet     = "cannot get Twilio accountssigningkeys"
	errCreate  = "cannot create Twilio accountssigningkeys"
	errUpdate  = "cannot update Twilio accountssigningkeys"
	errDelete  = "cannot delete Twilio accountssigningkeys"
	errObserve = "cannot project the Twilio accountssigningkeys onto status.atProvider"

	// errNoID guards the one failure mode that silently leaks a resource: the
	// create succeeds but the answer carries no identifier. Setting an empty
	// external name would make every later Observe report ResourceExists:
	// false and create another one, for ever.
	errNoID = "Twilio returned no accountssigningkeys identifier from create; refusing to record an empty external name (one may have been created and needs manual cleanup)"
)

// newService builds the API client from the extracted credentials.
var newService = func(creds []byte) (*twilio.Client, error) {
	return twilio.NewClientFromCredentials(creds)
}

// SetupGated adds a controller that reconciles AccountsSigningKeys managed resources with safe-start support.
func SetupGated(mgr ctrl.Manager, o controller.Options) error {
	o.Gate.Register(func() {
		if err := Setup(mgr, o); err != nil {
			panic(errors.Wrap(err, "cannot setup AccountsSigningKeys controller"))
		}
	}, v1alpha1.AccountsSigningKeysGroupVersionKind)
	return nil
}

// Setup adds a controller that reconciles AccountsSigningKeys managed resources.
func Setup(mgr ctrl.Manager, o controller.Options) error {
	name := managed.ControllerName(v1alpha1.AccountsSigningKeysGroupKind)

	opts := []managed.ReconcilerOption{
		managed.WithTypedExternalConnector[*v1alpha1.AccountsSigningKeys](&connector{
			kube:         mgr.GetClient(),
			usage:        resource.NewProviderConfigUsageTracker(mgr.GetClient(), &apisv1alpha1.ProviderConfigUsage{}),
			newServiceFn: newService,
		}),
		managed.WithLogger(o.Logger.WithValues("controller", name)),
		managed.WithPollInterval(o.PollInterval),
		managed.WithRecorder(event.NewAPIRecorder(mgr.GetEventRecorderFor(name))), //nolint:staticcheck // Crossplane has not moved to the new events API yet.
	}

	if o.Features.Enabled(feature.EnableBetaManagementPolicies) {
		opts = append(opts, managed.WithManagementPolicies())
	}

	if o.Features.Enabled(feature.EnableAlphaChangeLogs) {
		opts = append(opts, managed.WithChangeLogger(o.ChangeLogOptions.ChangeLogger))
	}

	if o.MetricOptions != nil {
		opts = append(opts, managed.WithMetricRecorder(o.MetricOptions.MRMetrics))
	}

	if o.MetricOptions != nil && o.MetricOptions.MRStateMetrics != nil {
		stateMetricsRecorder := statemetrics.NewMRStateRecorder(
			mgr.GetClient(), o.Logger, o.MetricOptions.MRStateMetrics, &v1alpha1.AccountsSigningKeysList{}, o.MetricOptions.PollStateMetricInterval,
		)
		if err := mgr.Add(stateMetricsRecorder); err != nil {
			return errors.Wrap(err, "cannot register MR state metrics recorder for kind v1alpha1.AccountsSigningKeysList")
		}
	}

	r := managed.NewReconciler(mgr, resource.ManagedKind(v1alpha1.AccountsSigningKeysGroupVersionKind), opts...)

	return ctrl.NewControllerManagedBy(mgr).
		Named(name).
		WithOptions(o.ForControllerRuntime()).
		WithEventFilter(resource.DesiredStateChanged()).
		For(&v1alpha1.AccountsSigningKeys{}).
		Complete(ratelimiter.NewReconciler(name, r, o.GlobalRateLimiter))
}

type connector struct {
	kube         client.Client
	usage        *resource.ProviderConfigUsageTracker
	newServiceFn func(creds []byte) (*twilio.Client, error)
}

// Connect tracks the ProviderConfig usage, reads the (Cluster)ProviderConfig
// the resource names, extracts its credentials and forms a client from them.
func (c *connector) Connect(ctx context.Context, cr *v1alpha1.AccountsSigningKeys) (managed.TypedExternalClient[*v1alpha1.AccountsSigningKeys], error) {
	if err := c.usage.Track(ctx, cr); err != nil {
		return nil, errors.Wrap(err, errTrackPCUsage)
	}

	var cd apisv1alpha1.ProviderCredentials

	ref := cr.GetProviderConfigReference()

	switch ref.Kind {
	case "ProviderConfig":
		pc := &apisv1alpha1.ProviderConfig{}
		if err := c.kube.Get(ctx, types.NamespacedName{Name: ref.Name, Namespace: cr.GetNamespace()}, pc); err != nil {
			return nil, errors.Wrap(err, errGetPC)
		}
		cd = pc.Spec.Credentials
	case "ClusterProviderConfig":
		cpc := &apisv1alpha1.ClusterProviderConfig{}
		if err := c.kube.Get(ctx, types.NamespacedName{Name: ref.Name}, cpc); err != nil {
			return nil, errors.Wrap(err, errGetCPC)
		}
		cd = cpc.Spec.Credentials
	default:
		return nil, errors.Errorf("unsupported provider config kind: %s", ref.Kind)
	}

	data, err := resource.CommonCredentialExtractor(ctx, cd.Source, c.kube, cd.CommonCredentialSelectors)
	if err != nil {
		return nil, errors.Wrap(err, errGetCreds)
	}

	svc, err := c.newServiceFn(data)
	if err != nil {
		return nil, errors.Wrap(err, errNewClient)
	}

	return &external{service: svc}, nil
}

type external struct {
	service *twilio.Client
}

// createParams projects spec.forProvider onto the create request.
//
// Every field of a twilio-go params struct is a pointer and every one has a
// setter, so an unset optional field is simply never set -- which matters
// because Twilio reads an empty string as an instruction to CLEAR a field
// rather than as "no opinion".
func createParams(cr *v1alpha1.AccountsSigningKeys) *twiliogo.CreateNewSigningKeyParams {
	params := &twiliogo.CreateNewSigningKeyParams{}

	if twilio.Set(cr.Spec.ForProvider.PathAccountSid) {
		params.SetPathAccountSid(cr.Spec.ForProvider.PathAccountSid)
	}
	if twilio.Set(cr.Spec.ForProvider.FriendlyName) {
		params.SetFriendlyName(cr.Spec.ForProvider.FriendlyName)
	}

	return params
}

// updateParams projects spec.forProvider onto the update request. The update
// takes its own parameter set, which is not always the create's -- see
// x-update-after-create in the generator.
func updateParams(cr *v1alpha1.AccountsSigningKeys) *twiliogo.UpdateSigningKeyParams {
	params := &twiliogo.UpdateSigningKeyParams{}

	if twilio.Set(cr.Spec.ForProvider.PathAccountSid) {
		params.SetPathAccountSid(cr.Spec.ForProvider.PathAccountSid)
	}
	if twilio.Set(cr.Spec.ForProvider.FriendlyName) {
		params.SetFriendlyName(cr.Spec.ForProvider.FriendlyName)
	}

	return params
}

// upToDate compares only the fields the API answers under the same name and
// the same shape. Twilio TAKES `FriendlyName` and ANSWERS `friendly_name`, so
// the pairing is done by the generator through the same snake_case function
// that produced the response names -- compared by Go field name, nothing would
// pair and this would return true for every resource, for ever.
//
// A field the API does not echo back -- a status callback URL, a password, a
// digit string it acts on rather than stores -- cannot be diffed without
// reporting drift on every reconcile, so it is left alone.
func upToDate(cr *v1alpha1.AccountsSigningKeys, observed *v1alpha1.AccountsSigningKeysObservation) bool {
	// Only what the person actually set: an optional field left empty is not a
	// difference from whatever the API chose to put there.
	if twilio.Set(cr.Spec.ForProvider.FriendlyName) && cr.Spec.ForProvider.FriendlyName != observed.FriendlyName {
		return false
	}

	return true
}

func (c *external) Observe(ctx context.Context, cr *v1alpha1.AccountsSigningKeys) (managed.ExternalObservation, error) {
	id := meta.GetExternalName(cr)
	if id == "" {
		// Nothing has been created yet.
		return managed.ExternalObservation{ResourceExists: false}, nil
	}

	r, err := c.service.Rest.Api.FetchSigningKey(id, &twiliogo.FetchSigningKeyParams{})
	if err != nil {
		// ONLY a 404 means it is gone. Any other failure (500, timeout,
		// throttling) must be surfaced -- treating it as "does not exist"
		// would provision a second one and orphan the first.
		if twilio.IsNotFound(err) {
			return managed.ExternalObservation{ResourceExists: false}, nil
		}
		return managed.ExternalObservation{}, errors.Wrap(err, errGet)
	}

	at := v1alpha1.AccountsSigningKeysObservation{}
	if err := twilio.Project(r, &at); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, errObserve)
	}
	cr.Status.AtProvider = at

	if meta.WasDeleted(cr) {
		cr.Status.SetConditions(xpv2.Deleting())
	} else {
		cr.Status.SetConditions(xpv2.Available())
	}

	return managed.ExternalObservation{
		ResourceExists:   true,
		ResourceUpToDate: upToDate(cr, &cr.Status.AtProvider),
	}, nil
}

func (c *external) Create(ctx context.Context, cr *v1alpha1.AccountsSigningKeys) (managed.ExternalCreation, error) {
	cr.Status.SetConditions(xpv2.Creating())

	r, err := c.service.Rest.Api.CreateNewSigningKey(createParams(cr))
	if err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, errCreate)
	}

	if r.Sid == nil || *r.Sid == "" {
		return managed.ExternalCreation{}, errors.New(errNoID)
	}

	meta.SetExternalName(cr, (*r.Sid))

	at := v1alpha1.AccountsSigningKeysObservation{}
	if err := twilio.Project(r, &at); err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, errObserve)
	}
	cr.Status.AtProvider = at

	return managed.ExternalCreation{}, nil
}

func (c *external) Update(ctx context.Context, cr *v1alpha1.AccountsSigningKeys) (managed.ExternalUpdate, error) {
	id := meta.GetExternalName(cr)
	if id == "" {
		return managed.ExternalUpdate{}, errors.New(errUpdate)
	}

	r, err := c.service.Rest.Api.UpdateSigningKey(id, updateParams(cr))
	if err != nil {
		return managed.ExternalUpdate{}, errors.Wrap(err, errUpdate)
	}

	at := v1alpha1.AccountsSigningKeysObservation{}
	if err := twilio.Project(r, &at); err != nil {
		return managed.ExternalUpdate{}, errors.Wrap(err, errObserve)
	}
	cr.Status.AtProvider = at

	return managed.ExternalUpdate{}, nil
}

func (c *external) Delete(ctx context.Context, cr *v1alpha1.AccountsSigningKeys) (managed.ExternalDelete, error) {
	cr.Status.SetConditions(xpv2.Deleting())

	id := meta.GetExternalName(cr)
	if id == "" {
		// Never created; nothing to destroy.
		return managed.ExternalDelete{}, nil
	}

	// A 404 means someone else already did it, which is success as far as
	// reconciliation is concerned.
	if err := c.service.Rest.Api.DeleteSigningKey(id, &twiliogo.DeleteSigningKeyParams{}); err != nil && !twilio.IsNotFound(err) {
		return managed.ExternalDelete{}, errors.Wrap(err, errDelete)
	}

	return managed.ExternalDelete{}, nil
}

func (c *external) Disconnect(_ context.Context) error {
	return nil
}
