// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Kind{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AccountsApplicationsParameters are the configurable fields of a AccountsApplications.
//
// These are the parameters of the create operation (CreateApplication), plus any the
// update accepts and the create does not. The fields are spelled the way
// Twilio TAKES them -- PascalCase -- because that is the name the request
// carries; status.atProvider spells the same values the way Twilio ANSWERS
// them, in snake_case. Nothing translates between the two, so nothing can
// drift out of a translation layer.
type AccountsApplicationsParameters struct {
	// PathAccountSid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that will create the resource.
	// +optional
	PathAccountSid string `json:"PathAccountSid,omitempty"`
	// ApiVersion The API version to use to start a new TwiML session. Can be: `2010-04-01` or `2008-08-01`. The default value is the account's default API version.
	// +optional
	ApiVersion string `json:"ApiVersion,omitempty"`
	// VoiceUrl The URL we should call when the phone number assigned to this application receives a call.
	// +optional
	VoiceUrl string `json:"VoiceUrl,omitempty"`
	// VoiceMethod The HTTP method we should use to call `voice_url`. Can be: `GET` or `POST`.
	// +optional
	VoiceMethod string `json:"VoiceMethod,omitempty"`
	// VoiceFallbackUrl The URL that we should call when an error occurs retrieving or executing the TwiML requested by `url`.
	// +optional
	VoiceFallbackUrl string `json:"VoiceFallbackUrl,omitempty"`
	// VoiceFallbackMethod The HTTP method we should use to call `voice_fallback_url`. Can be: `GET` or `POST`.
	// +optional
	VoiceFallbackMethod string `json:"VoiceFallbackMethod,omitempty"`
	// StatusCallback The URL we should call using the `status_callback_method` to send status information to your application.
	// +optional
	StatusCallback string `json:"StatusCallback,omitempty"`
	// StatusCallbackMethod The HTTP method we should use to call `status_callback`. Can be: `GET` or `POST`.
	// +optional
	StatusCallbackMethod string `json:"StatusCallbackMethod,omitempty"`
	// VoiceCallerIdLookup Whether we should look up the caller's caller-ID name from the CNAM database (additional charges apply). Can be: `true` or `false`.
	// +optional
	VoiceCallerIdLookup bool `json:"VoiceCallerIdLookup,omitempty"`
	// SmsUrl The URL we should call when the phone number receives an incoming SMS message.
	// +optional
	SmsUrl string `json:"SmsUrl,omitempty"`
	// SmsMethod The HTTP method we should use to call `sms_url`. Can be: `GET` or `POST`.
	// +optional
	SmsMethod string `json:"SmsMethod,omitempty"`
	// SmsFallbackUrl The URL that we should call when an error occurs while retrieving or executing the TwiML from `sms_url`.
	// +optional
	SmsFallbackUrl string `json:"SmsFallbackUrl,omitempty"`
	// SmsFallbackMethod The HTTP method we should use to call `sms_fallback_url`. Can be: `GET` or `POST`.
	// +optional
	SmsFallbackMethod string `json:"SmsFallbackMethod,omitempty"`
	// SmsStatusCallback The URL we should call using a POST method to send status information about SMS messages sent by the application.
	// +optional
	SmsStatusCallback string `json:"SmsStatusCallback,omitempty"`
	// MessageStatusCallback The URL we should call using a POST method to send message status information to your application.
	// +optional
	MessageStatusCallback string `json:"MessageStatusCallback,omitempty"`
	// FriendlyName A descriptive string that you create to describe the new application. It can be up to 64 characters long.
	// +optional
	FriendlyName string `json:"FriendlyName,omitempty"`
	// PublicApplicationConnectEnabled Whether to allow other Twilio accounts to dial this applicaton using Dial verb. Can be: `true` or `false`.
	// +optional
	PublicApplicationConnectEnabled bool `json:"PublicApplicationConnectEnabled,omitempty"`
}

// AccountsApplicationsObservation are the observable fields of a AccountsApplications.
//
// These are the properties of what the read (FetchApplication) answers -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AccountsApplicationsObservation struct {
	AccountSid                      string `json:"account_sid,omitempty"`
	ApiVersion                      string `json:"api_version,omitempty"`
	DateCreated                     string `json:"date_created,omitempty"`
	DateUpdated                     string `json:"date_updated,omitempty"`
	FriendlyName                    string `json:"friendly_name,omitempty"`
	MessageStatusCallback           string `json:"message_status_callback,omitempty"`
	Sid                             string `json:"sid,omitempty"`
	SmsFallbackMethod               string `json:"sms_fallback_method,omitempty"`
	SmsFallbackUrl                  string `json:"sms_fallback_url,omitempty"`
	SmsMethod                       string `json:"sms_method,omitempty"`
	SmsStatusCallback               string `json:"sms_status_callback,omitempty"`
	SmsUrl                          string `json:"sms_url,omitempty"`
	StatusCallback                  string `json:"status_callback,omitempty"`
	StatusCallbackMethod            string `json:"status_callback_method,omitempty"`
	Uri                             string `json:"uri,omitempty"`
	VoiceCallerIdLookup             bool   `json:"voice_caller_id_lookup,omitempty"`
	VoiceFallbackMethod             string `json:"voice_fallback_method,omitempty"`
	VoiceFallbackUrl                string `json:"voice_fallback_url,omitempty"`
	VoiceMethod                     string `json:"voice_method,omitempty"`
	VoiceUrl                        string `json:"voice_url,omitempty"`
	PublicApplicationConnectEnabled bool   `json:"public_application_connect_enabled,omitempty"`
}

// A AccountsApplicationsSpec defines the desired state of a AccountsApplications.
type AccountsApplicationsSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AccountsApplicationsParameters `json:"forProvider"`
}

// A AccountsApplicationsStatus represents the observed state of a AccountsApplications.
type AccountsApplicationsStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AccountsApplicationsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AccountsApplications is a managed Twilio resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twilio}
type AccountsApplications struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AccountsApplicationsSpec   `json:"spec"`
	Status AccountsApplicationsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountsApplicationsList contains a list of AccountsApplications
type AccountsApplicationsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountsApplications `json:"items"`
}

// AccountsApplications type metadata.
var (
	AccountsApplicationsKind             = reflect.TypeOf(AccountsApplications{}).Name()
	AccountsApplicationsGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountsApplicationsKind}.String()
	AccountsApplicationsKindAPIVersion   = AccountsApplicationsKind + "." + SchemeGroupVersion.String()
	AccountsApplicationsGroupVersionKind = SchemeGroupVersion.WithKind(AccountsApplicationsKind)
)

func init() {
	SchemeBuilder.Register(&AccountsApplications{}, &AccountsApplicationsList{})
}
