//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsApplications) DeepCopyInto(out *AccountsApplications) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsApplications.
func (in *AccountsApplications) DeepCopy() *AccountsApplications {
	if in == nil {
		return nil
	}
	out := new(AccountsApplications)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsApplications) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsApplicationsList) DeepCopyInto(out *AccountsApplicationsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccountsApplications, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsApplicationsList.
func (in *AccountsApplicationsList) DeepCopy() *AccountsApplicationsList {
	if in == nil {
		return nil
	}
	out := new(AccountsApplicationsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsApplicationsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsApplicationsObservation) DeepCopyInto(out *AccountsApplicationsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsApplicationsObservation.
func (in *AccountsApplicationsObservation) DeepCopy() *AccountsApplicationsObservation {
	if in == nil {
		return nil
	}
	out := new(AccountsApplicationsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsApplicationsParameters) DeepCopyInto(out *AccountsApplicationsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsApplicationsParameters.
func (in *AccountsApplicationsParameters) DeepCopy() *AccountsApplicationsParameters {
	if in == nil {
		return nil
	}
	out := new(AccountsApplicationsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsApplicationsSpec) DeepCopyInto(out *AccountsApplicationsSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsApplicationsSpec.
func (in *AccountsApplicationsSpec) DeepCopy() *AccountsApplicationsSpec {
	if in == nil {
		return nil
	}
	out := new(AccountsApplicationsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsApplicationsStatus) DeepCopyInto(out *AccountsApplicationsStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsApplicationsStatus.
func (in *AccountsApplicationsStatus) DeepCopy() *AccountsApplicationsStatus {
	if in == nil {
		return nil
	}
	out := new(AccountsApplicationsStatus)
	in.DeepCopyInto(out)
	return out
}
