// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accounts_conferences_participants

import (
	"context"

	"github.com/crossplane/crossplane-runtime/v2/pkg/controller"
	"github.com/crossplane/crossplane-runtime/v2/pkg/errors"
	"github.com/crossplane/crossplane-runtime/v2/pkg/event"
	"github.com/crossplane/crossplane-runtime/v2/pkg/feature"
	"github.com/crossplane/crossplane-runtime/v2/pkg/meta"
	"github.com/crossplane/crossplane-runtime/v2/pkg/ratelimiter"
	"github.com/crossplane/crossplane-runtime/v2/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	"github.com/crossplane/crossplane-runtime/v2/pkg/statemetrics"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"

	twiliogo "github.com/twilio/twilio-go/rest/api/v2010"

	"github.com/n-at-han-k/crossplane-provider-twilio/apis/accounts_conferences_participants/v1alpha1"
	apisv1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/v1alpha1"
	"github.com/n-at-han-k/crossplane-provider-twilio/internal/clients/twilio"
)

const (
	errTrackPCUsage = "cannot track ProviderConfig usage"
	errGetPC        = "cannot get ProviderConfig"
	errGetCPC       = "cannot get ClusterProviderConfig"
	errGetCreds     = "cannot get credentials"
	errNewClient    = "cannot create new Service"

	errGet     = "cannot get Twilio accountsconferencesparticipants"
	errCreate  = "cannot create Twilio accountsconferencesparticipants"
	errUpdate  = "cannot update Twilio accountsconferencesparticipants"
	errDelete  = "cannot delete Twilio accountsconferencesparticipants"
	errObserve = "cannot project the Twilio accountsconferencesparticipants onto status.atProvider"

	// errNoID guards the one failure mode that silently leaks a resource: the
	// create succeeds but the answer carries no identifier. Setting an empty
	// external name would make every later Observe report ResourceExists:
	// false and create another one, for ever.
	errNoID = "Twilio returned no accountsconferencesparticipants identifier from create; refusing to record an empty external name (one may have been created and needs manual cleanup)"
)

// newService builds the API client from the extracted credentials.
var newService = func(creds []byte) (*twilio.Client, error) {
	return twilio.NewClientFromCredentials(creds)
}

// SetupGated adds a controller that reconciles AccountsConferencesParticipants managed resources with safe-start support.
func SetupGated(mgr ctrl.Manager, o controller.Options) error {
	o.Gate.Register(func() {
		if err := Setup(mgr, o); err != nil {
			panic(errors.Wrap(err, "cannot setup AccountsConferencesParticipants controller"))
		}
	}, v1alpha1.AccountsConferencesParticipantsGroupVersionKind)
	return nil
}

// Setup adds a controller that reconciles AccountsConferencesParticipants managed resources.
func Setup(mgr ctrl.Manager, o controller.Options) error {
	name := managed.ControllerName(v1alpha1.AccountsConferencesParticipantsGroupKind)

	opts := []managed.ReconcilerOption{
		managed.WithTypedExternalConnector[*v1alpha1.AccountsConferencesParticipants](&connector{
			kube:         mgr.GetClient(),
			usage:        resource.NewProviderConfigUsageTracker(mgr.GetClient(), &apisv1alpha1.ProviderConfigUsage{}),
			newServiceFn: newService,
		}),
		managed.WithLogger(o.Logger.WithValues("controller", name)),
		managed.WithPollInterval(o.PollInterval),
		managed.WithRecorder(event.NewAPIRecorder(mgr.GetEventRecorderFor(name))), //nolint:staticcheck // Crossplane has not moved to the new events API yet.
	}

	if o.Features.Enabled(feature.EnableBetaManagementPolicies) {
		opts = append(opts, managed.WithManagementPolicies())
	}

	if o.Features.Enabled(feature.EnableAlphaChangeLogs) {
		opts = append(opts, managed.WithChangeLogger(o.ChangeLogOptions.ChangeLogger))
	}

	if o.MetricOptions != nil {
		opts = append(opts, managed.WithMetricRecorder(o.MetricOptions.MRMetrics))
	}

	if o.MetricOptions != nil && o.MetricOptions.MRStateMetrics != nil {
		stateMetricsRecorder := statemetrics.NewMRStateRecorder(
			mgr.GetClient(), o.Logger, o.MetricOptions.MRStateMetrics, &v1alpha1.AccountsConferencesParticipantsList{}, o.MetricOptions.PollStateMetricInterval,
		)
		if err := mgr.Add(stateMetricsRecorder); err != nil {
			return errors.Wrap(err, "cannot register MR state metrics recorder for kind v1alpha1.AccountsConferencesParticipantsList")
		}
	}

	r := managed.NewReconciler(mgr, resource.ManagedKind(v1alpha1.AccountsConferencesParticipantsGroupVersionKind), opts...)

	return ctrl.NewControllerManagedBy(mgr).
		Named(name).
		WithOptions(o.ForControllerRuntime()).
		WithEventFilter(resource.DesiredStateChanged()).
		For(&v1alpha1.AccountsConferencesParticipants{}).
		Complete(ratelimiter.NewReconciler(name, r, o.GlobalRateLimiter))
}

type connector struct {
	kube         client.Client
	usage        *resource.ProviderConfigUsageTracker
	newServiceFn func(creds []byte) (*twilio.Client, error)
}

// Connect tracks the ProviderConfig usage, reads the (Cluster)ProviderConfig
// the resource names, extracts its credentials and forms a client from them.
func (c *connector) Connect(ctx context.Context, cr *v1alpha1.AccountsConferencesParticipants) (managed.TypedExternalClient[*v1alpha1.AccountsConferencesParticipants], error) {
	if err := c.usage.Track(ctx, cr); err != nil {
		return nil, errors.Wrap(err, errTrackPCUsage)
	}

	var cd apisv1alpha1.ProviderCredentials

	ref := cr.GetProviderConfigReference()

	switch ref.Kind {
	case "ProviderConfig":
		pc := &apisv1alpha1.ProviderConfig{}
		if err := c.kube.Get(ctx, types.NamespacedName{Name: ref.Name, Namespace: cr.GetNamespace()}, pc); err != nil {
			return nil, errors.Wrap(err, errGetPC)
		}
		cd = pc.Spec.Credentials
	case "ClusterProviderConfig":
		cpc := &apisv1alpha1.ClusterProviderConfig{}
		if err := c.kube.Get(ctx, types.NamespacedName{Name: ref.Name}, cpc); err != nil {
			return nil, errors.Wrap(err, errGetCPC)
		}
		cd = cpc.Spec.Credentials
	default:
		return nil, errors.Errorf("unsupported provider config kind: %s", ref.Kind)
	}

	data, err := resource.CommonCredentialExtractor(ctx, cd.Source, c.kube, cd.CommonCredentialSelectors)
	if err != nil {
		return nil, errors.Wrap(err, errGetCreds)
	}

	svc, err := c.newServiceFn(data)
	if err != nil {
		return nil, errors.Wrap(err, errNewClient)
	}

	return &external{service: svc}, nil
}

type external struct {
	service *twilio.Client
}

// createParams projects spec.forProvider onto the create request.
//
// Every field of a twilio-go params struct is a pointer and every one has a
// setter, so an unset optional field is simply never set -- which matters
// because Twilio reads an empty string as an instruction to CLEAR a field
// rather than as "no opinion".
func createParams(cr *v1alpha1.AccountsConferencesParticipants) *twiliogo.CreateParticipantParams {
	params := &twiliogo.CreateParticipantParams{}

	params.SetFrom(cr.Spec.ForProvider.From)
	params.SetTo(cr.Spec.ForProvider.To)
	if twilio.Set(cr.Spec.ForProvider.PathAccountSid) {
		params.SetPathAccountSid(cr.Spec.ForProvider.PathAccountSid)
	}
	if twilio.Set(cr.Spec.ForProvider.StatusCallback) {
		params.SetStatusCallback(cr.Spec.ForProvider.StatusCallback)
	}
	if twilio.Set(cr.Spec.ForProvider.StatusCallbackMethod) {
		params.SetStatusCallbackMethod(cr.Spec.ForProvider.StatusCallbackMethod)
	}
	if twilio.Set(cr.Spec.ForProvider.StatusCallbackEvent) {
		params.SetStatusCallbackEvent(cr.Spec.ForProvider.StatusCallbackEvent)
	}
	if twilio.Set(cr.Spec.ForProvider.Label) {
		params.SetLabel(cr.Spec.ForProvider.Label)
	}
	if twilio.Set(cr.Spec.ForProvider.Timeout) {
		params.SetTimeout(cr.Spec.ForProvider.Timeout)
	}
	if twilio.Set(cr.Spec.ForProvider.Record) {
		params.SetRecord(cr.Spec.ForProvider.Record)
	}
	if twilio.Set(cr.Spec.ForProvider.Muted) {
		params.SetMuted(cr.Spec.ForProvider.Muted)
	}
	if twilio.Set(cr.Spec.ForProvider.Beep) {
		params.SetBeep(cr.Spec.ForProvider.Beep)
	}
	if twilio.Set(cr.Spec.ForProvider.StartConferenceOnEnter) {
		params.SetStartConferenceOnEnter(cr.Spec.ForProvider.StartConferenceOnEnter)
	}
	if twilio.Set(cr.Spec.ForProvider.EndConferenceOnExit) {
		params.SetEndConferenceOnExit(cr.Spec.ForProvider.EndConferenceOnExit)
	}
	if twilio.Set(cr.Spec.ForProvider.WaitUrl) {
		params.SetWaitUrl(cr.Spec.ForProvider.WaitUrl)
	}
	if twilio.Set(cr.Spec.ForProvider.WaitMethod) {
		params.SetWaitMethod(cr.Spec.ForProvider.WaitMethod)
	}
	if twilio.Set(cr.Spec.ForProvider.EarlyMedia) {
		params.SetEarlyMedia(cr.Spec.ForProvider.EarlyMedia)
	}
	if twilio.Set(cr.Spec.ForProvider.MaxParticipants) {
		params.SetMaxParticipants(cr.Spec.ForProvider.MaxParticipants)
	}
	if twilio.Set(cr.Spec.ForProvider.ConferenceRecord) {
		params.SetConferenceRecord(cr.Spec.ForProvider.ConferenceRecord)
	}
	if twilio.Set(cr.Spec.ForProvider.ConferenceTrim) {
		params.SetConferenceTrim(cr.Spec.ForProvider.ConferenceTrim)
	}
	if twilio.Set(cr.Spec.ForProvider.ConferenceStatusCallback) {
		params.SetConferenceStatusCallback(cr.Spec.ForProvider.ConferenceStatusCallback)
	}
	if twilio.Set(cr.Spec.ForProvider.ConferenceStatusCallbackMethod) {
		params.SetConferenceStatusCallbackMethod(cr.Spec.ForProvider.ConferenceStatusCallbackMethod)
	}
	if twilio.Set(cr.Spec.ForProvider.ConferenceStatusCallbackEvent) {
		params.SetConferenceStatusCallbackEvent(cr.Spec.ForProvider.ConferenceStatusCallbackEvent)
	}
	if twilio.Set(cr.Spec.ForProvider.RecordingChannels) {
		params.SetRecordingChannels(cr.Spec.ForProvider.RecordingChannels)
	}
	if twilio.Set(cr.Spec.ForProvider.RecordingStatusCallback) {
		params.SetRecordingStatusCallback(cr.Spec.ForProvider.RecordingStatusCallback)
	}
	if twilio.Set(cr.Spec.ForProvider.RecordingStatusCallbackMethod) {
		params.SetRecordingStatusCallbackMethod(cr.Spec.ForProvider.RecordingStatusCallbackMethod)
	}
	if twilio.Set(cr.Spec.ForProvider.SipAuthUsername) {
		params.SetSipAuthUsername(cr.Spec.ForProvider.SipAuthUsername)
	}
	if twilio.Set(cr.Spec.ForProvider.SipAuthPassword) {
		params.SetSipAuthPassword(cr.Spec.ForProvider.SipAuthPassword)
	}
	if twilio.Set(cr.Spec.ForProvider.Region) {
		params.SetRegion(cr.Spec.ForProvider.Region)
	}
	if twilio.Set(cr.Spec.ForProvider.ConferenceRecordingStatusCallback) {
		params.SetConferenceRecordingStatusCallback(cr.Spec.ForProvider.ConferenceRecordingStatusCallback)
	}
	if twilio.Set(cr.Spec.ForProvider.ConferenceRecordingStatusCallbackMethod) {
		params.SetConferenceRecordingStatusCallbackMethod(cr.Spec.ForProvider.ConferenceRecordingStatusCallbackMethod)
	}
	if twilio.Set(cr.Spec.ForProvider.RecordingStatusCallbackEvent) {
		params.SetRecordingStatusCallbackEvent(cr.Spec.ForProvider.RecordingStatusCallbackEvent)
	}
	if twilio.Set(cr.Spec.ForProvider.ConferenceRecordingStatusCallbackEvent) {
		params.SetConferenceRecordingStatusCallbackEvent(cr.Spec.ForProvider.ConferenceRecordingStatusCallbackEvent)
	}
	if twilio.Set(cr.Spec.ForProvider.Coaching) {
		params.SetCoaching(cr.Spec.ForProvider.Coaching)
	}
	if twilio.Set(cr.Spec.ForProvider.CallSidToCoach) {
		params.SetCallSidToCoach(cr.Spec.ForProvider.CallSidToCoach)
	}
	if twilio.Set(cr.Spec.ForProvider.JitterBufferSize) {
		params.SetJitterBufferSize(cr.Spec.ForProvider.JitterBufferSize)
	}
	if twilio.Set(cr.Spec.ForProvider.Byoc) {
		params.SetByoc(cr.Spec.ForProvider.Byoc)
	}
	if twilio.Set(cr.Spec.ForProvider.CallerId) {
		params.SetCallerId(cr.Spec.ForProvider.CallerId)
	}
	if twilio.Set(cr.Spec.ForProvider.CallReason) {
		params.SetCallReason(cr.Spec.ForProvider.CallReason)
	}
	if twilio.Set(cr.Spec.ForProvider.RecordingTrack) {
		params.SetRecordingTrack(cr.Spec.ForProvider.RecordingTrack)
	}
	if twilio.Set(cr.Spec.ForProvider.RecordingConfigurationId) {
		params.SetRecordingConfigurationId(cr.Spec.ForProvider.RecordingConfigurationId)
	}
	if twilio.Set(cr.Spec.ForProvider.TimeLimit) {
		params.SetTimeLimit(cr.Spec.ForProvider.TimeLimit)
	}
	if twilio.Set(cr.Spec.ForProvider.MachineDetection) {
		params.SetMachineDetection(cr.Spec.ForProvider.MachineDetection)
	}
	if twilio.Set(cr.Spec.ForProvider.MachineDetectionTimeout) {
		params.SetMachineDetectionTimeout(cr.Spec.ForProvider.MachineDetectionTimeout)
	}
	if twilio.Set(cr.Spec.ForProvider.MachineDetectionSpeechThreshold) {
		params.SetMachineDetectionSpeechThreshold(cr.Spec.ForProvider.MachineDetectionSpeechThreshold)
	}
	if twilio.Set(cr.Spec.ForProvider.MachineDetectionSpeechEndThreshold) {
		params.SetMachineDetectionSpeechEndThreshold(cr.Spec.ForProvider.MachineDetectionSpeechEndThreshold)
	}
	if twilio.Set(cr.Spec.ForProvider.MachineDetectionSilenceTimeout) {
		params.SetMachineDetectionSilenceTimeout(cr.Spec.ForProvider.MachineDetectionSilenceTimeout)
	}
	if twilio.Set(cr.Spec.ForProvider.AmdStatusCallback) {
		params.SetAmdStatusCallback(cr.Spec.ForProvider.AmdStatusCallback)
	}
	if twilio.Set(cr.Spec.ForProvider.AmdStatusCallbackMethod) {
		params.SetAmdStatusCallbackMethod(cr.Spec.ForProvider.AmdStatusCallbackMethod)
	}
	if twilio.Set(cr.Spec.ForProvider.Trim) {
		params.SetTrim(cr.Spec.ForProvider.Trim)
	}
	if twilio.Set(cr.Spec.ForProvider.CallToken) {
		params.SetCallToken(cr.Spec.ForProvider.CallToken)
	}
	if twilio.Set(cr.Spec.ForProvider.Passports) {
		params.SetPassports(cr.Spec.ForProvider.Passports)
	}
	if twilio.Set(cr.Spec.ForProvider.ClientNotificationUrl) {
		params.SetClientNotificationUrl(cr.Spec.ForProvider.ClientNotificationUrl)
	}
	if twilio.Set(cr.Spec.ForProvider.CallerDisplayName) {
		params.SetCallerDisplayName(cr.Spec.ForProvider.CallerDisplayName)
	}
	if twilio.Set(cr.Spec.ForProvider.EmergencyCallerPosition) {
		params.SetEmergencyCallerPosition(cr.Spec.ForProvider.EmergencyCallerPosition)
	}
	if twilio.Set(cr.Spec.ForProvider.EmergencyCallerLocation) {
		params.SetEmergencyCallerLocation(cr.Spec.ForProvider.EmergencyCallerLocation)
	}
	if twilio.Set(cr.Spec.ForProvider.EmergencyName) {
		params.SetEmergencyName(cr.Spec.ForProvider.EmergencyName)
	}
	if twilio.Set(cr.Spec.ForProvider.EmergencyAddress) {
		params.SetEmergencyAddress(cr.Spec.ForProvider.EmergencyAddress)
	}
	if twilio.Set(cr.Spec.ForProvider.EmergencyZipCode) {
		params.SetEmergencyZipCode(cr.Spec.ForProvider.EmergencyZipCode)
	}
	if twilio.Set(cr.Spec.ForProvider.EmergencyCity) {
		params.SetEmergencyCity(cr.Spec.ForProvider.EmergencyCity)
	}
	if twilio.Set(cr.Spec.ForProvider.EmergencyState) {
		params.SetEmergencyState(cr.Spec.ForProvider.EmergencyState)
	}
	if twilio.Set(cr.Spec.ForProvider.EmergencyCountry) {
		params.SetEmergencyCountry(cr.Spec.ForProvider.EmergencyCountry)
	}

	return params
}

// updateParams projects spec.forProvider onto the update request. The update
// takes its own parameter set, which is not always the create's -- see
// x-update-after-create in the generator.
func updateParams(cr *v1alpha1.AccountsConferencesParticipants) *twiliogo.UpdateParticipantParams {
	params := &twiliogo.UpdateParticipantParams{}

	if twilio.Set(cr.Spec.ForProvider.PathAccountSid) {
		params.SetPathAccountSid(cr.Spec.ForProvider.PathAccountSid)
	}
	if twilio.Set(cr.Spec.ForProvider.Muted) {
		params.SetMuted(cr.Spec.ForProvider.Muted)
	}
	if twilio.Set(cr.Spec.ForProvider.Hold) {
		params.SetHold(cr.Spec.ForProvider.Hold)
	}
	if twilio.Set(cr.Spec.ForProvider.HoldUrl) {
		params.SetHoldUrl(cr.Spec.ForProvider.HoldUrl)
	}
	if twilio.Set(cr.Spec.ForProvider.HoldMethod) {
		params.SetHoldMethod(cr.Spec.ForProvider.HoldMethod)
	}
	if twilio.Set(cr.Spec.ForProvider.AnnounceUrl) {
		params.SetAnnounceUrl(cr.Spec.ForProvider.AnnounceUrl)
	}
	if twilio.Set(cr.Spec.ForProvider.AnnounceMethod) {
		params.SetAnnounceMethod(cr.Spec.ForProvider.AnnounceMethod)
	}
	if twilio.Set(cr.Spec.ForProvider.WaitUrl) {
		params.SetWaitUrl(cr.Spec.ForProvider.WaitUrl)
	}
	if twilio.Set(cr.Spec.ForProvider.WaitMethod) {
		params.SetWaitMethod(cr.Spec.ForProvider.WaitMethod)
	}
	if twilio.Set(cr.Spec.ForProvider.BeepOnExit) {
		params.SetBeepOnExit(cr.Spec.ForProvider.BeepOnExit)
	}
	if twilio.Set(cr.Spec.ForProvider.EndConferenceOnExit) {
		params.SetEndConferenceOnExit(cr.Spec.ForProvider.EndConferenceOnExit)
	}
	if twilio.Set(cr.Spec.ForProvider.Coaching) {
		params.SetCoaching(cr.Spec.ForProvider.Coaching)
	}
	if twilio.Set(cr.Spec.ForProvider.CallSidToCoach) {
		params.SetCallSidToCoach(cr.Spec.ForProvider.CallSidToCoach)
	}

	return params
}

// upToDate compares only the fields the API answers under the same name and
// the same shape. Twilio TAKES `FriendlyName` and ANSWERS `friendly_name`, so
// the pairing is done by the generator through the same snake_case function
// that produced the response names -- compared by Go field name, nothing would
// pair and this would return true for every resource, for ever.
//
// A field the API does not echo back -- a status callback URL, a password, a
// digit string it acts on rather than stores -- cannot be diffed without
// reporting drift on every reconcile, so it is left alone.
func upToDate(cr *v1alpha1.AccountsConferencesParticipants, observed *v1alpha1.AccountsConferencesParticipantsObservation) bool {
	// Only what the person actually set: an optional field left empty is not a
	// difference from whatever the API chose to put there.
	if twilio.Set(cr.Spec.ForProvider.ConferenceSid) && cr.Spec.ForProvider.ConferenceSid != observed.ConferenceSid {
		return false
	}
	// Only what the person actually set: an optional field left empty is not a
	// difference from whatever the API chose to put there.
	if twilio.Set(cr.Spec.ForProvider.Label) && cr.Spec.ForProvider.Label != observed.Label {
		return false
	}
	// Only what the person actually set: an optional field left empty is not a
	// difference from whatever the API chose to put there.
	if twilio.Set(cr.Spec.ForProvider.Muted) && cr.Spec.ForProvider.Muted != observed.Muted {
		return false
	}
	// Only what the person actually set: an optional field left empty is not a
	// difference from whatever the API chose to put there.
	if twilio.Set(cr.Spec.ForProvider.StartConferenceOnEnter) && cr.Spec.ForProvider.StartConferenceOnEnter != observed.StartConferenceOnEnter {
		return false
	}
	// Only what the person actually set: an optional field left empty is not a
	// difference from whatever the API chose to put there.
	if twilio.Set(cr.Spec.ForProvider.EndConferenceOnExit) && cr.Spec.ForProvider.EndConferenceOnExit != observed.EndConferenceOnExit {
		return false
	}
	// Only what the person actually set: an optional field left empty is not a
	// difference from whatever the API chose to put there.
	if twilio.Set(cr.Spec.ForProvider.Coaching) && cr.Spec.ForProvider.Coaching != observed.Coaching {
		return false
	}
	// Only what the person actually set: an optional field left empty is not a
	// difference from whatever the API chose to put there.
	if twilio.Set(cr.Spec.ForProvider.CallSidToCoach) && cr.Spec.ForProvider.CallSidToCoach != observed.CallSidToCoach {
		return false
	}
	// Only what the person actually set: an optional field left empty is not a
	// difference from whatever the API chose to put there.
	if twilio.Set(cr.Spec.ForProvider.Hold) && cr.Spec.ForProvider.Hold != observed.Hold {
		return false
	}

	return true
}

func (c *external) Observe(ctx context.Context, cr *v1alpha1.AccountsConferencesParticipants) (managed.ExternalObservation, error) {
	id := meta.GetExternalName(cr)
	if id == "" {
		// Nothing has been created yet.
		return managed.ExternalObservation{ResourceExists: false}, nil
	}

	r, err := c.service.Rest.Api.FetchParticipant(cr.Spec.ForProvider.ConferenceSid, id, &twiliogo.FetchParticipantParams{})
	if err != nil {
		// ONLY a 404 means it is gone. Any other failure (500, timeout,
		// throttling) must be surfaced -- treating it as "does not exist"
		// would provision a second one and orphan the first.
		if twilio.IsNotFound(err) {
			return managed.ExternalObservation{ResourceExists: false}, nil
		}
		return managed.ExternalObservation{}, errors.Wrap(err, errGet)
	}

	at := v1alpha1.AccountsConferencesParticipantsObservation{}
	if err := twilio.Project(r, &at); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, errObserve)
	}
	cr.Status.AtProvider = at

	if meta.WasDeleted(cr) {
		cr.Status.SetConditions(xpv2.Deleting())
	} else {
		cr.Status.SetConditions(xpv2.Available())
	}

	return managed.ExternalObservation{
		ResourceExists:   true,
		ResourceUpToDate: upToDate(cr, &cr.Status.AtProvider),
	}, nil
}

func (c *external) Create(ctx context.Context, cr *v1alpha1.AccountsConferencesParticipants) (managed.ExternalCreation, error) {
	cr.Status.SetConditions(xpv2.Creating())

	r, err := c.service.Rest.Api.CreateParticipant(cr.Spec.ForProvider.ConferenceSid, createParams(cr))
	if err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, errCreate)
	}

	if r.CallSid == nil || *r.CallSid == "" {
		return managed.ExternalCreation{}, errors.New(errNoID)
	}

	meta.SetExternalName(cr, (*r.CallSid))

	at := v1alpha1.AccountsConferencesParticipantsObservation{}
	if err := twilio.Project(r, &at); err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, errObserve)
	}
	cr.Status.AtProvider = at

	return managed.ExternalCreation{}, nil
}

func (c *external) Update(ctx context.Context, cr *v1alpha1.AccountsConferencesParticipants) (managed.ExternalUpdate, error) {
	id := meta.GetExternalName(cr)
	if id == "" {
		return managed.ExternalUpdate{}, errors.New(errUpdate)
	}

	r, err := c.service.Rest.Api.UpdateParticipant(cr.Spec.ForProvider.ConferenceSid, id, updateParams(cr))
	if err != nil {
		return managed.ExternalUpdate{}, errors.Wrap(err, errUpdate)
	}

	at := v1alpha1.AccountsConferencesParticipantsObservation{}
	if err := twilio.Project(r, &at); err != nil {
		return managed.ExternalUpdate{}, errors.Wrap(err, errObserve)
	}
	cr.Status.AtProvider = at

	return managed.ExternalUpdate{}, nil
}

func (c *external) Delete(ctx context.Context, cr *v1alpha1.AccountsConferencesParticipants) (managed.ExternalDelete, error) {
	cr.Status.SetConditions(xpv2.Deleting())

	id := meta.GetExternalName(cr)
	if id == "" {
		// Never created; nothing to destroy.
		return managed.ExternalDelete{}, nil
	}

	// A 404 means someone else already did it, which is success as far as
	// reconciliation is concerned.
	if err := c.service.Rest.Api.DeleteParticipant(cr.Spec.ForProvider.ConferenceSid, id, &twiliogo.DeleteParticipantParams{}); err != nil && !twilio.IsNotFound(err) {
		return managed.ExternalDelete{}, errors.Wrap(err, errDelete)
	}

	return managed.ExternalDelete{}, nil
}

func (c *external) Disconnect(_ context.Context) error {
	return nil
}
