// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

// The two tools a mustache template cannot replace, because they need to see
// the Go TYPES rather than the API description: controller-gen writes the
// DeepCopy methods and the CRD manifests, angryjet writes the
// crossplane-runtime methodsets (GetCondition, SetProviderConfigReference...).
//
// `make generate` runs this file.

// Remove existing CRDs
//go:generate rm -rf ../package/crds

// Generate deepcopy methodsets and CRD manifests.
//go:generate go run -tags generate sigs.k8s.io/controller-tools/cmd/controller-gen object:headerFile=../hack/boilerplate.go.txt paths=./... crd:crdVersions=v1,allowDangerousTypes=true output:artifacts:config=../package/crds

// Generate crossplane-runtime methodsets (resource.Claim, etc)
//go:generate go run -tags generate github.com/crossplane/crossplane-tools/cmd/angryjet generate-methodsets --header-file=../hack/boilerplate.go.txt ./...

package apis
