// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

// Package apis contains the Kubernetes API of the Twilio provider.
package apis

import (
	"k8s.io/apimachinery/pkg/runtime"

	accounts_addressesv1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/accounts_addresses/v1alpha1"

	accounts_applicationsv1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/accounts_applications/v1alpha1"

	accounts_callsv1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/accounts_calls/v1alpha1"

	accounts_calls_recordingsv1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/accounts_calls_recordings/v1alpha1"

	accounts_conferences_participantsv1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/accounts_conferences_participants/v1alpha1"

	accounts_incoming_phone_numbersv1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/accounts_incoming_phone_numbers/v1alpha1"

	accounts_incoming_phone_numbers_assigned_add_onsv1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/accounts_incoming_phone_numbers_assigned_add_ons/v1alpha1"

	accounts_keysv1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/accounts_keys/v1alpha1"

	accounts_messagesv1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/accounts_messages/v1alpha1"

	accounts_queuesv1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/accounts_queues/v1alpha1"

	accounts_sip_credential_listsv1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/accounts_sip_credential_lists/v1alpha1"

	accounts_sip_credential_lists_credentialsv1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/accounts_sip_credential_lists_credentials/v1alpha1"

	accounts_sip_domainsv1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/accounts_sip_domains/v1alpha1"

	accounts_sip_domains_auth_calls_credential_list_mappingsv1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/accounts_sip_domains_auth_calls_credential_list_mappings/v1alpha1"

	accounts_sip_domains_auth_calls_ip_access_control_list_mappingsv1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/accounts_sip_domains_auth_calls_ip_access_control_list_mappings/v1alpha1"

	accounts_sip_domains_auth_registrations_credential_list_mappingsv1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/accounts_sip_domains_auth_registrations_credential_list_mappings/v1alpha1"

	accounts_sip_domains_credential_list_mappingsv1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/accounts_sip_domains_credential_list_mappings/v1alpha1"

	accounts_sip_domains_ip_access_control_list_mappingsv1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/accounts_sip_domains_ip_access_control_list_mappings/v1alpha1"

	accounts_sip_ip_access_control_listsv1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/accounts_sip_ip_access_control_lists/v1alpha1"

	accounts_sip_ip_access_control_lists_ip_addressesv1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/accounts_sip_ip_access_control_lists_ip_addresses/v1alpha1"

	accounts_signing_keysv1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/accounts_signing_keys/v1alpha1"

	accounts_usage_triggersv1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/accounts_usage_triggers/v1alpha1"

	twiliov1alpha1 "github.com/n-at-han-k/crossplane-provider-twilio/apis/v1alpha1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to
	// GroupVersionKinds and back.
	AddToSchemes = append(AddToSchemes,
		twiliov1alpha1.SchemeBuilder.AddToScheme,

		accounts_addressesv1alpha1.SchemeBuilder.AddToScheme,

		accounts_applicationsv1alpha1.SchemeBuilder.AddToScheme,

		accounts_callsv1alpha1.SchemeBuilder.AddToScheme,

		accounts_calls_recordingsv1alpha1.SchemeBuilder.AddToScheme,

		accounts_conferences_participantsv1alpha1.SchemeBuilder.AddToScheme,

		accounts_incoming_phone_numbersv1alpha1.SchemeBuilder.AddToScheme,

		accounts_incoming_phone_numbers_assigned_add_onsv1alpha1.SchemeBuilder.AddToScheme,

		accounts_keysv1alpha1.SchemeBuilder.AddToScheme,

		accounts_messagesv1alpha1.SchemeBuilder.AddToScheme,

		accounts_queuesv1alpha1.SchemeBuilder.AddToScheme,

		accounts_sip_credential_listsv1alpha1.SchemeBuilder.AddToScheme,

		accounts_sip_credential_lists_credentialsv1alpha1.SchemeBuilder.AddToScheme,

		accounts_sip_domainsv1alpha1.SchemeBuilder.AddToScheme,

		accounts_sip_domains_auth_calls_credential_list_mappingsv1alpha1.SchemeBuilder.AddToScheme,

		accounts_sip_domains_auth_calls_ip_access_control_list_mappingsv1alpha1.SchemeBuilder.AddToScheme,

		accounts_sip_domains_auth_registrations_credential_list_mappingsv1alpha1.SchemeBuilder.AddToScheme,

		accounts_sip_domains_credential_list_mappingsv1alpha1.SchemeBuilder.AddToScheme,

		accounts_sip_domains_ip_access_control_list_mappingsv1alpha1.SchemeBuilder.AddToScheme,

		accounts_sip_ip_access_control_listsv1alpha1.SchemeBuilder.AddToScheme,

		accounts_sip_ip_access_control_lists_ip_addressesv1alpha1.SchemeBuilder.AddToScheme,

		accounts_signing_keysv1alpha1.SchemeBuilder.AddToScheme,

		accounts_usage_triggersv1alpha1.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
