// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Kind{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AccountsIncomingPhoneNumbersAssignedAddOnsParameters are the configurable fields of a AccountsIncomingPhoneNumbersAssignedAddOns.
//
// These are the parameters of the create operation (CreateIncomingPhoneNumberAssignedAddOn), plus any the
// update accepts and the create does not. The fields are spelled the way
// Twilio TAKES them -- PascalCase -- because that is the name the request
// carries; status.atProvider spells the same values the way Twilio ANSWERS
// them, in snake_case. Nothing translates between the two, so nothing can
// drift out of a translation layer.
type AccountsIncomingPhoneNumbersAssignedAddOnsParameters struct {
	// ResourceSid The SID of the Phone Number to assign the Add-on.
	// +kubebuilder:validation:Required
	ResourceSid string `json:"ResourceSid"`
	// InstalledAddOnSid The SID that identifies the Add-on installation.
	// +kubebuilder:validation:Required
	InstalledAddOnSid string `json:"InstalledAddOnSid"`
	// PathAccountSid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that will create the resource.
	// +optional
	PathAccountSid string `json:"PathAccountSid,omitempty"`
}

// AccountsIncomingPhoneNumbersAssignedAddOnsObservation are the observable fields of a AccountsIncomingPhoneNumbersAssignedAddOns.
//
// These are the properties of what the read (FetchIncomingPhoneNumberAssignedAddOn) answers -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AccountsIncomingPhoneNumbersAssignedAddOnsObservation struct {
	Sid             string `json:"sid,omitempty"`
	AccountSid      string `json:"account_sid,omitempty"`
	ResourceSid     string `json:"resource_sid,omitempty"`
	FriendlyName    string `json:"friendly_name,omitempty"`
	Description     string `json:"description,omitempty"`
	Configuration   string `json:"configuration,omitempty"`
	UniqueName      string `json:"unique_name,omitempty"`
	DateCreated     string `json:"date_created,omitempty"`
	DateUpdated     string `json:"date_updated,omitempty"`
	Uri             string `json:"uri,omitempty"`
	SubresourceUris string `json:"subresource_uris,omitempty"`
}

// A AccountsIncomingPhoneNumbersAssignedAddOnsSpec defines the desired state of a AccountsIncomingPhoneNumbersAssignedAddOns.
type AccountsIncomingPhoneNumbersAssignedAddOnsSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AccountsIncomingPhoneNumbersAssignedAddOnsParameters `json:"forProvider"`
}

// A AccountsIncomingPhoneNumbersAssignedAddOnsStatus represents the observed state of a AccountsIncomingPhoneNumbersAssignedAddOns.
type AccountsIncomingPhoneNumbersAssignedAddOnsStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AccountsIncomingPhoneNumbersAssignedAddOnsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AccountsIncomingPhoneNumbersAssignedAddOns is a managed Twilio resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twilio}
type AccountsIncomingPhoneNumbersAssignedAddOns struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AccountsIncomingPhoneNumbersAssignedAddOnsSpec   `json:"spec"`
	Status AccountsIncomingPhoneNumbersAssignedAddOnsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountsIncomingPhoneNumbersAssignedAddOnsList contains a list of AccountsIncomingPhoneNumbersAssignedAddOns
type AccountsIncomingPhoneNumbersAssignedAddOnsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountsIncomingPhoneNumbersAssignedAddOns `json:"items"`
}

// AccountsIncomingPhoneNumbersAssignedAddOns type metadata.
var (
	AccountsIncomingPhoneNumbersAssignedAddOnsKind             = reflect.TypeOf(AccountsIncomingPhoneNumbersAssignedAddOns{}).Name()
	AccountsIncomingPhoneNumbersAssignedAddOnsGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountsIncomingPhoneNumbersAssignedAddOnsKind}.String()
	AccountsIncomingPhoneNumbersAssignedAddOnsKindAPIVersion   = AccountsIncomingPhoneNumbersAssignedAddOnsKind + "." + SchemeGroupVersion.String()
	AccountsIncomingPhoneNumbersAssignedAddOnsGroupVersionKind = SchemeGroupVersion.WithKind(AccountsIncomingPhoneNumbersAssignedAddOnsKind)
)

func init() {
	SchemeBuilder.Register(&AccountsIncomingPhoneNumbersAssignedAddOns{}, &AccountsIncomingPhoneNumbersAssignedAddOnsList{})
}
