//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsIncomingPhoneNumbersAssignedAddOns) DeepCopyInto(out *AccountsIncomingPhoneNumbersAssignedAddOns) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsIncomingPhoneNumbersAssignedAddOns.
func (in *AccountsIncomingPhoneNumbersAssignedAddOns) DeepCopy() *AccountsIncomingPhoneNumbersAssignedAddOns {
	if in == nil {
		return nil
	}
	out := new(AccountsIncomingPhoneNumbersAssignedAddOns)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsIncomingPhoneNumbersAssignedAddOns) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsIncomingPhoneNumbersAssignedAddOnsList) DeepCopyInto(out *AccountsIncomingPhoneNumbersAssignedAddOnsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccountsIncomingPhoneNumbersAssignedAddOns, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsIncomingPhoneNumbersAssignedAddOnsList.
func (in *AccountsIncomingPhoneNumbersAssignedAddOnsList) DeepCopy() *AccountsIncomingPhoneNumbersAssignedAddOnsList {
	if in == nil {
		return nil
	}
	out := new(AccountsIncomingPhoneNumbersAssignedAddOnsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsIncomingPhoneNumbersAssignedAddOnsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsIncomingPhoneNumbersAssignedAddOnsObservation) DeepCopyInto(out *AccountsIncomingPhoneNumbersAssignedAddOnsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsIncomingPhoneNumbersAssignedAddOnsObservation.
func (in *AccountsIncomingPhoneNumbersAssignedAddOnsObservation) DeepCopy() *AccountsIncomingPhoneNumbersAssignedAddOnsObservation {
	if in == nil {
		return nil
	}
	out := new(AccountsIncomingPhoneNumbersAssignedAddOnsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsIncomingPhoneNumbersAssignedAddOnsParameters) DeepCopyInto(out *AccountsIncomingPhoneNumbersAssignedAddOnsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsIncomingPhoneNumbersAssignedAddOnsParameters.
func (in *AccountsIncomingPhoneNumbersAssignedAddOnsParameters) DeepCopy() *AccountsIncomingPhoneNumbersAssignedAddOnsParameters {
	if in == nil {
		return nil
	}
	out := new(AccountsIncomingPhoneNumbersAssignedAddOnsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsIncomingPhoneNumbersAssignedAddOnsSpec) DeepCopyInto(out *AccountsIncomingPhoneNumbersAssignedAddOnsSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsIncomingPhoneNumbersAssignedAddOnsSpec.
func (in *AccountsIncomingPhoneNumbersAssignedAddOnsSpec) DeepCopy() *AccountsIncomingPhoneNumbersAssignedAddOnsSpec {
	if in == nil {
		return nil
	}
	out := new(AccountsIncomingPhoneNumbersAssignedAddOnsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsIncomingPhoneNumbersAssignedAddOnsStatus) DeepCopyInto(out *AccountsIncomingPhoneNumbersAssignedAddOnsStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsIncomingPhoneNumbersAssignedAddOnsStatus.
func (in *AccountsIncomingPhoneNumbersAssignedAddOnsStatus) DeepCopy() *AccountsIncomingPhoneNumbersAssignedAddOnsStatus {
	if in == nil {
		return nil
	}
	out := new(AccountsIncomingPhoneNumbersAssignedAddOnsStatus)
	in.DeepCopyInto(out)
	return out
}
