// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Kind{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AccountsSIPDomainsParameters are the configurable fields of a AccountsSIPDomains.
//
// These are the parameters of the create operation (CreateSipDomain), plus any the
// update accepts and the create does not. The fields are spelled the way
// Twilio TAKES them -- PascalCase -- because that is the name the request
// carries; status.atProvider spells the same values the way Twilio ANSWERS
// them, in snake_case. Nothing translates between the two, so nothing can
// drift out of a translation layer.
type AccountsSIPDomainsParameters struct {
	// DomainName The unique address you reserve on Twilio to which you route your SIP traffic. Domain names can contain letters, digits, and \\\"-\\\" and must end with `sip.twilio.com`.
	// +kubebuilder:validation:Required
	DomainName string `json:"DomainName"`
	// PathAccountSid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that will create the resource.
	// +optional
	PathAccountSid string `json:"PathAccountSid,omitempty"`
	// FriendlyName A descriptive string that you created to describe the resource. It can be up to 64 characters long.
	// +optional
	FriendlyName string `json:"FriendlyName,omitempty"`
	// VoiceUrl The URL we should when the domain receives a call.
	// +optional
	VoiceUrl string `json:"VoiceUrl,omitempty"`
	// VoiceMethod The HTTP method we should use to call `voice_url`. Can be: `GET` or `POST`.
	// +optional
	VoiceMethod string `json:"VoiceMethod,omitempty"`
	// VoiceFallbackUrl The URL that we should call when an error occurs while retrieving or executing the TwiML from `voice_url`.
	// +optional
	VoiceFallbackUrl string `json:"VoiceFallbackUrl,omitempty"`
	// VoiceFallbackMethod The HTTP method we should use to call `voice_fallback_url`. Can be: `GET` or `POST`.
	// +optional
	VoiceFallbackMethod string `json:"VoiceFallbackMethod,omitempty"`
	// VoiceStatusCallbackUrl The URL that we should call to pass status parameters (such as call ended) to your application.
	// +optional
	VoiceStatusCallbackUrl string `json:"VoiceStatusCallbackUrl,omitempty"`
	// VoiceStatusCallbackMethod The HTTP method we should use to call `voice_status_callback_url`. Can be: `GET` or `POST`.
	// +optional
	VoiceStatusCallbackMethod string `json:"VoiceStatusCallbackMethod,omitempty"`
	// SipRegistration Whether to allow SIP Endpoints to register with the domain to receive calls. Can be `true` or `false`. `true` allows SIP Endpoints to register with the domain to receive calls, `false` does not.
	// +optional
	SipRegistration bool `json:"SipRegistration,omitempty"`
	// EmergencyCallingEnabled Whether emergency calling is enabled for the domain. If enabled, allows emergency calls on the domain from phone numbers with validated addresses.
	// +optional
	EmergencyCallingEnabled bool `json:"EmergencyCallingEnabled,omitempty"`
	// Secure Whether secure SIP is enabled for the domain. If enabled, TLS will be enforced and SRTP will be negotiated on all incoming calls to this sip domain.
	// +optional
	Secure bool `json:"Secure,omitempty"`
	// ByocTrunkSid The SID of the BYOC Trunk(Bring Your Own Carrier) resource that the Sip Domain will be associated with.
	// +optional
	ByocTrunkSid string `json:"ByocTrunkSid,omitempty"`
	// EmergencyCallerSid Whether an emergency caller sid is configured for the domain. If present, this phone number will be used as the callback for the emergency call.
	// +optional
	EmergencyCallerSid string `json:"EmergencyCallerSid,omitempty"`
}

// AccountsSIPDomainsObservation are the observable fields of a AccountsSIPDomains.
//
// These are the properties of what the read (FetchSipDomain) answers -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AccountsSIPDomainsObservation struct {
	AccountSid                string `json:"account_sid,omitempty"`
	ApiVersion                string `json:"api_version,omitempty"`
	AuthType                  string `json:"auth_type,omitempty"`
	DateCreated               string `json:"date_created,omitempty"`
	DateUpdated               string `json:"date_updated,omitempty"`
	DomainName                string `json:"domain_name,omitempty"`
	FriendlyName              string `json:"friendly_name,omitempty"`
	Sid                       string `json:"sid,omitempty"`
	Uri                       string `json:"uri,omitempty"`
	VoiceFallbackMethod       string `json:"voice_fallback_method,omitempty"`
	VoiceFallbackUrl          string `json:"voice_fallback_url,omitempty"`
	VoiceMethod               string `json:"voice_method,omitempty"`
	VoiceStatusCallbackMethod string `json:"voice_status_callback_method,omitempty"`
	VoiceStatusCallbackUrl    string `json:"voice_status_callback_url,omitempty"`
	VoiceUrl                  string `json:"voice_url,omitempty"`
	SubresourceUris           string `json:"subresource_uris,omitempty"`
	SipRegistration           bool   `json:"sip_registration,omitempty"`
	EmergencyCallingEnabled   bool   `json:"emergency_calling_enabled,omitempty"`
	Secure                    bool   `json:"secure,omitempty"`
	ByocTrunkSid              string `json:"byoc_trunk_sid,omitempty"`
	EmergencyCallerSid        string `json:"emergency_caller_sid,omitempty"`
}

// A AccountsSIPDomainsSpec defines the desired state of a AccountsSIPDomains.
type AccountsSIPDomainsSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AccountsSIPDomainsParameters `json:"forProvider"`
}

// A AccountsSIPDomainsStatus represents the observed state of a AccountsSIPDomains.
type AccountsSIPDomainsStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AccountsSIPDomainsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AccountsSIPDomains is a managed Twilio resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twilio}
type AccountsSIPDomains struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AccountsSIPDomainsSpec   `json:"spec"`
	Status AccountsSIPDomainsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountsSIPDomainsList contains a list of AccountsSIPDomains
type AccountsSIPDomainsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountsSIPDomains `json:"items"`
}

// AccountsSIPDomains type metadata.
var (
	AccountsSIPDomainsKind             = reflect.TypeOf(AccountsSIPDomains{}).Name()
	AccountsSIPDomainsGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountsSIPDomainsKind}.String()
	AccountsSIPDomainsKindAPIVersion   = AccountsSIPDomainsKind + "." + SchemeGroupVersion.String()
	AccountsSIPDomainsGroupVersionKind = SchemeGroupVersion.WithKind(AccountsSIPDomainsKind)
)

func init() {
	SchemeBuilder.Register(&AccountsSIPDomains{}, &AccountsSIPDomainsList{})
}
