// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Kind{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AccountsIncomingPhoneNumbersParameters are the configurable fields of a AccountsIncomingPhoneNumbers.
//
// These are the parameters of the create operation (CreateIncomingPhoneNumber), plus any the
// update accepts and the create does not. The fields are spelled the way
// Twilio TAKES them -- PascalCase -- because that is the name the request
// carries; status.atProvider spells the same values the way Twilio ANSWERS
// them, in snake_case. Nothing translates between the two, so nothing can
// drift out of a translation layer.
type AccountsIncomingPhoneNumbersParameters struct {
	// PathAccountSid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that will create the resource.
	// +optional
	PathAccountSid string `json:"PathAccountSid,omitempty"`
	// ApiVersion The API version to use for incoming calls made to the new phone number. The default is `2010-04-01`.
	// +optional
	ApiVersion string `json:"ApiVersion,omitempty"`
	// FriendlyName A descriptive string that you created to describe the new phone number. It can be up to 64 characters long. By default, this is a formatted version of the new phone number.
	// +optional
	FriendlyName string `json:"FriendlyName,omitempty"`
	// SmsApplicationSid The SID of the application that should handle SMS messages sent to the new phone number. If an `sms_application_sid` is present, we ignore all of the `sms_*_url` urls and use those set on the application.
	// +optional
	SmsApplicationSid string `json:"SmsApplicationSid,omitempty"`
	// SmsFallbackMethod The HTTP method that we should use to call `sms_fallback_url`. Can be: `GET` or `POST` and defaults to `POST`.
	// +optional
	SmsFallbackMethod string `json:"SmsFallbackMethod,omitempty"`
	// SmsFallbackUrl The URL that we should call when an error occurs while requesting or executing the TwiML defined by `sms_url`.
	// +optional
	SmsFallbackUrl string `json:"SmsFallbackUrl,omitempty"`
	// SmsMethod The HTTP method that we should use to call `sms_url`. Can be: `GET` or `POST` and defaults to `POST`.
	// +optional
	SmsMethod string `json:"SmsMethod,omitempty"`
	// SmsUrl The URL we should call when the new phone number receives an incoming SMS message.
	// +optional
	SmsUrl string `json:"SmsUrl,omitempty"`
	// StatusCallback The URL we should call using the `status_callback_method` to send status information to your application.
	// +optional
	StatusCallback string `json:"StatusCallback,omitempty"`
	// StatusCallbackMethod The HTTP method we should use to call `status_callback`. Can be: `GET` or `POST` and defaults to `POST`.
	// +optional
	StatusCallbackMethod string `json:"StatusCallbackMethod,omitempty"`
	// VoiceApplicationSid The SID of the application we should use to handle calls to the new phone number. If a `voice_application_sid` is present, we ignore all of the voice urls and use only those set on the application. Setting a `voice_application_sid` will automatically delete your `trunk_sid` and vice versa.
	// +optional
	VoiceApplicationSid string `json:"VoiceApplicationSid,omitempty"`
	// VoiceCallerIdLookup Whether to lookup the caller's name from the CNAM database and post it to your app. Can be: `true` or `false` and defaults to `false`.
	// +optional
	VoiceCallerIdLookup bool `json:"VoiceCallerIdLookup,omitempty"`
	// VoiceFallbackMethod The HTTP method that we should use to call `voice_fallback_url`. Can be: `GET` or `POST` and defaults to `POST`.
	// +optional
	VoiceFallbackMethod string `json:"VoiceFallbackMethod,omitempty"`
	// VoiceFallbackUrl The URL that we should call when an error occurs retrieving or executing the TwiML requested by `url`.
	// +optional
	VoiceFallbackUrl string `json:"VoiceFallbackUrl,omitempty"`
	// VoiceMethod The HTTP method that we should use to call `voice_url`. Can be: `GET` or `POST` and defaults to `POST`.
	// +optional
	VoiceMethod string `json:"VoiceMethod,omitempty"`
	// VoiceUrl The URL that we should call to answer a call to the new phone number. The `voice_url` will not be called if a `voice_application_sid` or a `trunk_sid` is set.
	// +optional
	VoiceUrl string `json:"VoiceUrl,omitempty"`
	// EmergencyStatus
	// +optional
	EmergencyStatus string `json:"EmergencyStatus,omitempty"`
	// EmergencyAddressSid The SID of the emergency address configuration to use for emergency calling from the new phone number.
	// +optional
	EmergencyAddressSid string `json:"EmergencyAddressSid,omitempty"`
	// TrunkSid The SID of the Trunk we should use to handle calls to the new phone number. If a `trunk_sid` is present, we ignore all of the voice urls and voice applications and use only those set on the Trunk. Setting a `trunk_sid` will automatically delete your `voice_application_sid` and vice versa.
	// +optional
	TrunkSid string `json:"TrunkSid,omitempty"`
	// IdentitySid The SID of the Identity resource that we should associate with the new phone number. Some regions require an identity to meet local regulations.
	// +optional
	IdentitySid string `json:"IdentitySid,omitempty"`
	// AddressSid The SID of the Address resource we should associate with the new phone number. Some regions require addresses to meet local regulations.
	// +optional
	AddressSid string `json:"AddressSid,omitempty"`
	// VoiceReceiveMode
	// +optional
	VoiceReceiveMode string `json:"VoiceReceiveMode,omitempty"`
	// BundleSid The SID of the Bundle resource that you associate with the phone number. Some regions require a Bundle to meet local Regulations.
	// +optional
	BundleSid string `json:"BundleSid,omitempty"`
	// PhoneNumber The phone number to purchase specified in [E.164](https://www.twilio.com/docs/glossary/what-e164) format. E.164 phone numbers consist of a + followed by the country code and subscriber number without punctuation characters. For example, +14155551234.
	// +optional
	PhoneNumber string `json:"PhoneNumber,omitempty"`
	// AreaCode The desired area code for your new incoming phone number. Can be any three-digit, US or Canada area code. We will provision an available phone number within this area code for you. **You must provide an `area_code` or a `phone_number`.** (US and Canada only).
	// +optional
	AreaCode string `json:"AreaCode,omitempty"`
	// AccountSid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the IncomingPhoneNumber resource to update. For more information, see [Exchanging Numbers Between Subaccounts](https://www.twilio.com/docs/iam/api/subaccounts#exchanging-numbers).
	// +optional
	AccountSid string `json:"AccountSid,omitempty"`
}

// AccountsIncomingPhoneNumbersObservation are the observable fields of a AccountsIncomingPhoneNumbers.
//
// These are the properties of what the read (FetchIncomingPhoneNumber) answers -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AccountsIncomingPhoneNumbersObservation struct {
	AccountSid             string `json:"account_sid,omitempty"`
	AddressSid             string `json:"address_sid,omitempty"`
	AddressRequirements    string `json:"address_requirements,omitempty"`
	ApiVersion             string `json:"api_version,omitempty"`
	Beta                   bool   `json:"beta,omitempty"`
	Capabilities           string `json:"capabilities,omitempty"`
	DateCreated            string `json:"date_created,omitempty"`
	DateUpdated            string `json:"date_updated,omitempty"`
	FriendlyName           string `json:"friendly_name,omitempty"`
	IdentitySid            string `json:"identity_sid,omitempty"`
	PhoneNumber            string `json:"phone_number,omitempty"`
	Origin                 string `json:"origin,omitempty"`
	Sid                    string `json:"sid,omitempty"`
	SmsApplicationSid      string `json:"sms_application_sid,omitempty"`
	SmsFallbackMethod      string `json:"sms_fallback_method,omitempty"`
	SmsFallbackUrl         string `json:"sms_fallback_url,omitempty"`
	SmsMethod              string `json:"sms_method,omitempty"`
	SmsUrl                 string `json:"sms_url,omitempty"`
	StatusCallback         string `json:"status_callback,omitempty"`
	StatusCallbackMethod   string `json:"status_callback_method,omitempty"`
	TrunkSid               string `json:"trunk_sid,omitempty"`
	Uri                    string `json:"uri,omitempty"`
	VoiceReceiveMode       string `json:"voice_receive_mode,omitempty"`
	VoiceApplicationSid    string `json:"voice_application_sid,omitempty"`
	VoiceCallerIdLookup    bool   `json:"voice_caller_id_lookup,omitempty"`
	VoiceFallbackMethod    string `json:"voice_fallback_method,omitempty"`
	VoiceFallbackUrl       string `json:"voice_fallback_url,omitempty"`
	VoiceMethod            string `json:"voice_method,omitempty"`
	VoiceUrl               string `json:"voice_url,omitempty"`
	EmergencyStatus        string `json:"emergency_status,omitempty"`
	EmergencyAddressSid    string `json:"emergency_address_sid,omitempty"`
	EmergencyAddressStatus string `json:"emergency_address_status,omitempty"`
	BundleSid              string `json:"bundle_sid,omitempty"`
	Status                 string `json:"status,omitempty"`
	Type                   string `json:"type,omitempty"`
}

// A AccountsIncomingPhoneNumbersSpec defines the desired state of a AccountsIncomingPhoneNumbers.
type AccountsIncomingPhoneNumbersSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AccountsIncomingPhoneNumbersParameters `json:"forProvider"`
}

// A AccountsIncomingPhoneNumbersStatus represents the observed state of a AccountsIncomingPhoneNumbers.
type AccountsIncomingPhoneNumbersStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AccountsIncomingPhoneNumbersObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AccountsIncomingPhoneNumbers is a managed Twilio resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twilio}
type AccountsIncomingPhoneNumbers struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AccountsIncomingPhoneNumbersSpec   `json:"spec"`
	Status AccountsIncomingPhoneNumbersStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountsIncomingPhoneNumbersList contains a list of AccountsIncomingPhoneNumbers
type AccountsIncomingPhoneNumbersList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountsIncomingPhoneNumbers `json:"items"`
}

// AccountsIncomingPhoneNumbers type metadata.
var (
	AccountsIncomingPhoneNumbersKind             = reflect.TypeOf(AccountsIncomingPhoneNumbers{}).Name()
	AccountsIncomingPhoneNumbersGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountsIncomingPhoneNumbersKind}.String()
	AccountsIncomingPhoneNumbersKindAPIVersion   = AccountsIncomingPhoneNumbersKind + "." + SchemeGroupVersion.String()
	AccountsIncomingPhoneNumbersGroupVersionKind = SchemeGroupVersion.WithKind(AccountsIncomingPhoneNumbersKind)
)

func init() {
	SchemeBuilder.Register(&AccountsIncomingPhoneNumbers{}, &AccountsIncomingPhoneNumbersList{})
}
