//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsIncomingPhoneNumbers) DeepCopyInto(out *AccountsIncomingPhoneNumbers) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsIncomingPhoneNumbers.
func (in *AccountsIncomingPhoneNumbers) DeepCopy() *AccountsIncomingPhoneNumbers {
	if in == nil {
		return nil
	}
	out := new(AccountsIncomingPhoneNumbers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsIncomingPhoneNumbers) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsIncomingPhoneNumbersList) DeepCopyInto(out *AccountsIncomingPhoneNumbersList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccountsIncomingPhoneNumbers, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsIncomingPhoneNumbersList.
func (in *AccountsIncomingPhoneNumbersList) DeepCopy() *AccountsIncomingPhoneNumbersList {
	if in == nil {
		return nil
	}
	out := new(AccountsIncomingPhoneNumbersList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsIncomingPhoneNumbersList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsIncomingPhoneNumbersObservation) DeepCopyInto(out *AccountsIncomingPhoneNumbersObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsIncomingPhoneNumbersObservation.
func (in *AccountsIncomingPhoneNumbersObservation) DeepCopy() *AccountsIncomingPhoneNumbersObservation {
	if in == nil {
		return nil
	}
	out := new(AccountsIncomingPhoneNumbersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsIncomingPhoneNumbersParameters) DeepCopyInto(out *AccountsIncomingPhoneNumbersParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsIncomingPhoneNumbersParameters.
func (in *AccountsIncomingPhoneNumbersParameters) DeepCopy() *AccountsIncomingPhoneNumbersParameters {
	if in == nil {
		return nil
	}
	out := new(AccountsIncomingPhoneNumbersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsIncomingPhoneNumbersSpec) DeepCopyInto(out *AccountsIncomingPhoneNumbersSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsIncomingPhoneNumbersSpec.
func (in *AccountsIncomingPhoneNumbersSpec) DeepCopy() *AccountsIncomingPhoneNumbersSpec {
	if in == nil {
		return nil
	}
	out := new(AccountsIncomingPhoneNumbersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsIncomingPhoneNumbersStatus) DeepCopyInto(out *AccountsIncomingPhoneNumbersStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsIncomingPhoneNumbersStatus.
func (in *AccountsIncomingPhoneNumbersStatus) DeepCopy() *AccountsIncomingPhoneNumbersStatus {
	if in == nil {
		return nil
	}
	out := new(AccountsIncomingPhoneNumbersStatus)
	in.DeepCopyInto(out)
	return out
}
