// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Kind{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AccountsCallsParameters are the configurable fields of a AccountsCalls.
//
// These are the parameters of the create operation (CreateCall), plus any the
// update accepts and the create does not. The fields are spelled the way
// Twilio TAKES them -- PascalCase -- because that is the name the request
// carries; status.atProvider spells the same values the way Twilio ANSWERS
// them, in snake_case. Nothing translates between the two, so nothing can
// drift out of a translation layer.
type AccountsCallsParameters struct {
	// To The phone number, SIP address, or client identifier to call.
	// +kubebuilder:validation:Required
	To string `json:"To"`
	// From The phone number or client identifier to use as the caller id. If using a phone number, it must be a Twilio number or a Verified [outgoing caller id](https://www.twilio.com/docs/voice/api/outgoing-caller-ids) for your account. If the `to` parameter is a phone number, `From` must also be a phone number.
	// +kubebuilder:validation:Required
	From string `json:"From"`
	// PathAccountSid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that will create the resource.
	// +optional
	PathAccountSid string `json:"PathAccountSid,omitempty"`
	// Method The HTTP method we should use when calling the `url` parameter's value. Can be: `GET` or `POST` and the default is `POST`. If an `application_sid` parameter is present, this parameter is ignored.
	// +optional
	Method string `json:"Method,omitempty"`
	// FallbackUrl The URL that we call using the `fallback_method` if an error occurs when requesting or executing the TwiML at `url`. If an `application_sid` parameter is present, this parameter is ignored.
	// +optional
	FallbackUrl string `json:"FallbackUrl,omitempty"`
	// FallbackMethod The HTTP method that we should use to request the `fallback_url`. Can be: `GET` or `POST` and the default is `POST`. If an `application_sid` parameter is present, this parameter is ignored.
	// +optional
	FallbackMethod string `json:"FallbackMethod,omitempty"`
	// StatusCallback The URL we should call using the `status_callback_method` to send status information to your application. If no `status_callback_event` is specified, we will send the `completed` status. If an `application_sid` parameter is present, this parameter is ignored. URLs must contain a valid hostname (underscores are not permitted).
	// +optional
	StatusCallback string `json:"StatusCallback,omitempty"`
	// StatusCallbackEvent The call progress events that we will send to the `status_callback` URL. Can be: `initiated`, `ringing`, `answered`, and `completed`. If no event is specified, we send the `completed` status. If you want to receive multiple events, specify each one in a separate `status_callback_event` parameter. See the code sample for [monitoring call progress](https://www.twilio.com/docs/voice/api/call-resource?code-sample=code-create-a-call-resource-and-specify-a-statuscallbackevent&code-sdk-version=json). If an `application_sid` is present, this parameter is ignored.
	// +optional
	StatusCallbackEvent []string `json:"StatusCallbackEvent,omitempty"`
	// StatusCallbackMethod The HTTP method we should use when calling the `status_callback` URL. Can be: `GET` or `POST` and the default is `POST`. If an `application_sid` parameter is present, this parameter is ignored.
	// +optional
	StatusCallbackMethod string `json:"StatusCallbackMethod,omitempty"`
	// SendDigits The string of keys to dial after connecting to the number, with a maximum length of 32 digits. Valid digits in the string include any digit (`0`-`9`), '`A`', '`B`', '`C`', '`D`', '`#`', and '`*`'. You can also use '`w`' to insert a half-second pause and '`W`' to insert a one-second pause. For example, to pause for one second after connecting and then dial extension 1234 followed by the # key, set this parameter to `W1234#`. Be sure to URL-encode this string because the '`#`' character has special meaning in a URL. If both `SendDigits` and `MachineDetection` parameters are provided, then `MachineDetection` will be ignored.
	// +optional
	SendDigits string `json:"SendDigits,omitempty"`
	// Timeout The integer number of seconds that we should allow the phone to ring before assuming there is no answer. The default is `60` seconds and the maximum is `600` seconds. For some call flows, we will add a 5-second buffer to the timeout value you provide. For this reason, a timeout value of 10 seconds could result in an actual timeout closer to 15 seconds. You can set this to a short time, such as `15` seconds, to hang up before reaching an answering machine or voicemail.
	// +optional
	Timeout int `json:"Timeout,omitempty"`
	// Record Whether to record the call. Can be `true` to record the phone call, or `false` to not. The default is `false`. The `recording_url` is sent to the `status_callback` URL.
	// +optional
	Record bool `json:"Record,omitempty"`
	// RecordingChannels The number of channels in the final recording. Can be: `mono` or `dual`. The default is `mono`. `mono` records both legs of the call in a single channel of the recording file. `dual` records each leg to a separate channel of the recording file. The first channel of a dual-channel recording contains the parent call and the second channel contains the child call.
	// +optional
	RecordingChannels string `json:"RecordingChannels,omitempty"`
	// RecordingStatusCallback The URL that we call when the recording is available to be accessed.
	// +optional
	RecordingStatusCallback string `json:"RecordingStatusCallback,omitempty"`
	// RecordingStatusCallbackMethod The HTTP method we should use when calling the `recording_status_callback` URL. Can be: `GET` or `POST` and the default is `POST`.
	// +optional
	RecordingStatusCallbackMethod string `json:"RecordingStatusCallbackMethod,omitempty"`
	// RecordingConfigurationId The identifier of the configuration to be used when creating and processing the recording
	// +optional
	RecordingConfigurationId string `json:"RecordingConfigurationId,omitempty"`
	// SipAuthUsername The username used to authenticate the caller making a SIP call.
	// +optional
	SipAuthUsername string `json:"SipAuthUsername,omitempty"`
	// SipAuthPassword The password required to authenticate the user account specified in `sip_auth_username`.
	// +optional
	SipAuthPassword string `json:"SipAuthPassword,omitempty"`
	// MachineDetection Whether to detect if a human, answering machine, or fax has picked up the call. Can be: `Enable` or `DetectMessageEnd`. Use `Enable` if you would like us to return `AnsweredBy` as soon as the called party is identified. Use `DetectMessageEnd`, if you would like to leave a message on an answering machine. If `send_digits` is provided, this parameter is ignored. For more information, see [Answering Machine Detection](https://www.twilio.com/docs/voice/answering-machine-detection).
	// +optional
	MachineDetection string `json:"MachineDetection,omitempty"`
	// MachineDetectionTimeout The number of seconds that we should attempt to detect an answering machine before timing out and sending a voice request with `AnsweredBy` of `unknown`. The default timeout is 30 seconds.
	// +optional
	MachineDetectionTimeout int `json:"MachineDetectionTimeout,omitempty"`
	// RecordingStatusCallbackEvent The recording status events that will trigger calls to the URL specified in `recording_status_callback`. Can be: `in-progress`, `completed` and `absent`. Defaults to `completed`. Separate multiple values with a space.
	// +optional
	RecordingStatusCallbackEvent []string `json:"RecordingStatusCallbackEvent,omitempty"`
	// Trim Whether to trim any leading and trailing silence from the recording. Can be: `trim-silence` or `do-not-trim` and the default is `trim-silence`.
	// +optional
	Trim string `json:"Trim,omitempty"`
	// CallerId The phone number, SIP address, or Client identifier that made this call. Phone numbers are in [E.164 format](https://wwnw.twilio.com/docs/glossary/what-e164) (e.g., +16175551212). SIP addresses are formatted as `name@company.com`.
	// +optional
	CallerId string `json:"CallerId,omitempty"`
	// MachineDetectionSpeechThreshold The number of milliseconds that is used as the measuring stick for the length of the speech activity, where durations lower than this value will be interpreted as a human and longer than this value as a machine. Possible Values: 1000-6000. Default: 2400.
	// +optional
	MachineDetectionSpeechThreshold int `json:"MachineDetectionSpeechThreshold,omitempty"`
	// MachineDetectionSpeechEndThreshold The number of milliseconds of silence after speech activity at which point the speech activity is considered complete. Possible Values: 500-5000. Default: 1200.
	// +optional
	MachineDetectionSpeechEndThreshold int `json:"MachineDetectionSpeechEndThreshold,omitempty"`
	// MachineDetectionSilenceTimeout The number of milliseconds of initial silence after which an `unknown` AnsweredBy result will be returned. Possible Values: 2000-10000. Default: 5000.
	// +optional
	MachineDetectionSilenceTimeout int `json:"MachineDetectionSilenceTimeout,omitempty"`
	// AsyncAmd Select whether to perform answering machine detection in the background. Default, blocks the execution of the call until Answering Machine Detection is completed. Can be: `true` or `false`.
	// +optional
	AsyncAmd string `json:"AsyncAmd,omitempty"`
	// AsyncAmdStatusCallback The URL that we should call using the `async_amd_status_callback_method` to notify customer application whether the call was answered by human, machine or fax.
	// +optional
	AsyncAmdStatusCallback string `json:"AsyncAmdStatusCallback,omitempty"`
	// AsyncAmdStatusCallbackMethod The HTTP method we should use when calling the `async_amd_status_callback` URL. Can be: `GET` or `POST` and the default is `POST`.
	// +optional
	AsyncAmdStatusCallbackMethod string `json:"AsyncAmdStatusCallbackMethod,omitempty"`
	// Passports The STIR/SHAKEN passport for this call, provided as a base64 encoded string. Multiple passports (at max 5) are comma separated and provided as base64 encoded string
	// +optional
	Passports string `json:"Passports,omitempty"`
	// Byoc The SID of a BYOC (Bring Your Own Carrier) trunk to route this call with. Note that `byoc` is only meaningful when `to` is a phone number; it will otherwise be ignored. (Beta)
	// +optional
	Byoc string `json:"Byoc,omitempty"`
	// CallReason The Reason for the outgoing call. Use it to specify the purpose of the call that is presented on the called party's phone. (Branded Calls Beta)
	// +optional
	CallReason string `json:"CallReason,omitempty"`
	// CallToken A token string needed to invoke a forwarded call. A call_token is generated when an incoming call is received on a Twilio number. Pass an incoming call's call_token value to a forwarded call via the call_token parameter when creating a new call. A forwarded call should bear the same CallerID of the original incoming call.
	// +optional
	CallToken string `json:"CallToken,omitempty"`
	// RecordingTrack The audio track to record for the call. Can be: `inbound`, `outbound` or `both`. The default is `both`. `inbound` records the audio that is received by Twilio. `outbound` records the audio that is generated from Twilio. `both` records the audio that is received and generated by Twilio.
	// +optional
	RecordingTrack string `json:"RecordingTrack,omitempty"`
	// TimeLimit The maximum duration of the call in seconds. Constraints depend on account and configuration.
	// +optional
	TimeLimit int `json:"TimeLimit,omitempty"`
	// ClientNotificationUrl The URL that we should use to deliver `push call notification`.
	// +optional
	ClientNotificationUrl string `json:"ClientNotificationUrl,omitempty"`
	// Url The absolute URL that returns the TwiML instructions for the call. We will call this URL using the `method` when the call connects. For more information, see the [Url Parameter](https://www.twilio.com/docs/voice/make-calls#specify-a-url-parameter) section in [Making Calls](https://www.twilio.com/docs/voice/make-calls).
	// +optional
	Url string `json:"Url,omitempty"`
	// Twiml TwiML instructions for the call Twilio will use without fetching Twiml from url parameter. If both `twiml` and `url` are provided then `twiml` parameter will be ignored. Max 4000 characters.
	// +optional
	Twiml string `json:"Twiml,omitempty"`
	// ApplicationSid The SID of the Application resource that will handle the call, if the call will be handled by an application.
	// +optional
	ApplicationSid string `json:"ApplicationSid,omitempty"`
	// Status
	// +optional
	Status string `json:"Status,omitempty"`
}

// AccountsCallsObservation are the observable fields of a AccountsCalls.
//
// These are the properties of what the read (FetchCall) answers -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AccountsCallsObservation struct {
	Sid             string `json:"sid,omitempty"`
	DateCreated     string `json:"date_created,omitempty"`
	DateUpdated     string `json:"date_updated,omitempty"`
	ParentCallSid   string `json:"parent_call_sid,omitempty"`
	AccountSid      string `json:"account_sid,omitempty"`
	To              string `json:"to,omitempty"`
	ToFormatted     string `json:"to_formatted,omitempty"`
	From            string `json:"from,omitempty"`
	FromFormatted   string `json:"from_formatted,omitempty"`
	PhoneNumberSid  string `json:"phone_number_sid,omitempty"`
	Status          string `json:"status,omitempty"`
	StartTime       string `json:"start_time,omitempty"`
	EndTime         string `json:"end_time,omitempty"`
	Duration        string `json:"duration,omitempty"`
	Price           string `json:"price,omitempty"`
	PriceUnit       string `json:"price_unit,omitempty"`
	Direction       string `json:"direction,omitempty"`
	AnsweredBy      string `json:"answered_by,omitempty"`
	ApiVersion      string `json:"api_version,omitempty"`
	ForwardedFrom   string `json:"forwarded_from,omitempty"`
	GroupSid        string `json:"group_sid,omitempty"`
	CallerName      string `json:"caller_name,omitempty"`
	QueueTime       string `json:"queue_time,omitempty"`
	TrunkSid        string `json:"trunk_sid,omitempty"`
	Uri             string `json:"uri,omitempty"`
	SubresourceUris string `json:"subresource_uris,omitempty"`
}

// A AccountsCallsSpec defines the desired state of a AccountsCalls.
type AccountsCallsSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AccountsCallsParameters `json:"forProvider"`
}

// A AccountsCallsStatus represents the observed state of a AccountsCalls.
type AccountsCallsStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AccountsCallsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AccountsCalls is a managed Twilio resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twilio}
type AccountsCalls struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AccountsCallsSpec   `json:"spec"`
	Status AccountsCallsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountsCallsList contains a list of AccountsCalls
type AccountsCallsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountsCalls `json:"items"`
}

// AccountsCalls type metadata.
var (
	AccountsCallsKind             = reflect.TypeOf(AccountsCalls{}).Name()
	AccountsCallsGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountsCallsKind}.String()
	AccountsCallsKindAPIVersion   = AccountsCallsKind + "." + SchemeGroupVersion.String()
	AccountsCallsGroupVersionKind = SchemeGroupVersion.WithKind(AccountsCallsKind)
)

func init() {
	SchemeBuilder.Register(&AccountsCalls{}, &AccountsCallsList{})
}
