//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsCalls) DeepCopyInto(out *AccountsCalls) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsCalls.
func (in *AccountsCalls) DeepCopy() *AccountsCalls {
	if in == nil {
		return nil
	}
	out := new(AccountsCalls)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsCalls) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsCallsList) DeepCopyInto(out *AccountsCallsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccountsCalls, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsCallsList.
func (in *AccountsCallsList) DeepCopy() *AccountsCallsList {
	if in == nil {
		return nil
	}
	out := new(AccountsCallsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsCallsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsCallsObservation) DeepCopyInto(out *AccountsCallsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsCallsObservation.
func (in *AccountsCallsObservation) DeepCopy() *AccountsCallsObservation {
	if in == nil {
		return nil
	}
	out := new(AccountsCallsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsCallsParameters) DeepCopyInto(out *AccountsCallsParameters) {
	*out = *in
	if in.StatusCallbackEvent != nil {
		in, out := &in.StatusCallbackEvent, &out.StatusCallbackEvent
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RecordingStatusCallbackEvent != nil {
		in, out := &in.RecordingStatusCallbackEvent, &out.RecordingStatusCallbackEvent
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsCallsParameters.
func (in *AccountsCallsParameters) DeepCopy() *AccountsCallsParameters {
	if in == nil {
		return nil
	}
	out := new(AccountsCallsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsCallsSpec) DeepCopyInto(out *AccountsCallsSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsCallsSpec.
func (in *AccountsCallsSpec) DeepCopy() *AccountsCallsSpec {
	if in == nil {
		return nil
	}
	out := new(AccountsCallsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsCallsStatus) DeepCopyInto(out *AccountsCallsStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsCallsStatus.
func (in *AccountsCallsStatus) DeepCopy() *AccountsCallsStatus {
	if in == nil {
		return nil
	}
	out := new(AccountsCallsStatus)
	in.DeepCopyInto(out)
	return out
}
