// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Kind{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AccountsUsageTriggersParameters are the configurable fields of a AccountsUsageTriggers.
//
// These are the parameters of the create operation (CreateUsageTrigger), plus any the
// update accepts and the create does not. The fields are spelled the way
// Twilio TAKES them -- PascalCase -- because that is the name the request
// carries; status.atProvider spells the same values the way Twilio ANSWERS
// them, in snake_case. Nothing translates between the two, so nothing can
// drift out of a translation layer.
type AccountsUsageTriggersParameters struct {
	// CallbackUrl The URL we should call using `callback_method` when the trigger fires.
	// +kubebuilder:validation:Required
	CallbackUrl string `json:"CallbackUrl"`
	// TriggerValue The usage value at which the trigger should fire. For convenience, you can use an offset value such as `+30` to specify a trigger_value that is 30 units more than the current usage value. Be sure to urlencode a `+` as `%2B`.
	// +kubebuilder:validation:Required
	TriggerValue string `json:"TriggerValue"`
	// UsageCategory The usage category that the trigger should watch. Use one of the supported [usage categories](https://www.twilio.com/docs/usage/api/usage-record#usage-categories) for this value.
	// +kubebuilder:validation:Required
	UsageCategory string `json:"UsageCategory"`
	// PathAccountSid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that will create the resource.
	// +optional
	PathAccountSid string `json:"PathAccountSid,omitempty"`
	// CallbackMethod The HTTP method we should use to call `callback_url`. Can be: `GET` or `POST` and the default is `POST`.
	// +optional
	CallbackMethod string `json:"CallbackMethod,omitempty"`
	// FriendlyName A descriptive string that you create to describe the resource. It can be up to 64 characters long.
	// +optional
	FriendlyName string `json:"FriendlyName,omitempty"`
	// Recurring
	// +optional
	Recurring string `json:"Recurring,omitempty"`
	// TriggerBy
	// +optional
	TriggerBy string `json:"TriggerBy,omitempty"`
}

// AccountsUsageTriggersObservation are the observable fields of a AccountsUsageTriggers.
//
// These are the properties of what the read (FetchUsageTrigger) answers -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AccountsUsageTriggersObservation struct {
	AccountSid     string `json:"account_sid,omitempty"`
	ApiVersion     string `json:"api_version,omitempty"`
	CallbackMethod string `json:"callback_method,omitempty"`
	CallbackUrl    string `json:"callback_url,omitempty"`
	CurrentValue   string `json:"current_value,omitempty"`
	DateCreated    string `json:"date_created,omitempty"`
	DateFired      string `json:"date_fired,omitempty"`
	DateUpdated    string `json:"date_updated,omitempty"`
	FriendlyName   string `json:"friendly_name,omitempty"`
	Recurring      string `json:"recurring,omitempty"`
	Sid            string `json:"sid,omitempty"`
	TriggerBy      string `json:"trigger_by,omitempty"`
	TriggerValue   string `json:"trigger_value,omitempty"`
	Uri            string `json:"uri,omitempty"`
	UsageCategory  string `json:"usage_category,omitempty"`
	UsageRecordUri string `json:"usage_record_uri,omitempty"`
}

// A AccountsUsageTriggersSpec defines the desired state of a AccountsUsageTriggers.
type AccountsUsageTriggersSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AccountsUsageTriggersParameters `json:"forProvider"`
}

// A AccountsUsageTriggersStatus represents the observed state of a AccountsUsageTriggers.
type AccountsUsageTriggersStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AccountsUsageTriggersObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AccountsUsageTriggers is a managed Twilio resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twilio}
type AccountsUsageTriggers struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AccountsUsageTriggersSpec   `json:"spec"`
	Status AccountsUsageTriggersStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountsUsageTriggersList contains a list of AccountsUsageTriggers
type AccountsUsageTriggersList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountsUsageTriggers `json:"items"`
}

// AccountsUsageTriggers type metadata.
var (
	AccountsUsageTriggersKind             = reflect.TypeOf(AccountsUsageTriggers{}).Name()
	AccountsUsageTriggersGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountsUsageTriggersKind}.String()
	AccountsUsageTriggersKindAPIVersion   = AccountsUsageTriggersKind + "." + SchemeGroupVersion.String()
	AccountsUsageTriggersGroupVersionKind = SchemeGroupVersion.WithKind(AccountsUsageTriggersKind)
)

func init() {
	SchemeBuilder.Register(&AccountsUsageTriggers{}, &AccountsUsageTriggersList{})
}
