//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsUsageTriggers) DeepCopyInto(out *AccountsUsageTriggers) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsUsageTriggers.
func (in *AccountsUsageTriggers) DeepCopy() *AccountsUsageTriggers {
	if in == nil {
		return nil
	}
	out := new(AccountsUsageTriggers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsUsageTriggers) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsUsageTriggersList) DeepCopyInto(out *AccountsUsageTriggersList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccountsUsageTriggers, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsUsageTriggersList.
func (in *AccountsUsageTriggersList) DeepCopy() *AccountsUsageTriggersList {
	if in == nil {
		return nil
	}
	out := new(AccountsUsageTriggersList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsUsageTriggersList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsUsageTriggersObservation) DeepCopyInto(out *AccountsUsageTriggersObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsUsageTriggersObservation.
func (in *AccountsUsageTriggersObservation) DeepCopy() *AccountsUsageTriggersObservation {
	if in == nil {
		return nil
	}
	out := new(AccountsUsageTriggersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsUsageTriggersParameters) DeepCopyInto(out *AccountsUsageTriggersParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsUsageTriggersParameters.
func (in *AccountsUsageTriggersParameters) DeepCopy() *AccountsUsageTriggersParameters {
	if in == nil {
		return nil
	}
	out := new(AccountsUsageTriggersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsUsageTriggersSpec) DeepCopyInto(out *AccountsUsageTriggersSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsUsageTriggersSpec.
func (in *AccountsUsageTriggersSpec) DeepCopy() *AccountsUsageTriggersSpec {
	if in == nil {
		return nil
	}
	out := new(AccountsUsageTriggersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsUsageTriggersStatus) DeepCopyInto(out *AccountsUsageTriggersStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsUsageTriggersStatus.
func (in *AccountsUsageTriggersStatus) DeepCopy() *AccountsUsageTriggersStatus {
	if in == nil {
		return nil
	}
	out := new(AccountsUsageTriggersStatus)
	in.DeepCopyInto(out)
	return out
}
