// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Kind{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AccountsSigningKeysParameters are the configurable fields of a AccountsSigningKeys.
//
// These are the parameters of the create operation (CreateNewSigningKey), plus any the
// update accepts and the create does not. The fields are spelled the way
// Twilio TAKES them -- PascalCase -- because that is the name the request
// carries; status.atProvider spells the same values the way Twilio ANSWERS
// them, in snake_case. Nothing translates between the two, so nothing can
// drift out of a translation layer.
type AccountsSigningKeysParameters struct {
	// PathAccountSid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that will be responsible for the new Key resource.
	// +optional
	PathAccountSid string `json:"PathAccountSid,omitempty"`
	// FriendlyName A descriptive string that you create to describe the resource. It can be up to 64 characters long.
	// +optional
	FriendlyName string `json:"FriendlyName,omitempty"`
}

// AccountsSigningKeysObservation are the observable fields of a AccountsSigningKeys.
//
// These are the properties of what the read (FetchSigningKey) answers -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AccountsSigningKeysObservation struct {
	Sid          string `json:"sid,omitempty"`
	FriendlyName string `json:"friendly_name,omitempty"`
	DateCreated  string `json:"date_created,omitempty"`
	DateUpdated  string `json:"date_updated,omitempty"`
}

// A AccountsSigningKeysSpec defines the desired state of a AccountsSigningKeys.
type AccountsSigningKeysSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AccountsSigningKeysParameters `json:"forProvider"`
}

// A AccountsSigningKeysStatus represents the observed state of a AccountsSigningKeys.
type AccountsSigningKeysStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AccountsSigningKeysObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AccountsSigningKeys is a managed Twilio resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twilio}
type AccountsSigningKeys struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AccountsSigningKeysSpec   `json:"spec"`
	Status AccountsSigningKeysStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountsSigningKeysList contains a list of AccountsSigningKeys
type AccountsSigningKeysList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountsSigningKeys `json:"items"`
}

// AccountsSigningKeys type metadata.
var (
	AccountsSigningKeysKind             = reflect.TypeOf(AccountsSigningKeys{}).Name()
	AccountsSigningKeysGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountsSigningKeysKind}.String()
	AccountsSigningKeysKindAPIVersion   = AccountsSigningKeysKind + "." + SchemeGroupVersion.String()
	AccountsSigningKeysGroupVersionKind = SchemeGroupVersion.WithKind(AccountsSigningKeysKind)
)

func init() {
	SchemeBuilder.Register(&AccountsSigningKeys{}, &AccountsSigningKeysList{})
}
