//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSigningKeys) DeepCopyInto(out *AccountsSigningKeys) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSigningKeys.
func (in *AccountsSigningKeys) DeepCopy() *AccountsSigningKeys {
	if in == nil {
		return nil
	}
	out := new(AccountsSigningKeys)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsSigningKeys) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSigningKeysList) DeepCopyInto(out *AccountsSigningKeysList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccountsSigningKeys, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSigningKeysList.
func (in *AccountsSigningKeysList) DeepCopy() *AccountsSigningKeysList {
	if in == nil {
		return nil
	}
	out := new(AccountsSigningKeysList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountsSigningKeysList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSigningKeysObservation) DeepCopyInto(out *AccountsSigningKeysObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSigningKeysObservation.
func (in *AccountsSigningKeysObservation) DeepCopy() *AccountsSigningKeysObservation {
	if in == nil {
		return nil
	}
	out := new(AccountsSigningKeysObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSigningKeysParameters) DeepCopyInto(out *AccountsSigningKeysParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSigningKeysParameters.
func (in *AccountsSigningKeysParameters) DeepCopy() *AccountsSigningKeysParameters {
	if in == nil {
		return nil
	}
	out := new(AccountsSigningKeysParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSigningKeysSpec) DeepCopyInto(out *AccountsSigningKeysSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSigningKeysSpec.
func (in *AccountsSigningKeysSpec) DeepCopy() *AccountsSigningKeysSpec {
	if in == nil {
		return nil
	}
	out := new(AccountsSigningKeysSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountsSigningKeysStatus) DeepCopyInto(out *AccountsSigningKeysStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountsSigningKeysStatus.
func (in *AccountsSigningKeysStatus) DeepCopy() *AccountsSigningKeysStatus {
	if in == nil {
		return nil
	}
	out := new(AccountsSigningKeysStatus)
	in.DeepCopyInto(out)
	return out
}
